// Ingredient knowledge base used by the evidence-first scorer.
// Every entry is something a dermatology / regulatory source says about a NAMED INCI ingredient —
// never a seller adjective. Sources are listed once in SOURCES and referenced by key.
// CommonJS so the scrape generators outside the repo can require() it too.

const SOURCES = {
  eu1223: { label: 'EU Cosmetics Regulation 1223/2009 (Art. 19 labelling order; Annex III fragrance allergens; Annex II bans)', url: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02009R1223-20240424' },
  sccsMi: { label: 'EU Reg. 2016/1198 — methylisothiazolinone banned in leave-on products', url: 'https://eur-lex.europa.eu/eli/reg/2016/1198/oj' },
  eu2019_831: { label: 'EU Reg. 2019/831 — quaternium-15 and other CMR substances prohibited', url: 'https://eur-lex.europa.eu/eli/reg/2019/831/oj' },
  fdaTriclosan: { label: 'US FDA final rule (2016) — triclosan removed from OTC antiseptic washes', url: 'https://www.federalregister.gov/documents/2016/09/06/2016-21337/safety-and-effectiveness-of-consumer-antiseptics-topical-antimicrobial-drug-products-for-over-the-counter-human-use' },
  acdsFragrance: { label: 'de Groot 2020, Dermatitis — fragrances: contact allergy and other adverse effects (review)', url: 'https://pubmed.ncbi.nlm.nih.gov/31433384/' },
  aadScrub: { label: 'AAD — how to safely exfoliate (avoid abrasive scrubs on sensitive/acne-prone skin)', url: 'https://www.aad.org/public/everyday-care/skin-care-secrets/routine/safely-exfoliate-at-home' },
  cdscoHq: { label: 'Schwartz et al., StatPearls (NCBI) — hydroquinone is a prescription-only depigmenting agent; combination use needs a dermatologist', url: 'https://www.ncbi.nlm.nih.gov/books/NBK539693/' },
  sccsParabens: { label: 'SCCS/1514/13 — methyl-/ethylparaben safe at permitted limits (basis for NOT penalising parabens)', url: 'https://health.ec.europa.eu/system/files/2016-11/sccs_o_132_0.pdf' },
  niacinamide: { label: 'Wohlrab & Kreft 2014, Skin Pharmacol Physiol — niacinamide review', url: 'https://doi.org/10.1159/000359974' },
  retinoids: { label: 'Mukherjee et al. 2006, Clin Interv Aging — retinoids in skin ageing', url: 'https://doi.org/10.2147/ciia.2006.1.4.327' },
  vitc: { label: 'Al-Niaimi & Chiang 2017, J Clin Aesthet Dermatol — topical vitamin C review', url: 'https://pubmed.ncbi.nlm.nih.gov/29104718/' },
  aha: { label: 'Tang & Yang 2018, Molecules — dual effects of AHAs on skin', url: 'https://doi.org/10.3390/molecules23040863' },
  bha: { label: 'Arif 2015, Clin Cosmet Investig Dermatol — salicylic acid as peeling agent', url: 'https://doi.org/10.2147/CCID.S84765' },
  azelaic: { label: 'Fitton & Goa 1991, Drugs — azelaic acid review', url: 'https://doi.org/10.2165/00003495-199141050-00007' },
  pigment: { label: 'Sarkar et al. 2013, J Cutan Aesthet Surg — cosmeceuticals for hyperpigmentation (kojic, arbutin, licorice, tranexamic)', url: 'https://doi.org/10.4103/0974-2077.110089' },
  tranexamic: { label: 'Kim et al. 2016, Br J Dermatol — topical tranexamic acid for melasma', url: 'https://doi.org/10.1111/bjd.14300' },
  bakuchiol: { label: 'Dhaliwal et al. 2019, Br J Dermatol — bakuchiol vs retinol RCT', url: 'https://doi.org/10.1111/bjd.16918' },
  ceramide: { label: 'Spada et al. 2018, Clin Cosmet Investig Dermatol — ceramide moisturiser barrier study', url: 'https://doi.org/10.2147/CCID.S177697' },
  ha: { label: 'Bukhari et al. 2018, Int J Biol Macromol — hyaluronic acid in skin', url: 'https://doi.org/10.1016/j.ijbiomac.2018.09.188' },
  urea: { label: 'Celleno 2018, Dermatol Ther — urea in dermatology', url: 'https://doi.org/10.1111/dth.12690' },
  kp: { label: 'Pennycook & McCready 2023 StatPearls — keratosis pilaris (lactic acid / urea / ammonium lactate)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK546708/' },
  oat: { label: 'Reynertson et al. 2015, J Drugs Dermatol — colloidal oatmeal anti-inflammatory activity', url: 'https://pubmed.ncbi.nlm.nih.gov/25607907/' },
  panthenol: { label: 'Proksch et al. 2017, J Dermatolog Treat — topical dexpanthenol', url: 'https://doi.org/10.1080/09546634.2017.1325310' },
  centella: { label: 'Bylka et al. 2013, Postepy Dermatol Alergol — Centella asiatica in cosmetology', url: 'https://doi.org/10.5114/pdia.2013.33378' },
  petrolatum: { label: 'Sethi et al. 2016, Indian J Dermatol — moisturizers: the slippery road (occlusives, humectants)', url: 'https://doi.org/10.4103/0019-5154.182427' },
  sunFilters: { label: 'Geoffrey et al. 2019, Saudi Pharm J — sunscreen filters review (UVA/UVB coverage, photostability)', url: 'https://doi.org/10.1016/j.jsps.2019.08.003' },
  surfactants: { label: 'Ananthapadmanabhan et al. 2004, Dermatol Ther — cleansing without compromise (SLS vs mild surfactants)', url: 'https://doi.org/10.1111/j.1396-0296.2004.04S1002.x' },
  alcohol: { label: 'Lachenmeier 2008, J Occup Med Toxicol — safety of topical ethanol', url: 'https://doi.org/10.1186/1745-6673-3-26' },
  peptides: { label: 'Schagen 2017, Cosmetics — topical peptide treatments', url: 'https://doi.org/10.3390/cosmetics4020016' },
  caffeine: { label: 'Herman & Herman 2013, Skin Pharmacol Physiol — caffeine in cosmetics', url: 'https://doi.org/10.1159/000343174' },
  squalane: { label: 'Huang et al. 2009, Molecules — squalene/squalane in skin care', url: 'https://doi.org/10.3390/molecules14010540' },
  teaTree: { label: 'Hammer 2015, Int J Antimicrob Agents — tea tree oil for acne (efficacy) + contact sensitisation risk', url: 'https://doi.org/10.1016/j.ijantimicag.2014.10.011' },
  greenTea: { label: 'OyetakinWhite et al. 2012, Oxid Med Cell Longev — green tea polyphenols and skin', url: 'https://doi.org/10.1155/2012/560682' },
  glycerin: { label: 'Fluhr et al. 2008, Br J Dermatol — glycerol and the skin', url: 'https://doi.org/10.1111/j.1365-2133.2008.08643.x' },
};

// Evidence grade: A = multiple RCTs / regulatory monograph, B = clinical studies, C = in-vitro / traditional use.
// roles: which product categories treat this as a CORE active (scored higher) vs a supporting ingredient.
const ACTIVES = [
  ['niacinamide', 'A', 'niacinamide', ['niacinamide', 'facewash', 'toner', 'essence', 'moisturizer', 'sunscreen', 'detan', 'pigmentation', 'eyecream', 'facemask', 'bodylotion']],
  ['retinol', 'A', 'retinoids', ['retinol', 'eyecream', 'moisturizer']],
  ['retinal', 'A', 'retinoids', ['retinol', 'eyecream']],
  ['retinaldehyde', 'A', 'retinoids', ['retinol', 'eyecream']],
  ['hydroxypinacolone retinoate', 'B', 'retinoids', ['retinol', 'eyecream']],
  ['retinyl palmitate', 'C', 'retinoids', ['retinol', 'eyecream']],
  ['retinyl acetate', 'C', 'retinoids', ['retinol', 'eyecream']],
  ['retinyl propionate', 'B', 'retinoids', ['retinol']],
  ['adapalene', 'A', 'retinoids', ['retinol', 'salicylic']],
  ['tretinoin', 'A', 'retinoids', ['retinol', 'pigmentation']],
  ['bakuchiol', 'B', 'bakuchiol', ['retinol', 'eyecream']],
  ['ascorbic acid', 'A', 'vitc', ['vitaminc', 'detan', 'pigmentation', 'eyecream', 'toner', 'essence', 'facemask']],
  ['3-o-ethyl ascorbic acid', 'B', 'vitc', ['vitaminc', 'detan', 'pigmentation', 'toner', 'essence']],
  ['ethyl ascorbic acid', 'B', 'vitc', ['vitaminc', 'detan', 'pigmentation']],
  ['ascorbyl glucoside', 'B', 'vitc', ['vitaminc', 'detan', 'pigmentation', 'toner', 'essence']],
  ['sodium ascorbyl phosphate', 'B', 'vitc', ['vitaminc', 'detan', 'pigmentation', 'facewash']],
  ['magnesium ascorbyl phosphate', 'B', 'vitc', ['vitaminc', 'detan', 'pigmentation']],
  ['tetrahexyldecyl ascorbate', 'B', 'vitc', ['vitaminc', 'detan', 'pigmentation', 'faceoil']],
  ['ascorbyl tetraisopalmitate', 'B', 'vitc', ['vitaminc', 'faceoil']],
  ['ascorbyl palmitate', 'C', 'vitc', ['vitaminc']],
  ['ferulic acid', 'B', 'vitc', ['vitaminc']],
  ['tocopherol', 'B', 'vitc', ['vitaminc', 'faceoil', 'moisturizer', 'bodylotion', 'eyecream']],
  ['tocopheryl acetate', 'B', 'vitc', ['vitaminc', 'faceoil', 'moisturizer', 'bodylotion', 'eyecream']],
  ['glycolic acid', 'A', 'aha', ['exfoliator', 'toner', 'detan', 'pigmentation', 'kp', 'facewash', 'bodywash', 'bodylotion']],
  ['lactic acid', 'A', 'aha', ['exfoliator', 'toner', 'detan', 'pigmentation', 'kp', 'bodylotion', 'facewash', 'bodywash']],
  ['mandelic acid', 'B', 'aha', ['exfoliator', 'toner', 'detan', 'pigmentation', 'salicylic']],
  ['gluconolactone', 'B', 'aha', ['exfoliator', 'toner']],
  ['lactobionic acid', 'B', 'aha', ['exfoliator', 'toner']],
  ['citric acid', 'C', 'aha', []],
  ['salicylic acid', 'A', 'bha', ['salicylic', 'exfoliator', 'facewash', 'toner', 'kp', 'bodywash']],
  ['betaine salicylate', 'B', 'bha', ['salicylic', 'exfoliator', 'toner']],
  ['azelaic acid', 'A', 'azelaic', ['pigmentation', 'detan', 'salicylic', 'niacinamide']],
  ['kojic acid', 'B', 'pigment', ['detan', 'pigmentation', 'facewash', 'facemask']],
  ['kojic dipalmitate', 'B', 'pigment', ['detan', 'pigmentation']],
  ['alpha-arbutin', 'B', 'pigment', ['detan', 'pigmentation', 'vitaminc', 'niacinamide', 'essence', 'toner']],
  ['arbutin', 'B', 'pigment', ['detan', 'pigmentation', 'vitaminc', 'niacinamide']],
  ['tranexamic acid', 'B', 'tranexamic', ['detan', 'pigmentation', 'vitaminc', 'niacinamide', 'eyecream']],
  ['glycyrrhiza glabra root extract', 'B', 'pigment', ['detan', 'pigmentation', 'vitaminc']],
  ['dipotassium glycyrrhizate', 'B', 'pigment', ['detan', 'pigmentation']],
  ['glabridin', 'B', 'pigment', ['detan', 'pigmentation']],
  ['hexylresorcinol', 'B', 'pigment', ['detan', 'pigmentation']],
  ['4-butylresorcinol', 'B', 'pigment', ['detan', 'pigmentation']],
  ['isobutylamido thiazolyl resorcinol', 'B', 'pigment', ['detan', 'pigmentation']],
  ['hydroquinone', 'A', 'pigment', ['pigmentation']],
  ['cysteamine', 'B', 'pigment', ['pigmentation']],
  ['glutathione', 'C', 'pigment', ['detan', 'pigmentation']],
  ['hyaluronic acid', 'B', 'ha', ['essence', 'toner', 'moisturizer', 'eyecream', 'facemask', 'vitaminc', 'niacinamide']],
  ['sodium hyaluronate', 'B', 'ha', ['essence', 'toner', 'moisturizer', 'eyecream', 'facemask', 'vitaminc', 'niacinamide']],
  ['hydrolyzed hyaluronic acid', 'B', 'ha', ['essence', 'toner', 'moisturizer', 'eyecream']],
  ['sodium acetylated hyaluronate', 'B', 'ha', ['essence', 'toner', 'moisturizer']],
  ['glycerin', 'A', 'glycerin', ['moisturizer', 'bodylotion', 'toner', 'essence', 'facewash', 'bodywash', 'facemask', 'eyecream', 'kp']],
  ['urea', 'A', 'urea', ['kp', 'bodylotion', 'moisturizer']],
  ['ammonium lactate', 'A', 'kp', ['kp', 'bodylotion']],
  ['ceramide np', 'B', 'ceramide', ['moisturizer', 'bodylotion', 'eyecream', 'kp', 'essence', 'toner', 'facewash']],
  ['ceramide ap', 'B', 'ceramide', ['moisturizer', 'bodylotion', 'eyecream', 'kp']],
  ['ceramide eop', 'B', 'ceramide', ['moisturizer', 'bodylotion', 'eyecream', 'kp']],
  ['ceramide ns', 'B', 'ceramide', ['moisturizer', 'bodylotion']],
  ['ceramide eos', 'B', 'ceramide', ['moisturizer', 'bodylotion', 'eyecream', 'kp']],
  ['cholesterol', 'B', 'ceramide', ['moisturizer', 'bodylotion', 'kp']],
  ['panthenol', 'B', 'panthenol', ['moisturizer', 'bodylotion', 'toner', 'essence', 'facewash', 'eyecream', 'facemask', 'sunscreen']],
  ['allantoin', 'C', 'panthenol', ['moisturizer', 'bodylotion', 'toner']],
  ['bisabolol', 'B', 'centella', ['moisturizer', 'toner', 'essence', 'sunscreen']],
  ['centella asiatica extract', 'B', 'centella', ['moisturizer', 'toner', 'essence', 'facewash', 'sunscreen', 'facemask']],
  ['madecassoside', 'B', 'centella', ['moisturizer', 'toner', 'essence']],
  ['asiaticoside', 'B', 'centella', ['moisturizer', 'toner', 'essence']],
  ['avena sativa kernel flour', 'B', 'oat', ['bodylotion', 'moisturizer', 'bodywash', 'facewash', 'kp']],
  ['avena sativa kernel extract', 'B', 'oat', ['bodylotion', 'moisturizer', 'bodywash']],
  ['colloidal oatmeal', 'B', 'oat', ['bodylotion', 'moisturizer', 'bodywash']],
  ['petrolatum', 'A', 'petrolatum', ['bodylotion', 'moisturizer', 'kp']],
  ['dimethicone', 'B', 'petrolatum', ['bodylotion', 'moisturizer', 'kp']],
  ['shea butter', 'B', 'petrolatum', ['bodylotion', 'moisturizer', 'kp']],
  ['butyrospermum parkii butter', 'B', 'petrolatum', ['bodylotion', 'moisturizer', 'kp']],
  ['squalane', 'B', 'squalane', ['faceoil', 'moisturizer', 'eyecream', 'bodylotion']],
  ['zinc oxide', 'A', 'sunFilters', ['sunscreen']],
  ['titanium dioxide', 'A', 'sunFilters', ['sunscreen']],
  ['butyl methoxydibenzoylmethane', 'A', 'sunFilters', ['sunscreen']],
  ['avobenzone', 'A', 'sunFilters', ['sunscreen']],
  ['octocrylene', 'A', 'sunFilters', ['sunscreen']],
  ['homosalate', 'A', 'sunFilters', ['sunscreen']],
  ['ethylhexyl methoxycinnamate', 'A', 'sunFilters', ['sunscreen']],
  ['octinoxate', 'A', 'sunFilters', ['sunscreen']],
  ['ethylhexyl salicylate', 'A', 'sunFilters', ['sunscreen']],
  ['octisalate', 'A', 'sunFilters', ['sunscreen']],
  ['phenylbenzimidazole sulfonic acid', 'A', 'sunFilters', ['sunscreen']],
  ['benzophenone-3', 'A', 'sunFilters', ['sunscreen']],
  ['benzophenone-4', 'A', 'sunFilters', ['sunscreen']],
  ['bis-ethylhexyloxyphenol methoxyphenyl triazine', 'A', 'sunFilters', ['sunscreen']],
  ['methylene bis-benzotriazolyl tetramethylbutylphenol', 'A', 'sunFilters', ['sunscreen']],
  ['diethylamino hydroxybenzoyl hexyl benzoate', 'A', 'sunFilters', ['sunscreen']],
  ['terephthalylidene dicamphor sulfonic acid', 'A', 'sunFilters', ['sunscreen']],
  ['drometrizole trisiloxane', 'A', 'sunFilters', ['sunscreen']],
  ['methoxypropylamino cyclohexenylidene ethoxyethylcyanoacetate', 'A', 'sunFilters', ['sunscreen']],
  ['diethylhexyl butamido triazone', 'A', 'sunFilters', ['sunscreen']],
  ['ethylhexyl triazone', 'A', 'sunFilters', ['sunscreen']],
  ['tris-biphenyl triazine', 'A', 'sunFilters', ['sunscreen']],
  ['polysilicone-15', 'A', 'sunFilters', ['sunscreen']],
  ['isoamyl p-methoxycinnamate', 'A', 'sunFilters', ['sunscreen']],
  ['palmitoyl tripeptide-1', 'B', 'peptides', ['eyecream', 'moisturizer', 'retinol', 'essence']],
  ['palmitoyl tetrapeptide-7', 'B', 'peptides', ['eyecream', 'moisturizer', 'retinol', 'essence']],
  ['palmitoyl pentapeptide-4', 'B', 'peptides', ['eyecream', 'moisturizer']],
  ['acetyl hexapeptide-8', 'B', 'peptides', ['eyecream', 'moisturizer']],
  ['copper tripeptide-1', 'B', 'peptides', ['eyecream', 'moisturizer']],
  ['caffeine', 'B', 'caffeine', ['eyecream', 'facemask']],
  ['adenosine', 'B', 'peptides', ['eyecream', 'moisturizer', 'essence']],
  ['camellia sinensis leaf extract', 'B', 'greenTea', ['toner', 'essence', 'facewash', 'sunscreen', 'facemask', 'moisturizer']],
  ['epigallocatechin gallate', 'B', 'greenTea', ['toner', 'essence', 'sunscreen']],
  ['melaleuca alternifolia leaf oil', 'B', 'teaTree', ['facewash', 'salicylic', 'toner']],
  ['sulfur', 'B', 'bha', ['salicylic', 'facemask']],
  ['benzoyl peroxide', 'A', 'bha', ['salicylic', 'facewash']],
  ['zinc pca', 'B', 'niacinamide', ['toner', 'salicylic', 'niacinamide', 'facewash']],
  ['aloe barbadensis leaf juice', 'B', 'centella', ['toner', 'essence', 'facemask', 'moisturizer', 'bodylotion', 'sunscreen']],
  ['aloe barbadensis leaf extract', 'B', 'centella', ['toner', 'essence', 'facemask', 'moisturizer', 'bodylotion', 'sunscreen']],
  ['snail secretion filtrate', 'C', 'ha', ['essence', 'toner', 'moisturizer']],
  ['galactomyces ferment filtrate', 'C', 'ha', ['essence', 'toner']],
  ['saccharomyces ferment filtrate', 'C', 'ha', ['essence', 'toner']],
  ['oryza sativa extract', 'C', 'ha', ['essence', 'toner', 'facewash']],
  ['kaolin', 'C', 'bha', ['facemask', 'exfoliator']],
  ['bentonite', 'C', 'bha', ['facemask', 'exfoliator']],
  ['charcoal powder', 'C', 'bha', ['facemask', 'facewash']],
  ['curcuma longa root extract', 'C', 'greenTea', ['detan', 'facemask', 'facewash']],
  ['resveratrol', 'B', 'greenTea', ['vitaminc', 'moisturizer', 'eyecream']],
  ['ubiquinone', 'B', 'greenTea', ['moisturizer', 'eyecream']],
  ['beta-glucan', 'B', 'centella', ['essence', 'toner', 'moisturizer']],
  ['rosa canina fruit oil', 'B', 'squalane', ['faceoil']],
  ['simmondsia chinensis seed oil', 'B', 'squalane', ['faceoil', 'bodylotion']],
  ['argania spinosa kernel oil', 'B', 'squalane', ['faceoil', 'bodylotion']],
  ['prunus amygdalus dulcis oil', 'B', 'squalane', ['faceoil', 'bodylotion']],
  ['helianthus annuus seed oil', 'B', 'squalane', ['faceoil', 'bodylotion', 'moisturizer']],
  ['cocos nucifera oil', 'C', 'squalane', ['bodylotion']],
  ['crocus sativus flower extract', 'C', 'pigment', ['faceoil', 'detan']],
];

// Mild surfactants preferred by the cleansing literature (core actives for wash categories).
const MILD_SURFACTANTS = ['sodium cocoyl isethionate', 'cocamidopropyl betaine', 'coco-glucoside', 'decyl glucoside',
  'lauryl glucoside', 'sodium lauroyl sarcosinate', 'sodium cocoyl glycinate', 'sodium cocoyl glutamate',
  'disodium cocoamphodiacetate', 'sodium cocoamphoacetate', 'sodium methyl cocoyl taurate', 'lauryl hydroxysultaine',
  'cocamidopropyl hydroxysultaine', 'sodium lauroyl methyl isethionate', 'sodium laurylglucosides hydroxypropylsulfonate',
  'disodium laureth sulfosuccinate', 'sodium lauroamphoacetate', 'potassium cocoyl glycinate', 'sodium cocoyl alaninate',
  'sodium lauroyl lactylate', 'sodium c14-16 olefin sulfonate'];

// Preservatives are legally capped near 1%; on an EU/India-style descending INCI list, anything AFTER the first of these is ≤1%.
const ONE_PERCENT_MARKERS = ['phenoxyethanol', 'sodium benzoate', 'potassium sorbate', 'ethylhexylglycerin', 'chlorphenesin',
  'benzyl alcohol', 'methylparaben', 'propylparaben', 'ethylparaben', 'butylparaben', 'dmdm hydantoin', 'methylisothiazolinone',
  'methylchloroisothiazolinone', 'imidazolidinyl urea', 'diazolidinyl urea', 'sodium hydroxymethylglycinate', 'caprylhydroxamic acid',
  'sodium dehydroacetate', 'dehydroacetic acid', 'benzoic acid', 'sorbic acid', 'iodopropynyl butylcarbamate', 'triclosan',
  'disodium edta', 'tetrasodium edta', 'trisodium ethylenediamine disuccinate', 'parfum', 'fragrance'];

const WATER_FIRST = ['aqua', 'water', 'purified water', 'aqua (water)', 'water (aqua)', 'eau', 'aqua/water', 'water/aqua',
  'aqua/water/eau', 'deionized water', 'demineralized water', 'aqua purificata', 'rose water', 'rosa damascena flower water',
  'hamamelis virginiana water', 'alcohol denat', 'alcohol', 'glycerin', 'butylene glycol', 'cyclopentasiloxane', 'dimethicone',
  'squalane', 'caprylic/capric triglyceride', 'petrolatum', 'mineral oil', 'paraffinum liquidum', 'helianthus annuus seed oil',
  'simmondsia chinensis seed oil', 'prunus amygdalus dulcis oil', 'cocos nucifera oil', 'sesamum indicum seed oil',
  'rosa canina fruit oil', 'argania spinosa kernel oil', 'oryza sativa bran oil', 'zinc oxide', 'titanium dioxide', 'kaolin',
  'bentonite', 'sodium hyaluronate', 'niacinamide', 'ascorbic acid', 'urea', 'propanediol', 'isododecane', 'isopropyl myristate',
  'c12-15 alkyl benzoate', 'ethylhexyl methoxycinnamate', 'homosalate', 'octocrylene', 'talc', 'sodium bicarbonate',
  'lactic acid', 'glycolic acid', 'polysorbate 20', 'hydrogenated polyisobutene', 'isohexadecane', 'ethanol'];

module.exports = { SOURCES, ACTIVES, MILD_SURFACTANTS, ONE_PERCENT_MARKERS, WATER_FIRST };
