// Ingredient knowledge base used by the evidence-first scorer.
// Every entry is something a dermatology / regulatory source says about a NAMED INCI ingredient —
// never a seller adjective. Sources are listed once in SOURCES and referenced by key.
// CommonJS so the scrape generators outside the repo can require() it too.

const SOURCES = {
  eu1223: { label: 'EU Cosmetics Regulation 1223/2009 (Art. 19 labelling order; Annex III fragrance allergens; Annex II bans)', url: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02009R1223-20240424' },
  sccsMi: { label: 'EU Reg. 2016/1198 — methylisothiazolinone banned in leave-on products', url: 'https://eur-lex.europa.eu/eli/reg/2016/1198/oj' },
  eu2019_831: { label: 'EU Reg. 2019/831 — quaternium-15 and other CMR substances prohibited', url: 'https://eur-lex.europa.eu/eli/reg/2019/831/oj' },
  fdaTriclosan: { label: 'US FDA final rule (2016) — triclosan removed from OTC antiseptic washes', url: 'https://www.federalregister.gov/documents/2016/09/06/2016-21337/safety-and-effectiveness-of-consumer-antiseptics-topical-antimicrobial-drug-products-for-over-the-counter-human-use' },
  acdsFragrance: { label: 'de Groot 2020, Dermatitis — fragrances: contact allergy and other adverse effects (review)', url: 'https://pubmed.ncbi.nlm.nih.gov/31433384/' },
  aadScrub: { label: 'AAD — how to safely exfoliate (avoid abrasive scrubs on sensitive/acne-prone skin)', url: 'https://www.aad.org/public/everyday-care/skin-care-secrets/routine/safely-exfoliate-at-home' },
  cdscoHq: { label: 'Schwartz et al., StatPearls (NCBI) — hydroquinone is a prescription-only depigmenting agent; combination use needs a dermatologist', url: 'https://www.ncbi.nlm.nih.gov/books/NBK539693/' },
  sccsParabens: { label: 'SCCS/1514/13 — methyl-/ethylparaben safe at permitted limits (basis for NOT penalising parabens)', url: 'https://health.ec.europa.eu/system/files/2016-11/sccs_o_132_0.pdf' },
  niacinamide: { label: 'Wohlrab & Kreft 2014, Skin Pharmacol Physiol — niacinamide review', url: 'https://doi.org/10.1159/000359974' },
  retinoids: { label: 'Mukherjee et al. 2006, Clin Interv Aging — retinoids in skin ageing', url: 'https://doi.org/10.2147/ciia.2006.1.4.327' },
  vitc: { label: 'Al-Niaimi & Chiang 2017, J Clin Aesthet Dermatol — topical vitamin C review', url: 'https://pubmed.ncbi.nlm.nih.gov/29104718/' },
  aha: { label: 'Tang & Yang 2018, Molecules — dual effects of AHAs on skin', url: 'https://doi.org/10.3390/molecules23040863' },
  bha: { label: 'Arif 2015, Clin Cosmet Investig Dermatol — salicylic acid as peeling agent', url: 'https://doi.org/10.2147/CCID.S84765' },
  azelaic: { label: 'Fitton & Goa 1991, Drugs — azelaic acid review', url: 'https://doi.org/10.2165/00003495-199141050-00007' },
  pigment: { label: 'Sarkar et al. 2013, J Cutan Aesthet Surg — cosmeceuticals for hyperpigmentation (kojic, arbutin, licorice, tranexamic)', url: 'https://doi.org/10.4103/0974-2077.110089' },
  tranexamic: { label: 'Kim et al. 2016, Br J Dermatol — topical tranexamic acid for melasma', url: 'https://doi.org/10.1111/bjd.14300' },
  bakuchiol: { label: 'Dhaliwal et al. 2019, Br J Dermatol — bakuchiol vs retinol RCT', url: 'https://doi.org/10.1111/bjd.16918' },
  ceramide: { label: 'Spada et al. 2018, Clin Cosmet Investig Dermatol — ceramide moisturiser barrier study', url: 'https://doi.org/10.2147/CCID.S177697' },
  ha: { label: 'Bukhari et al. 2018, Int J Biol Macromol — hyaluronic acid in skin', url: 'https://doi.org/10.1016/j.ijbiomac.2018.09.188' },
  urea: { label: 'Celleno 2018, Dermatol Ther — urea in dermatology', url: 'https://doi.org/10.1111/dth.12690' },
  kp: { label: 'Pennycook & McCready 2023 StatPearls — keratosis pilaris (lactic acid / urea / ammonium lactate)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK546708/' },
  oat: { label: 'Reynertson et al. 2015, J Drugs Dermatol — colloidal oatmeal anti-inflammatory activity', url: 'https://pubmed.ncbi.nlm.nih.gov/25607907/' },
  panthenol: { label: 'Proksch et al. 2017, J Dermatolog Treat — topical dexpanthenol', url: 'https://doi.org/10.1080/09546634.2017.1325310' },
  centella: { label: 'Bylka et al. 2013, Postepy Dermatol Alergol — Centella asiatica in cosmetology', url: 'https://doi.org/10.5114/pdia.2013.33378' },
  petrolatum: { label: 'Sethi et al. 2016, Indian J Dermatol — moisturizers: the slippery road (occlusives, humectants)', url: 'https://doi.org/10.4103/0019-5154.182427' },
  sunFilters: { label: 'Geoffrey et al. 2019, Saudi Pharm J — sunscreen filters review (UVA/UVB coverage, photostability)', url: 'https://doi.org/10.1016/j.jsps.2019.08.003' },
  surfactants: { label: 'Ananthapadmanabhan et al. 2004, Dermatol Ther — cleansing without compromise (SLS vs mild surfactants)', url: 'https://doi.org/10.1111/j.1396-0296.2004.04S1002.x' },
  alcohol: { label: 'Lachenmeier 2008, J Occup Med Toxicol — safety of topical ethanol', url: 'https://doi.org/10.1186/1745-6673-3-26' },
  peptides: { label: 'Schagen 2017, Cosmetics — topical peptide treatments', url: 'https://doi.org/10.3390/cosmetics4020016' },
  caffeine: { label: 'Herman & Herman 2013, Skin Pharmacol Physiol — caffeine in cosmetics', url: 'https://doi.org/10.1159/000343174' },
  squalane: { label: 'Huang et al. 2009, Molecules — squalene/squalane in skin care', url: 'https://doi.org/10.3390/molecules14010540' },
  teaTree: { label: 'Hammer 2015, Int J Antimicrob Agents — tea tree oil for acne (efficacy) + contact sensitisation risk', url: 'https://doi.org/10.1016/j.ijantimicag.2014.10.011' },
  greenTea: { label: 'OyetakinWhite et al. 2012, Oxid Med Cell Longev — green tea polyphenols and skin', url: 'https://doi.org/10.1155/2012/560682' },
  glycerin: { label: 'Fluhr et al. 2008, Br J Dermatol — glycerol and the skin', url: 'https://doi.org/10.1111/j.1365-2133.2008.08643.x' },
  // Hair care
  dandruff: { label: 'Borda & Wikramanayake 2015, J Clin Investig Dermatol — seborrheic dermatitis and dandruff: comprehensive review (ketoconazole, zinc pyrithione, selenium sulfide, ciclopirox, salicylic acid, coal tar)', url: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4852869/' },
  dandruffIndia: { label: 'Ranganathan & Mukhopadhyay 2010, Indian J Dermatol — dandruff: the most commercially exploited skin disease (piroctone olamine, climbazole, ZPT)', url: 'https://doi.org/10.4103/0019-5154.60343' },
  teaTreeDandruff: { label: 'Satchell et al. 2002, J Am Acad Dermatol — 5% tea tree oil shampoo for dandruff, RCT', url: 'https://doi.org/10.1067/mjd.2002.122734' },
  minoxidil: { label: 'Suchonwanit et al. 2019, Drug Des Devel Ther — minoxidil and its use in hair disorders (review)', url: 'https://doi.org/10.2147/DDDT.S214907' },
  rosemary: { label: 'Panahi et al. 2015, Skinmed — rosemary oil vs minoxidil 2% for androgenetic alopecia, randomised trial', url: 'https://pubmed.ncbi.nlm.nih.gov/25842469/' },
  caffeineHair: { label: 'Fischer et al. 2007, Int J Dermatol — caffeine and testosterone on human hair follicles in vitro', url: 'https://doi.org/10.1111/j.1365-4632.2007.03119.x' },
  onion: { label: 'Sharquie & Al-Obaidi 2002, J Dermatol — onion juice for alopecia areata (small trial; not androgenetic hair fall)', url: 'https://pubmed.ncbi.nlm.nih.gov/12126069/' },
  bhringraj: { label: 'Roy et al. 2008, Arch Dermatol Res — hair growth promoting activity of Eclipta alba in albino rats (animal study)', url: 'https://doi.org/10.1007/s00403-008-0860-3' },
  agaCosmeceuticals: { label: 'Nestor et al. 2021, J Cosmet Dermatol — treatment options for androgenetic alopecia; cosmeceutical peptides / botanicals rest on manufacturer studies', url: 'https://doi.org/10.1111/jocd.14537' },
  sawPalmetto: { label: 'Evron et al. 2020, Skin Appendage Disord — saw palmetto for hair loss: systematic review', url: 'https://doi.org/10.1159/000509905' },
  hairCosmetics: { label: 'Gavazzoni Dias 2015, Int J Trichology — hair cosmetics: an overview (cationic conditioners, silicones, hydrolysed proteins, oils)', url: 'https://doi.org/10.4103/0974-7753.153450' },
  thermalProtect: { label: 'Zhou et al. 2011, J Cosmet Sci — cosmetic pre-treatments (silicones, conditioning polymers, hydrolysed proteins) protecting hair from thermal damage by hot flat ironing', url: 'https://pubmed.ncbi.nlm.nih.gov/21635853/' },
  stylingPolymers: { label: 'Gavazzoni Dias 2015, Int J Trichology — hair cosmetics: fixatives / film-forming polymers (PVP, VP/VA, acrylates) in gels, waxes and sprays', url: 'https://doi.org/10.4103/0974-7753.153450' },
  hairOils: { label: 'Rele & Mohile 2003, J Cosmet Sci — mineral, sunflower and coconut oil on prevention of hair damage (coconut oil penetrates the shaft, reduces protein loss)', url: 'https://pubmed.ncbi.nlm.nih.gov/12715094/' },
  hairCleansing: { label: 'Draelos 2010, Int J Trichology — essentials of hair care often neglected: hair cleansing (dry shampoo powders absorb sebum; no cleaning action)', url: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3002407/' },
  fdaFormaldehyde: { label: 'US FDA — hair-smoothing products that release formaldehyde when heated (proposed ban on formaldehyde / methylene glycol in hair smoothing products)', url: 'https://www.fda.gov/cosmetics/cosmetic-products/hair-smoothing-products-release-formaldehyde-when-heated' },
  // Spot treatment, body & personal care
  hydrocolloid: { label: 'Chao et al. 2006, J Cosmet Sci — hydrocolloid acne dressing, randomised double-blind pilot trial', url: 'https://pubmed.ncbi.nlm.nih.gov/16688373/' },
  fdaAntiperspirant: { label: 'US FDA 21 CFR Part 350 — antiperspirant drug products for OTC human use (aluminium chlorohydrate / zirconium salts monograph)', url: 'https://www.ecfr.gov/current/title-21/chapter-I/subchapter-D/part-350' },
  deodorants: { label: 'Teerasumran et al. 2023, Int J Cosmet Sci — deodorants and antiperspirants: active agents and testing methods (review)', url: 'https://doi.org/10.1111/ics.12852' },
  intimate: { label: 'Chen et al. 2017, Womens Health (Lond) — role of female intimate hygiene in vulvovaginal health (pH-matched, mild cleansers; lactic acid)', url: 'https://doi.org/10.1177/1745505717731011' },
  striae: { label: 'Ud-Din, McGeorge & Bayat 2016, J Eur Acad Dermatol Venereol — topical management of striae distensae (tretinoin, centella; cocoa butter / oils not shown to prevent)', url: 'https://doi.org/10.1111/jdv.13223' },
  depilatory: { label: 'EU Cosmetics Regulation 1223/2009 Annex III — thioglycolic acid and its salts permitted in depilatories at ≤5%', url: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02009R1223-20240424' },
  colophony: { label: 'Downs & Sansom 1999, Contact Dermatitis — colophony (rosin) allergy: a review', url: 'https://doi.org/10.1111/j.1600-0536.1999.tb06178.x' },
};

// Evidence grade: A = multiple RCTs / regulatory monograph, B = clinical studies, C = in-vitro / traditional use.
// roles: which product categories treat this as a CORE active (scored higher) vs a supporting ingredient.
const ACTIVES = [
  ['niacinamide', 'A', 'niacinamide', ['niacinamide', 'facewash', 'toner', 'essence', 'moisturizer', 'sunscreen', 'detan', 'pigmentation', 'eyecream', 'facemask', 'bodylotion']],
  ['retinol', 'A', 'retinoids', ['retinol', 'eyecream', 'moisturizer']],
  ['retinal', 'A', 'retinoids', ['retinol', 'eyecream']],
  ['retinaldehyde', 'A', 'retinoids', ['retinol', 'eyecream']],
  ['hydroxypinacolone retinoate', 'B', 'retinoids', ['retinol', 'eyecream']],
  ['retinyl palmitate', 'C', 'retinoids', ['retinol', 'eyecream']],
  ['retinyl acetate', 'C', 'retinoids', ['retinol', 'eyecream']],
  ['retinyl propionate', 'B', 'retinoids', ['retinol']],
  ['adapalene', 'A', 'retinoids', ['retinol', 'salicylic']],
  ['tretinoin', 'A', 'retinoids', ['retinol', 'pigmentation']],
  ['bakuchiol', 'B', 'bakuchiol', ['retinol', 'eyecream']],
  ['ascorbic acid', 'A', 'vitc', ['vitaminc', 'detan', 'pigmentation', 'eyecream', 'toner', 'essence', 'facemask']],
  ['3-o-ethyl ascorbic acid', 'B', 'vitc', ['vitaminc', 'detan', 'pigmentation', 'toner', 'essence']],
  ['ethyl ascorbic acid', 'B', 'vitc', ['vitaminc', 'detan', 'pigmentation']],
  ['ascorbyl glucoside', 'B', 'vitc', ['vitaminc', 'detan', 'pigmentation', 'toner', 'essence']],
  ['sodium ascorbyl phosphate', 'B', 'vitc', ['vitaminc', 'detan', 'pigmentation', 'facewash']],
  ['magnesium ascorbyl phosphate', 'B', 'vitc', ['vitaminc', 'detan', 'pigmentation']],
  ['tetrahexyldecyl ascorbate', 'B', 'vitc', ['vitaminc', 'detan', 'pigmentation', 'faceoil']],
  ['ascorbyl tetraisopalmitate', 'B', 'vitc', ['vitaminc', 'faceoil']],
  ['ascorbyl palmitate', 'C', 'vitc', ['vitaminc']],
  ['ferulic acid', 'B', 'vitc', ['vitaminc']],
  ['tocopherol', 'B', 'vitc', ['vitaminc', 'faceoil', 'moisturizer', 'bodylotion', 'eyecream']],
  ['tocopheryl acetate', 'B', 'vitc', ['vitaminc', 'faceoil', 'moisturizer', 'bodylotion', 'eyecream']],
  ['glycolic acid', 'A', 'aha', ['exfoliator', 'toner', 'detan', 'pigmentation', 'kp', 'facewash', 'bodywash', 'bodylotion']],
  ['lactic acid', 'A', 'aha', ['exfoliator', 'toner', 'detan', 'pigmentation', 'kp', 'bodylotion', 'facewash', 'bodywash']],
  ['mandelic acid', 'B', 'aha', ['exfoliator', 'toner', 'detan', 'pigmentation', 'salicylic']],
  ['gluconolactone', 'B', 'aha', ['exfoliator', 'toner']],
  ['lactobionic acid', 'B', 'aha', ['exfoliator', 'toner']],
  ['citric acid', 'C', 'aha', []],
  ['salicylic acid', 'A', 'bha', ['salicylic', 'exfoliator', 'facewash', 'toner', 'kp', 'bodywash']],
  ['betaine salicylate', 'B', 'bha', ['salicylic', 'exfoliator', 'toner']],
  ['azelaic acid', 'A', 'azelaic', ['pigmentation', 'detan', 'salicylic', 'niacinamide']],
  ['kojic acid', 'B', 'pigment', ['detan', 'pigmentation', 'facewash', 'facemask']],
  ['kojic dipalmitate', 'B', 'pigment', ['detan', 'pigmentation']],
  ['alpha-arbutin', 'B', 'pigment', ['detan', 'pigmentation', 'vitaminc', 'niacinamide', 'essence', 'toner']],
  ['arbutin', 'B', 'pigment', ['detan', 'pigmentation', 'vitaminc', 'niacinamide']],
  ['tranexamic acid', 'B', 'tranexamic', ['detan', 'pigmentation', 'vitaminc', 'niacinamide', 'eyecream']],
  ['glycyrrhiza glabra root extract', 'B', 'pigment', ['detan', 'pigmentation', 'vitaminc']],
  ['dipotassium glycyrrhizate', 'B', 'pigment', ['detan', 'pigmentation']],
  ['glabridin', 'B', 'pigment', ['detan', 'pigmentation']],
  ['hexylresorcinol', 'B', 'pigment', ['detan', 'pigmentation']],
  ['4-butylresorcinol', 'B', 'pigment', ['detan', 'pigmentation']],
  ['isobutylamido thiazolyl resorcinol', 'B', 'pigment', ['detan', 'pigmentation']],
  ['hydroquinone', 'A', 'pigment', ['pigmentation']],
  ['cysteamine', 'B', 'pigment', ['pigmentation']],
  ['glutathione', 'C', 'pigment', ['detan', 'pigmentation']],
  ['hyaluronic acid', 'B', 'ha', ['essence', 'toner', 'moisturizer', 'eyecream', 'facemask', 'vitaminc', 'niacinamide']],
  ['sodium hyaluronate', 'B', 'ha', ['essence', 'toner', 'moisturizer', 'eyecream', 'facemask', 'vitaminc', 'niacinamide']],
  ['hydrolyzed hyaluronic acid', 'B', 'ha', ['essence', 'toner', 'moisturizer', 'eyecream']],
  ['sodium acetylated hyaluronate', 'B', 'ha', ['essence', 'toner', 'moisturizer']],
  ['glycerin', 'A', 'glycerin', ['moisturizer', 'bodylotion', 'toner', 'essence', 'facewash', 'bodywash', 'facemask', 'eyecream', 'kp']],
  ['urea', 'A', 'urea', ['kp', 'bodylotion', 'moisturizer']],
  ['ammonium lactate', 'A', 'kp', ['kp', 'bodylotion']],
  ['ceramide np', 'B', 'ceramide', ['moisturizer', 'bodylotion', 'eyecream', 'kp', 'essence', 'toner', 'facewash']],
  ['ceramide ap', 'B', 'ceramide', ['moisturizer', 'bodylotion', 'eyecream', 'kp']],
  ['ceramide eop', 'B', 'ceramide', ['moisturizer', 'bodylotion', 'eyecream', 'kp']],
  ['ceramide ns', 'B', 'ceramide', ['moisturizer', 'bodylotion']],
  ['ceramide eos', 'B', 'ceramide', ['moisturizer', 'bodylotion', 'eyecream', 'kp']],
  ['cholesterol', 'B', 'ceramide', ['moisturizer', 'bodylotion', 'kp']],
  ['panthenol', 'B', 'panthenol', ['moisturizer', 'bodylotion', 'toner', 'essence', 'facewash', 'eyecream', 'facemask', 'sunscreen']],
  ['allantoin', 'C', 'panthenol', ['moisturizer', 'bodylotion', 'toner']],
  ['bisabolol', 'B', 'centella', ['moisturizer', 'toner', 'essence', 'sunscreen']],
  ['centella asiatica extract', 'B', 'centella', ['moisturizer', 'toner', 'essence', 'facewash', 'sunscreen', 'facemask']],
  ['madecassoside', 'B', 'centella', ['moisturizer', 'toner', 'essence']],
  ['asiaticoside', 'B', 'centella', ['moisturizer', 'toner', 'essence']],
  ['avena sativa kernel flour', 'B', 'oat', ['bodylotion', 'moisturizer', 'bodywash', 'facewash', 'kp']],
  ['avena sativa kernel extract', 'B', 'oat', ['bodylotion', 'moisturizer', 'bodywash']],
  ['colloidal oatmeal', 'B', 'oat', ['bodylotion', 'moisturizer', 'bodywash']],
  ['petrolatum', 'A', 'petrolatum', ['bodylotion', 'moisturizer', 'kp']],
  ['dimethicone', 'B', 'petrolatum', ['bodylotion', 'moisturizer', 'kp']],
  ['shea butter', 'B', 'petrolatum', ['bodylotion', 'moisturizer', 'kp']],
  ['butyrospermum parkii butter', 'B', 'petrolatum', ['bodylotion', 'moisturizer', 'kp']],
  ['squalane', 'B', 'squalane', ['faceoil', 'moisturizer', 'eyecream', 'bodylotion']],
  ['zinc oxide', 'A', 'sunFilters', ['sunscreen']],
  ['titanium dioxide', 'A', 'sunFilters', ['sunscreen']],
  ['butyl methoxydibenzoylmethane', 'A', 'sunFilters', ['sunscreen']],
  ['avobenzone', 'A', 'sunFilters', ['sunscreen']],
  ['octocrylene', 'A', 'sunFilters', ['sunscreen']],
  ['homosalate', 'A', 'sunFilters', ['sunscreen']],
  ['ethylhexyl methoxycinnamate', 'A', 'sunFilters', ['sunscreen']],
  ['octinoxate', 'A', 'sunFilters', ['sunscreen']],
  ['ethylhexyl salicylate', 'A', 'sunFilters', ['sunscreen']],
  ['octisalate', 'A', 'sunFilters', ['sunscreen']],
  ['phenylbenzimidazole sulfonic acid', 'A', 'sunFilters', ['sunscreen']],
  ['benzophenone-3', 'A', 'sunFilters', ['sunscreen']],
  ['benzophenone-4', 'A', 'sunFilters', ['sunscreen']],
  ['bis-ethylhexyloxyphenol methoxyphenyl triazine', 'A', 'sunFilters', ['sunscreen']],
  ['methylene bis-benzotriazolyl tetramethylbutylphenol', 'A', 'sunFilters', ['sunscreen']],
  ['diethylamino hydroxybenzoyl hexyl benzoate', 'A', 'sunFilters', ['sunscreen']],
  ['terephthalylidene dicamphor sulfonic acid', 'A', 'sunFilters', ['sunscreen']],
  ['drometrizole trisiloxane', 'A', 'sunFilters', ['sunscreen']],
  ['methoxypropylamino cyclohexenylidene ethoxyethylcyanoacetate', 'A', 'sunFilters', ['sunscreen']],
  ['diethylhexyl butamido triazone', 'A', 'sunFilters', ['sunscreen']],
  ['ethylhexyl triazone', 'A', 'sunFilters', ['sunscreen']],
  ['tris-biphenyl triazine', 'A', 'sunFilters', ['sunscreen']],
  ['polysilicone-15', 'A', 'sunFilters', ['sunscreen']],
  ['isoamyl p-methoxycinnamate', 'A', 'sunFilters', ['sunscreen']],
  ['palmitoyl tripeptide-1', 'B', 'peptides', ['eyecream', 'moisturizer', 'retinol', 'essence']],
  ['palmitoyl tetrapeptide-7', 'B', 'peptides', ['eyecream', 'moisturizer', 'retinol', 'essence']],
  ['palmitoyl pentapeptide-4', 'B', 'peptides', ['eyecream', 'moisturizer']],
  ['acetyl hexapeptide-8', 'B', 'peptides', ['eyecream', 'moisturizer']],
  ['copper tripeptide-1', 'B', 'peptides', ['eyecream', 'moisturizer']],
  ['caffeine', 'B', 'caffeine', ['eyecream', 'facemask']],
  ['adenosine', 'B', 'peptides', ['eyecream', 'moisturizer', 'essence']],
  ['camellia sinensis leaf extract', 'B', 'greenTea', ['toner', 'essence', 'facewash', 'sunscreen', 'facemask', 'moisturizer']],
  ['epigallocatechin gallate', 'B', 'greenTea', ['toner', 'essence', 'sunscreen']],
  ['melaleuca alternifolia leaf oil', 'B', 'teaTree', ['facewash', 'salicylic', 'toner']],
  ['sulfur', 'B', 'bha', ['salicylic', 'facemask']],
  ['benzoyl peroxide', 'A', 'bha', ['salicylic', 'facewash']],
  ['zinc pca', 'B', 'niacinamide', ['toner', 'salicylic', 'niacinamide', 'facewash']],
  ['aloe barbadensis leaf juice', 'B', 'centella', ['toner', 'essence', 'facemask', 'moisturizer', 'bodylotion', 'sunscreen']],
  ['aloe barbadensis leaf extract', 'B', 'centella', ['toner', 'essence', 'facemask', 'moisturizer', 'bodylotion', 'sunscreen']],
  ['snail secretion filtrate', 'C', 'ha', ['essence', 'toner', 'moisturizer']],
  ['galactomyces ferment filtrate', 'C', 'ha', ['essence', 'toner']],
  ['saccharomyces ferment filtrate', 'C', 'ha', ['essence', 'toner']],
  ['oryza sativa extract', 'C', 'ha', ['essence', 'toner', 'facewash']],
  ['kaolin', 'C', 'bha', ['facemask', 'exfoliator']],
  ['bentonite', 'C', 'bha', ['facemask', 'exfoliator']],
  ['charcoal powder', 'C', 'bha', ['facemask', 'facewash']],
  ['curcuma longa root extract', 'C', 'greenTea', ['detan', 'facemask', 'facewash']],
  ['resveratrol', 'B', 'greenTea', ['vitaminc', 'moisturizer', 'eyecream']],
  ['ubiquinone', 'B', 'greenTea', ['moisturizer', 'eyecream']],
  ['beta-glucan', 'B', 'centella', ['essence', 'toner', 'moisturizer']],
  ['rosa canina fruit oil', 'B', 'squalane', ['faceoil']],
  ['simmondsia chinensis seed oil', 'B', 'squalane', ['faceoil', 'bodylotion']],
  ['argania spinosa kernel oil', 'B', 'squalane', ['faceoil', 'bodylotion']],
  ['prunus amygdalus dulcis oil', 'B', 'squalane', ['faceoil', 'bodylotion']],
  ['helianthus annuus seed oil', 'B', 'squalane', ['faceoil', 'bodylotion', 'moisturizer']],
  ['cocos nucifera oil', 'C', 'squalane', ['bodylotion']],
  ['crocus sativus flower extract', 'C', 'pigment', ['faceoil', 'detan']],
  // Spot treatment & patches
  ['hydrocolloid', 'B', 'hydrocolloid', ['acnespot']],
  ['clindamycin', 'A', 'bha', ['acnespot']],
  ['clindamycin phosphate', 'A', 'bha', ['acnespot']],
  // Body & personal care (occlusives / humectants already listed above carry the new roles via ROLE_EXTRA below)
  ['lanolin', 'B', 'petrolatum', ['handfoot', 'bodylotion', 'stretchmark']],
  ['paraffinum liquidum', 'B', 'petrolatum', ['bodyoil', 'handfoot', 'stretchmark']],
  ['mineral oil', 'B', 'petrolatum', ['bodyoil', 'handfoot', 'stretchmark']],
  ['theobroma cacao seed butter', 'C', 'striae', ['bodyoil', 'stretchmark', 'handfoot', 'bodylotion']],
  ['cocoa butter', 'C', 'striae', ['bodyoil', 'stretchmark', 'handfoot', 'bodylotion']],
  ['aluminum chlorohydrate', 'A', 'fdaAntiperspirant', ['deodorant']],
  ['aluminium chlorohydrate', 'A', 'fdaAntiperspirant', ['deodorant']],
  ['aluminum zirconium tetrachlorohydrex gly', 'A', 'fdaAntiperspirant', ['deodorant']],
  ['aluminum zirconium trichlorohydrex gly', 'A', 'fdaAntiperspirant', ['deodorant']],
  ['aluminum zirconium pentachlorohydrex gly', 'A', 'fdaAntiperspirant', ['deodorant']],
  ['aluminum zirconium octachlorohydrex gly', 'A', 'fdaAntiperspirant', ['deodorant']],
  ['aluminum sesquichlorohydrate', 'A', 'fdaAntiperspirant', ['deodorant']],
  ['aluminum chloride', 'A', 'fdaAntiperspirant', ['deodorant']],
  ['potassium alum', 'C', 'deodorants', ['deodorant']],
  ['ammonium alum', 'C', 'deodorants', ['deodorant']],
  ['sodium bicarbonate', 'C', 'deodorants', ['deodorant']],
  ['magnesium hydroxide', 'C', 'deodorants', ['deodorant']],
  ['zinc ricinoleate', 'C', 'deodorants', ['deodorant']],
  ['triethyl citrate', 'C', 'deodorants', ['deodorant']],
  ['potassium thioglycolate', 'A', 'depilatory', ['hairremoval']],
  ['calcium thioglycolate', 'A', 'depilatory', ['hairremoval']],
  ['thioglycolic acid', 'A', 'depilatory', ['hairremoval']],
  // Physical exfoliant particles: cosmetic function only (grade C); on the face they are also a safety flag.
  ['sucrose', 'C', 'aadScrub', ['bodyscrub', 'scalpscrub']],
  ['sodium chloride', 'C', 'aadScrub', ['bodyscrub', 'scalpscrub']],
  ['maris sal', 'C', 'aadScrub', ['bodyscrub', 'scalpscrub']],
  ['sea salt', 'C', 'aadScrub', ['bodyscrub', 'scalpscrub']],
  ['coffea arabica seed powder', 'C', 'aadScrub', ['bodyscrub']],
  ['juglans regia shell powder', 'C', 'aadScrub', ['bodyscrub']],
  ['walnut shell powder', 'C', 'aadScrub', ['bodyscrub']],
  ['prunus armeniaca seed powder', 'C', 'aadScrub', ['bodyscrub']],
  ['pumice', 'C', 'aadScrub', ['bodyscrub', 'handfoot']],
];

// Extra category roles for actives already listed above — the new face / body pages reuse the same graded entries
// instead of duplicating them. Applied once when the tables are built (see ROLE_EXTRA use in inci-score.cjs).
const ROLE_EXTRA = {
  acnespot: ['benzoyl peroxide', 'salicylic acid', 'adapalene', 'azelaic acid', 'sulfur', 'niacinamide', 'zinc pca', 'melaleuca alternifolia leaf oil', 'tretinoin', 'retinol', 'centella asiatica extract'],
  facemist: ['glycerin', 'sodium hyaluronate', 'hyaluronic acid', 'hydrolyzed hyaluronic acid', 'panthenol', 'allantoin', 'aloe barbadensis leaf juice', 'aloe barbadensis leaf extract', 'centella asiatica extract', 'bisabolol', 'niacinamide', 'camellia sinensis leaf extract', 'beta-glucan'],
  barriercream: ['ceramide np', 'ceramide ap', 'ceramide eop', 'ceramide ns', 'ceramide eos', 'cholesterol', 'petrolatum', 'dimethicone', 'shea butter', 'butyrospermum parkii butter', 'niacinamide', 'panthenol', 'glycerin', 'squalane', 'centella asiatica extract', 'madecassoside', 'asiaticoside', 'colloidal oatmeal', 'avena sativa kernel flour', 'avena sativa kernel extract', 'allantoin', 'bisabolol', 'sodium hyaluronate', 'hyaluronic acid', 'urea'],
  peptideserum: ['palmitoyl tripeptide-1', 'palmitoyl tetrapeptide-7', 'palmitoyl pentapeptide-4', 'acetyl hexapeptide-8', 'copper tripeptide-1', 'adenosine', 'niacinamide', 'sodium hyaluronate', 'hyaluronic acid', 'hydrolyzed hyaluronic acid', 'retinol', 'bakuchiol', 'ascorbic acid', 'tocopherol', 'resveratrol', 'ubiquinone'],
  azelaic: ['azelaic acid', 'niacinamide', 'salicylic acid', 'tranexamic acid', 'alpha-arbutin', 'arbutin', 'glycolic acid', 'lactic acid', 'mandelic acid', 'zinc pca'],
  sheetmask: ['sodium hyaluronate', 'hyaluronic acid', 'hydrolyzed hyaluronic acid', 'glycerin', 'niacinamide', 'centella asiatica extract', 'madecassoside', 'snail secretion filtrate', 'camellia sinensis leaf extract', 'aloe barbadensis leaf juice', 'aloe barbadensis leaf extract', 'panthenol', 'allantoin', 'ceramide np', 'ascorbic acid', 'ascorbyl glucoside', '3-o-ethyl ascorbic acid', 'beta-glucan', 'galactomyces ferment filtrate', 'oryza sativa extract', 'adenosine', 'bisabolol'],
  bodyscrub: ['glycolic acid', 'lactic acid', 'salicylic acid', 'urea', 'mandelic acid', 'glycerin', 'kaolin', 'charcoal powder', 'curcuma longa root extract', 'shea butter', 'butyrospermum parkii butter', 'cocos nucifera oil', 'prunus amygdalus dulcis oil'],
  bodyoil: ['squalane', 'rosa canina fruit oil', 'simmondsia chinensis seed oil', 'argania spinosa kernel oil', 'prunus amygdalus dulcis oil', 'helianthus annuus seed oil', 'cocos nucifera oil', 'tocopherol', 'tocopheryl acetate', 'shea butter', 'butyrospermum parkii butter', 'ascorbyl tetraisopalmitate', 'tetrahexyldecyl ascorbate', 'crocus sativus flower extract'],
  handfoot: ['urea', 'glycerin', 'petrolatum', 'dimethicone', 'shea butter', 'butyrospermum parkii butter', 'lactic acid', 'salicylic acid', 'glycolic acid', 'allantoin', 'panthenol', 'ceramide np', 'ceramide ap', 'ceramide eop', 'cholesterol', 'squalane', 'colloidal oatmeal', 'avena sativa kernel flour', 'ammonium lactate', 'tocopherol', 'tocopheryl acetate', 'sodium hyaluronate'],
  deodorant: ['glycerin', 'aloe barbadensis leaf juice', 'aloe barbadensis leaf extract'],
  intimatewash: ['lactic acid', 'glycerin', 'melaleuca alternifolia leaf oil', 'aloe barbadensis leaf juice', 'aloe barbadensis leaf extract', 'panthenol', 'centella asiatica extract', 'bisabolol'],
  stretchmark: ['tretinoin', 'centella asiatica extract', 'madecassoside', 'asiaticoside', 'sodium hyaluronate', 'hyaluronic acid', 'glycerin', 'retinol', 'retinyl palmitate', 'tocopherol', 'tocopheryl acetate', 'shea butter', 'butyrospermum parkii butter', 'squalane', 'rosa canina fruit oil', 'petrolatum', 'dimethicone', 'panthenol', 'allantoin', 'urea', 'niacinamide', 'palmitoyl tripeptide-1', 'palmitoyl tetrapeptide-7'],
  hairremoval: ['glycerin', 'aloe barbadensis leaf juice', 'aloe barbadensis leaf extract', 'allantoin', 'panthenol', 'bisabolol', 'urea', 'petrolatum'],
};
for (const [role, names] of Object.entries(ROLE_EXTRA)) {
  for (const a of ACTIVES) if (names.includes(a[0]) && !a[3].includes(role)) a[3].push(role);
}

// Hair-care actives, kept separate so skincare grades never change. Same evidence grades: A = RCTs / OTC monograph,
// B = clinical studies, C = in-vitro, animal or manufacturer data. Trade-name blends (Redensyl, Procapil, Anagain,
// Capixyl) are listed by their INCI components and graded C — their evidence is manufacturer-run studies.
const HAIR_ACTIVES = [
  ['ketoconazole', 'A', 'dandruff', ['antidandruff']],
  ['zinc pyrithione', 'A', 'dandruff', ['antidandruff', 'shampoo']],
  ['pyrithione zinc', 'A', 'dandruff', ['antidandruff', 'shampoo']],
  ['selenium sulfide', 'A', 'dandruff', ['antidandruff']],
  ['selenium sulphide', 'A', 'dandruff', ['antidandruff']],
  ['ciclopirox olamine', 'A', 'dandruff', ['antidandruff']],
  ['ciclopirox', 'A', 'dandruff', ['antidandruff']],
  ['piroctone olamine', 'B', 'dandruffIndia', ['antidandruff', 'shampoo']],
  ['climbazole', 'B', 'dandruffIndia', ['antidandruff', 'shampoo']],
  ['coal tar', 'B', 'dandruff', ['antidandruff']],
  ['salicylic acid', 'B', 'dandruff', ['antidandruff', 'shampoo']],
  ['melaleuca alternifolia leaf oil', 'B', 'teaTreeDandruff', ['antidandruff', 'shampoo']],
  ['minoxidil', 'A', 'minoxidil', ['hairfall']],
  ['rosmarinus officinalis leaf oil', 'B', 'rosemary', ['hairfall', 'hairoil']],
  ['rosmarinus officinalis leaf extract', 'C', 'rosemary', ['hairfall', 'hairoil', 'shampoo']],
  ['caffeine', 'C', 'caffeineHair', ['hairfall', 'shampoo']],
  ['allium cepa bulb extract', 'C', 'onion', ['hairfall', 'hairoil', 'shampoo']],
  ['allium cepa bulb oil', 'C', 'onion', ['hairfall', 'hairoil']],
  ['eclipta prostrata extract', 'C', 'bhringraj', ['hairoil', 'hairfall']],
  ['eclipta alba extract', 'C', 'bhringraj', ['hairoil', 'hairfall']],
  ['eclipta prostrata leaf extract', 'C', 'bhringraj', ['hairoil', 'hairfall']],
  ['biotinoyl tripeptide-1', 'C', 'agaCosmeceuticals', ['hairfall']],
  ['larix europaea wood extract', 'C', 'agaCosmeceuticals', ['hairfall']],
  ['pisum sativum sprout extract', 'C', 'agaCosmeceuticals', ['hairfall']],
  ['acetyl tetrapeptide-3', 'C', 'agaCosmeceuticals', ['hairfall']],
  ['trifolium pratense flower extract', 'C', 'agaCosmeceuticals', ['hairfall']],
  ['serenoa serrulata fruit extract', 'C', 'sawPalmetto', ['hairfall']],
  ['serenoa repens fruit extract', 'C', 'sawPalmetto', ['hairfall']],
  ['cocos nucifera oil', 'B', 'hairOils', ['hairoil', 'hairmask', 'conditioner', 'haircream']],
  ['helianthus annuus seed oil', 'C', 'hairOils', ['hairoil']],
  ['paraffinum liquidum', 'C', 'hairOils', ['hairoil']],
  ['mineral oil', 'C', 'hairOils', ['hairoil']],
  ['argania spinosa kernel oil', 'C', 'hairCosmetics', ['hairoil', 'hairserum', 'hairmask', 'conditioner', 'haircream']],
  ['prunus amygdalus dulcis oil', 'C', 'hairCosmetics', ['hairoil']],
  ['ricinus communis seed oil', 'C', 'hairCosmetics', ['hairoil']],
  ['sesamum indicum seed oil', 'C', 'hairCosmetics', ['hairoil']],
  ['simmondsia chinensis seed oil', 'C', 'hairCosmetics', ['hairoil', 'hairserum']],
  ['behentrimonium chloride', 'B', 'hairCosmetics', ['conditioner', 'hairmask', 'haircream']],
  ['behentrimonium methosulfate', 'B', 'hairCosmetics', ['conditioner', 'hairmask', 'haircream']],
  ['cetrimonium chloride', 'B', 'hairCosmetics', ['conditioner', 'hairmask', 'haircream', 'heatprotect']],
  ['stearamidopropyl dimethylamine', 'B', 'hairCosmetics', ['conditioner', 'hairmask', 'haircream']],
  ['polyquaternium-10', 'B', 'hairCosmetics', ['shampoo', 'conditioner', 'haircream', 'heatprotect']],
  ['polyquaternium-7', 'B', 'hairCosmetics', ['shampoo', 'conditioner', 'haircream']],
  ['guar hydroxypropyltrimonium chloride', 'B', 'hairCosmetics', ['shampoo', 'conditioner']],
  ['dimethicone', 'B', 'thermalProtect', ['conditioner', 'hairserum', 'hairmask', 'haircream', 'heatprotect']],
  ['amodimethicone', 'B', 'thermalProtect', ['conditioner', 'hairserum', 'hairmask', 'haircream', 'heatprotect']],
  ['cyclopentasiloxane', 'B', 'thermalProtect', ['hairserum', 'heatprotect']],
  ['dimethiconol', 'B', 'thermalProtect', ['hairserum', 'conditioner', 'heatprotect', 'haircream']],
  ['hydrolyzed keratin', 'C', 'thermalProtect', ['conditioner', 'hairmask', 'hairserum', 'shampoo', 'heatprotect', 'haircream']],
  ['hydrolyzed wheat protein', 'C', 'thermalProtect', ['conditioner', 'hairmask', 'hairserum', 'shampoo', 'heatprotect', 'haircream']],
  ['hydrolyzed silk', 'C', 'hairCosmetics', ['conditioner', 'hairmask', 'hairserum']],
  ['hydrolyzed rice protein', 'C', 'hairCosmetics', ['conditioner', 'hairmask', 'shampoo']],
  ['hydrolyzed soy protein', 'C', 'hairCosmetics', ['conditioner', 'hairmask', 'shampoo']],
  ['hydrolyzed vegetable protein', 'C', 'hairCosmetics', ['conditioner', 'hairmask', 'shampoo']],
  ['panthenol', 'C', 'hairCosmetics', ['conditioner', 'hairmask', 'hairserum', 'shampoo', 'haircream', 'heatprotect']],
  ['glycerin', 'A', 'glycerin', ['conditioner', 'hairmask', 'shampoo', 'haircream']],
  ['butyrospermum parkii butter', 'C', 'hairCosmetics', ['hairmask', 'conditioner', 'haircream']],
  ['shea butter', 'C', 'hairCosmetics', ['hairmask', 'conditioner', 'haircream']],
  // Styling fixatives: film-forming polymers that give hold; cosmetic-function evidence only (grade C), never a health claim.
  ['pvp', 'C', 'stylingPolymers', ['hairstyling']],
  ['vp/va copolymer', 'C', 'stylingPolymers', ['hairstyling']],
  ['pvp/va copolymer', 'C', 'stylingPolymers', ['hairstyling']],
  ['acrylates copolymer', 'C', 'stylingPolymers', ['hairstyling']],
  ['acrylates/c10-30 alkyl acrylate crosspolymer', 'C', 'stylingPolymers', ['hairstyling']],
  ['polyquaternium-11', 'C', 'stylingPolymers', ['hairstyling', 'heatprotect']],
  ['polyquaternium-55', 'C', 'stylingPolymers', ['hairstyling', 'heatprotect']],
  ['vp/methacrylamide/vinyl imidazole copolymer', 'C', 'stylingPolymers', ['hairstyling']],
  ['cera alba', 'C', 'hairCosmetics', ['hairstyling', 'beard']],
  ['beeswax', 'C', 'hairCosmetics', ['hairstyling', 'beard']],
  // Dry shampoo: sebum-absorbing powders — cosmetic function only (grade C).
  ['oryza sativa starch', 'C', 'hairCleansing', ['dryshampoo']],
  ['rice starch', 'C', 'hairCleansing', ['dryshampoo']],
  ['zea mays starch', 'C', 'hairCleansing', ['dryshampoo']],
  ['corn starch', 'C', 'hairCleansing', ['dryshampoo']],
  ['tapioca starch', 'C', 'hairCleansing', ['dryshampoo']],
  ['manihot esculenta root starch', 'C', 'hairCleansing', ['dryshampoo']],
  ['aluminum starch octenylsuccinate', 'C', 'hairCleansing', ['dryshampoo']],
  ['maranta arundinacea root powder', 'C', 'hairCleansing', ['dryshampoo']],
  ['silica', 'C', 'hairCleansing', ['dryshampoo']],
  ['kaolin', 'C', 'hairCleansing', ['dryshampoo', 'scalpscrub']],
  // Scalp scrub: exfoliant particles / keratolytics (salicylic acid is graded above under dandruff).
  ['charcoal powder', 'C', 'hairCleansing', ['scalpscrub']],
  ['glycolic acid', 'C', 'hairCleansing', ['scalpscrub']],
  ['sucrose', 'C', 'hairCleansing', ['scalpscrub']],
  ['sodium chloride', 'C', 'hairCleansing', ['scalpscrub']],
  ['maris sal', 'C', 'hairCleansing', ['scalpscrub']],
  ['sea salt', 'C', 'hairCleansing', ['scalpscrub']],
];
// Hair roles reused by the new hair pages (same graded entries, no duplication).
const HAIR_ROLE_EXTRA = {
  scalpscrub: ['salicylic acid', 'melaleuca alternifolia leaf oil', 'piroctone olamine', 'zinc pyrithione', 'pyrithione zinc', 'rosmarinus officinalis leaf oil', 'glycerin', 'panthenol'],
  keratinkit: ['hydrolyzed keratin', 'hydrolyzed wheat protein', 'hydrolyzed silk', 'amodimethicone', 'dimethicone', 'cyclopentasiloxane', 'dimethiconol', 'cetrimonium chloride', 'behentrimonium chloride', 'behentrimonium methosulfate', 'panthenol', 'argania spinosa kernel oil', 'cocos nucifera oil', 'butyrospermum parkii butter', 'shea butter'],
  beard: ['argania spinosa kernel oil', 'simmondsia chinensis seed oil', 'prunus amygdalus dulcis oil', 'ricinus communis seed oil', 'cocos nucifera oil', 'helianthus annuus seed oil', 'sesamum indicum seed oil', 'butyrospermum parkii butter', 'shea butter', 'glycerin', 'panthenol', 'polyquaternium-10', 'polyquaternium-7', 'guar hydroxypropyltrimonium chloride'],
};
for (const [role, names] of Object.entries(HAIR_ROLE_EXTRA)) {
  for (const a of HAIR_ACTIVES) if (names.includes(a[0]) && !a[3].includes(role)) a[3].push(role);
}

// Mild surfactants preferred by the cleansing literature (core actives for wash categories).
const MILD_SURFACTANTS = ['sodium cocoyl isethionate', 'cocamidopropyl betaine', 'coco-glucoside', 'decyl glucoside',
  'lauryl glucoside', 'sodium lauroyl sarcosinate', 'sodium cocoyl glycinate', 'sodium cocoyl glutamate',
  'disodium cocoamphodiacetate', 'sodium cocoamphoacetate', 'sodium methyl cocoyl taurate', 'lauryl hydroxysultaine',
  'cocamidopropyl hydroxysultaine', 'sodium lauroyl methyl isethionate', 'sodium laurylglucosides hydroxypropylsulfonate',
  'disodium laureth sulfosuccinate', 'sodium lauroamphoacetate', 'potassium cocoyl glycinate', 'sodium cocoyl alaninate',
  'sodium lauroyl lactylate', 'sodium c14-16 olefin sulfonate'];

// Preservatives are legally capped near 1%; on an EU/India-style descending INCI list, anything AFTER the first of these is ≤1%.
const ONE_PERCENT_MARKERS = ['phenoxyethanol', 'sodium benzoate', 'potassium sorbate', 'ethylhexylglycerin', 'chlorphenesin',
  'benzyl alcohol', 'methylparaben', 'propylparaben', 'ethylparaben', 'butylparaben', 'dmdm hydantoin', 'methylisothiazolinone',
  'methylchloroisothiazolinone', 'imidazolidinyl urea', 'diazolidinyl urea', 'sodium hydroxymethylglycinate', 'caprylhydroxamic acid',
  'sodium dehydroacetate', 'dehydroacetic acid', 'benzoic acid', 'sorbic acid', 'iodopropynyl butylcarbamate', 'triclosan',
  'disodium edta', 'tetrasodium edta', 'trisodium ethylenediamine disuccinate', 'parfum', 'fragrance'];

const WATER_FIRST = ['aqua', 'water', 'purified water', 'aqua (water)', 'water (aqua)', 'eau', 'aqua/water', 'water/aqua',
  'aqua/water/eau', 'deionized water', 'demineralized water', 'aqua purificata', 'rose water', 'rosa damascena flower water',
  'hamamelis virginiana water', 'alcohol denat', 'alcohol', 'glycerin', 'butylene glycol', 'cyclopentasiloxane', 'dimethicone',
  'squalane', 'caprylic/capric triglyceride', 'petrolatum', 'mineral oil', 'paraffinum liquidum', 'helianthus annuus seed oil',
  'simmondsia chinensis seed oil', 'prunus amygdalus dulcis oil', 'cocos nucifera oil', 'sesamum indicum seed oil',
  'rosa canina fruit oil', 'argania spinosa kernel oil', 'oryza sativa bran oil', 'zinc oxide', 'titanium dioxide', 'kaolin',
  'bentonite', 'sodium hyaluronate', 'niacinamide', 'ascorbic acid', 'urea', 'propanediol', 'isododecane', 'isopropyl myristate',
  'c12-15 alkyl benzoate', 'ethylhexyl methoxycinnamate', 'homosalate', 'octocrylene', 'talc', 'sodium bicarbonate',
  'lactic acid', 'glycolic acid', 'polysorbate 20', 'hydrogenated polyisobutene', 'isohexadecane', 'ethanol'];

module.exports = { SOURCES, ACTIVES, HAIR_ACTIVES, MILD_SURFACTANTS, ONE_PERCENT_MARKERS, WATER_FIRST };
