// Sourced ingredient-pairing / routine-use knowledge for the assistant. Every entry names the SOURCES key(s) it
// rests on and says whether the claim is a DIRECT study finding or an INFERENCE from the two ingredients' own
// evidence (e.g. two irritants stacking). Nothing here is a seller claim, and nothing here is about a specific product.
// CommonJS like inci-kb.cjs so build-data.mjs can require() it.

// Ingredient families: how people say it → canonical id. `inci` lists the INCI names in inci-kb ACTIVES that belong
// to the family so the assistant can tie general guidance back to ranked products.
const FAMILIES = [
  { id: 'retinoid', label: 'Retinoids (retinol, retinal, tretinoin, adapalene)', aliases: ['retinoid', 'retinoids', 'retinol', 'retinal', 'retinaldehyde', 'tretinoin', 'adapalene', 'retin-a', 'retinyl palmitate', 'hydroxypinacolone retinoate', 'granactive retinoid', 'vitamin a'],
    inci: ['retinol', 'retinal', 'retinaldehyde', 'hydroxypinacolone retinoate', 'retinyl palmitate', 'retinyl acetate', 'retinyl propionate', 'adapalene', 'tretinoin'] },
  { id: 'bha', label: 'BHA (salicylic acid)', aliases: ['bha', 'bhas', 'salicylic acid', 'salicylic', 'betaine salicylate', 'beta hydroxy acid'], inci: ['salicylic acid', 'betaine salicylate'] },
  { id: 'aha', label: 'AHAs (glycolic, lactic, mandelic acid)', aliases: ['aha', 'ahas', 'alpha hydroxy acid', 'glycolic acid', 'glycolic', 'lactic acid', 'lactic', 'mandelic acid', 'mandelic', 'pha', 'gluconolactone', 'lactobionic acid'],
    inci: ['glycolic acid', 'lactic acid', 'mandelic acid', 'gluconolactone', 'lactobionic acid'] },
  { id: 'bpo', label: 'Benzoyl peroxide', aliases: ['benzoyl peroxide', 'bpo', 'benzoyl'], inci: ['benzoyl peroxide'] },
  { id: 'vitc', label: 'Vitamin C (L-ascorbic acid and derivatives)', aliases: ['vitamin c', 'vit c', 'vitc', 'ascorbic acid', 'l-ascorbic acid', 'ascorbyl glucoside', 'ethyl ascorbic acid', '3-o-ethyl ascorbic acid', 'sodium ascorbyl phosphate', 'magnesium ascorbyl phosphate', 'tetrahexyldecyl ascorbate'],
    inci: ['ascorbic acid', '3-o-ethyl ascorbic acid', 'ethyl ascorbic acid', 'ascorbyl glucoside', 'sodium ascorbyl phosphate', 'magnesium ascorbyl phosphate', 'tetrahexyldecyl ascorbate', 'ascorbyl tetraisopalmitate', 'ascorbyl palmitate'] },
  { id: 'vite', label: 'Vitamin E (tocopherol)', aliases: ['vitamin e', 'vit e', 'tocopherol', 'tocopheryl acetate'], inci: ['tocopherol', 'tocopheryl acetate'] },
  { id: 'ferulic', label: 'Ferulic acid', aliases: ['ferulic acid', 'ferulic'], inci: ['ferulic acid'] },
  { id: 'niacinamide', label: 'Niacinamide (vitamin B3)', aliases: ['niacinamide', 'nicotinamide', 'vitamin b3', 'b3'], inci: ['niacinamide'] },
  { id: 'azelaic', label: 'Azelaic acid', aliases: ['azelaic acid', 'azelaic'], inci: ['azelaic acid'] },
  { id: 'hydroquinone', label: 'Hydroquinone', aliases: ['hydroquinone', 'hq'], inci: ['hydroquinone'] },
  { id: 'ha', label: 'Hyaluronic acid', aliases: ['hyaluronic acid', 'hyaluronic', 'sodium hyaluronate', 'ha'], inci: ['hyaluronic acid', 'sodium hyaluronate', 'hydrolyzed hyaluronic acid', 'sodium acetylated hyaluronate'] },
  { id: 'barrier', label: 'Barrier ingredients (ceramides, glycerin, panthenol, cholesterol)', aliases: ['ceramide', 'ceramides', 'glycerin', 'glycerol', 'panthenol', 'cholesterol', 'squalane', 'barrier', 'moisturiser', 'moisturizer'],
    inci: ['ceramide np', 'ceramide ap', 'ceramide eop', 'ceramide ns', 'ceramide eos', 'cholesterol', 'glycerin', 'panthenol', 'squalane'] },
  { id: 'sunscreen', label: 'Sunscreen (SPF)', aliases: ['sunscreen', 'spf', 'sunblock', 'sun protection', 'sun screen'], inci: [] },
  { id: 'bakuchiol', label: 'Bakuchiol', aliases: ['bakuchiol'], inci: ['bakuchiol'] },
  { id: 'tranexamic', label: 'Tranexamic acid', aliases: ['tranexamic acid', 'tranexamic', 'txa'], inci: ['tranexamic acid'] },
  { id: 'arbutin', label: 'Arbutin / kojic acid (tyrosinase inhibitors)', aliases: ['arbutin', 'alpha-arbutin', 'alpha arbutin', 'kojic acid', 'kojic', 'licorice', 'liquorice'], inci: ['alpha-arbutin', 'arbutin', 'kojic acid', 'kojic dipalmitate', 'glycyrrhiza glabra root extract'] },
  { id: 'minoxidil', label: 'Minoxidil', aliases: ['minoxidil', 'rogaine'], inci: ['minoxidil'] },
  { id: 'antidandruff', label: 'Anti-dandruff actives (ketoconazole, zinc pyrithione, piroctone olamine, selenium sulfide)', aliases: ['ketoconazole', 'nizoral', 'zinc pyrithione', 'zpt', 'piroctone olamine', 'selenium sulfide', 'ciclopirox', 'climbazole', 'anti-dandruff', 'antidandruff', 'dandruff'],
    inci: ['ketoconazole', 'zinc pyrithione', 'pyrithione zinc', 'piroctone olamine', 'selenium sulfide', 'ciclopirox olamine', 'climbazole'] },
  { id: 'heat', label: 'Heat styling (dryer, straightener, curler)', aliases: ['heat', 'heat protectant', 'heat protection', 'blow dry', 'blow-dry', 'hair dryer', 'straightener', 'flat iron', 'curling iron', 'thermal'], inci: [] },
  { id: 'hairoil', label: 'Hair oils (coconut, mineral, argan)', aliases: ['hair oil', 'coconut oil', 'oiling', 'champi', 'argan oil', 'castor oil', 'mineral oil'], inci: ['cocos nucifera oil', 'argania spinosa kernel oil', 'ricinus communis seed oil'] },
  { id: 'keratin', label: 'Keratin / smoothening treatments', aliases: ['keratin', 'keratin treatment', 'smoothening', 'smoothing', 'rebonding', 'brazilian blowout'], inci: ['hydrolyzed keratin'] },
  { id: 'dryshampoo', label: 'Dry shampoo', aliases: ['dry shampoo'], inci: [] },
];

// verdict: 'avoid' = not in the same application; 'caution' = works, but stagger / build up; 'fine' = no evidence of a
// problem; 'synergy' = evidence they are better together; 'essential' = the second is required with the first.
// evidence: 'direct' = a cited study looked at the combination; 'inference' = follows from each ingredient's own cited
// profile (no study on the pair itself); 'regulatory' = an authority's instruction.
const PAIRINGS = [
  { pair: ['retinoid', 'bha'], verdict: 'caution', evidence: 'inference', src: ['retinoids', 'bha', 'retinization'],
    headline: 'Both irritate on their own; layering them the same night stacks the irritation',
    detail: 'Retinoids cause dose-dependent redness, scaling and dryness while the skin adapts ("retinization"); salicylic acid is a keratolytic that also dries and stings. No study shows a chemical incompatibility — the problem is cumulative irritation and a compromised barrier.',
    how: 'Alternate nights (retinoid one night, BHA the next), or BHA in the morning and retinoid at night. Introduce one at a time; a bland moisturiser before/after the retinoid softens the adjustment. Sensitive or eczema-prone skin: pick one.' },
  { pair: ['retinoid', 'aha'], verdict: 'caution', evidence: 'inference', src: ['retinoids', 'aha', 'fdaAha'],
    headline: 'Two exfoliating irritants at once — and AHAs also raise sun sensitivity',
    detail: 'Glycolic / lactic acid thin the stratum corneum and the FDA notes they increase sun sensitivity; retinoids independently cause peeling and photosensitivity. Together the barrier takes a double hit.',
    how: 'Alternate nights, keep AHA strength modest (≤10% at home), and wear sunscreen every morning. Skip the AHA the night after any peeling.' },
  { pair: ['aha', 'bha'], verdict: 'caution', evidence: 'inference', src: ['aha', 'bha', 'fdaAha'],
    headline: 'Both are chemical exfoliants — using both daily over-exfoliates',
    detail: 'AHAs work on the surface and are humectant-like; salicylic acid is oil-soluble and goes into pores. Combining them is common in products, but stacking two separate exfoliants every day removes more barrier than it can rebuild.',
    how: 'Pick one for daily use, or alternate (AHA for texture/pigment, BHA for congested pores) 2–3 nights a week each. Sunscreen daily either way.' },
  { pair: ['retinoid', 'bpo'], verdict: 'avoid', evidence: 'direct', src: ['bpoRetinoid'],
    headline: 'Benzoyl peroxide destroys tretinoin when mixed; adapalene survives it',
    detail: 'Mixed with benzoyl peroxide 10% and exposed to light, tretinoin lost more than 50% in about 2 hours and 95% in 24 hours; adapalene was stable in the same test. Retinol is also an oxidation-sensitive molecule, so the same caution applies to cosmetic retinol.',
    how: 'Benzoyl peroxide in the morning, tretinoin/retinol at night. Adapalene + benzoyl peroxide can be used together (fixed-dose combinations exist).' },
  { pair: ['retinoid', 'vitc'], verdict: 'caution', evidence: 'inference', src: ['vitc', 'retinoids'],
    headline: 'Fine to own both — just not usually in the same sitting',
    detail: 'L-ascorbic acid needs a low pH (below 3.5) and stings at higher strengths; a retinoid adds its own irritation. Neither cancels the other, but two irritants in one application is more than most skin enjoys while adapting.',
    how: 'Vitamin C in the morning (under sunscreen, where it also adds photoprotection), retinoid at night. Gentle derivatives (ascorbyl glucoside, ethyl ascorbic acid) are easier to combine.' },
  { pair: ['retinoid', 'niacinamide'], verdict: 'synergy', evidence: 'direct', src: ['retinization', 'niacinamide'],
    headline: 'Niacinamide makes retinoids easier to tolerate',
    detail: 'In a paired, double-blind study, a barrier-enhancing moisturiser with niacinamide, panthenol and tocopheryl acetate used before and during tretinoin 0.025% reduced early retinoid irritation and improved the treatment response.',
    how: 'Apply niacinamide/moisturiser first (or the same night), then the retinoid. Good pairing for beginners.' },
  { pair: ['retinoid', 'sunscreen'], verdict: 'essential', evidence: 'direct', src: ['retinoids'],
    headline: 'Retinoids are for night; sunscreen every morning is part of using them',
    detail: 'Retinoids are photolabile (break down in light) and increase sun sensitivity during retinization, so daytime UV both undoes the product and worsens irritation.',
    how: 'Retinoid at night only; broad-spectrum SPF 30+ every morning, reapplied if outdoors.' },
  { pair: ['aha', 'sunscreen'], verdict: 'essential', evidence: 'regulatory', src: ['fdaAha'],
    headline: 'AHAs increase sun sensitivity — the FDA says use daily sun protection with them',
    detail: 'FDA guidance for AHA cosmetics: products should protect from increased sun sensitivity or instruct consumers to use daily sun protection.',
    how: 'Sunscreen every morning while using glycolic/lactic products, and for a week after stopping.' },
  { pair: ['vitc', 'niacinamide'], verdict: 'fine', evidence: 'inference', src: ['niacinamide', 'vitc'],
    headline: 'The "they cancel out" worry is outdated — both are well tolerated together',
    detail: 'The old concern (niacinamide + ascorbic acid forming irritating nicotinic acid) came from heating unbuffered lab solutions, not skin use. The clinical reviews of each ingredient report no interaction; many products combine them.',
    how: 'Layer freely, or use vitamin C in the morning and niacinamide any time.' },
  { pair: ['vitc', 'vite'], verdict: 'synergy', evidence: 'direct', src: ['ferulicCE', 'vitc'],
    headline: 'Vitamin C + E (+ ferulic acid) protect each other and the skin',
    detail: 'Vitamin C regenerates vitamin E; adding ferulic acid stabilised a C + E solution and doubled its photoprotection in a published study. This is why the classic 15% C / 1% E / 0.5% ferulic formula exists.',
    how: 'Look for them in one serum rather than layering three products.' },
  { pair: ['vitc', 'ferulic'], verdict: 'synergy', evidence: 'direct', src: ['ferulicCE'],
    headline: 'Ferulic acid stabilises vitamin C and boosts its photoprotection',
    detail: 'Adding 0.5% ferulic acid to a vitamin C + E solution improved stability and doubled photoprotection against UV in the cited study.',
    how: 'A morning serum containing both, under sunscreen.' },
  { pair: ['vitc', 'aha'], verdict: 'caution', evidence: 'inference', src: ['vitc', 'aha'],
    headline: 'Both are low-pH — stacking them stings and over-exfoliates',
    detail: 'L-ascorbic acid sits at pH ~3; glycolic/lactic acids at pH 3–4. Each is tolerable alone; together in one application they add up to more acid load than most skin wants.',
    how: 'Vitamin C in the morning, AHA at night (on nights without retinoid).' },
  { pair: ['vitc', 'bha'], verdict: 'caution', evidence: 'inference', src: ['vitc', 'bha'],
    headline: 'Both acidic and both can sting — separate them by time of day',
    detail: 'No chemical incompatibility, but L-ascorbic acid and salicylic acid are both low-pH irritants. Derivative forms of vitamin C are gentler if you want them in one routine.',
    how: 'Vitamin C AM, BHA PM (or alternate nights with a retinoid).' },
  { pair: ['azelaic', 'retinoid'], verdict: 'fine', evidence: 'inference', src: ['azelaic', 'retinoids'],
    headline: 'Azelaic acid is mild enough to sit alongside a retinoid',
    detail: 'Azelaic acid causes only transient mild burning/itch in most users and is used for acne, rosacea and melasma; it is often prescribed with a retinoid in acne and pigmentation regimens.',
    how: 'Azelaic in the morning (it is not photosensitising) and retinoid at night, or azelaic first then retinoid at night once your skin tolerates the retinoid alone.' },
  { pair: ['azelaic', 'niacinamide'], verdict: 'fine', evidence: 'inference', src: ['azelaic', 'niacinamide'],
    headline: 'Two well-tolerated anti-redness / pigment actives — no conflict',
    detail: 'Both are used for acne, rosacea-type redness and post-inflammatory marks; neither is photosensitising or strongly acidic.',
    how: 'Layer in either order, morning or night.' },
  { pair: ['azelaic', 'aha'], verdict: 'caution', evidence: 'inference', src: ['azelaic', 'aha', 'fdaAha'],
    headline: 'Usually fine, but add the AHA slowly',
    detail: 'Azelaic acid is mild; the AHA is the exfoliating, photosensitising partner. Combining is common for pigmentation but doubles the acid load on already-irritated skin.',
    how: 'Azelaic daily; AHA 2–3 nights a week; sunscreen daily.' },
  { pair: ['hydroquinone', 'retinoid'], verdict: 'fine', evidence: 'direct', src: ['cdscoHq'],
    headline: 'Hydroquinone + tretinoin (+ a mild steroid) is the prescription melasma standard',
    detail: 'The triple-combination cream (hydroquinone 4%, tretinoin, a corticosteroid) is the best-evidenced melasma treatment — but hydroquinone is prescription-only in India and the combination needs a dermatologist to supervise duration and rebound.',
    how: 'Only under a dermatologist. Never buy hydroquinone from a marketplace listing without a prescription.' },
  { pair: ['niacinamide', 'bha'], verdict: 'fine', evidence: 'inference', src: ['niacinamide', 'bha'],
    headline: 'A calm, common acne pairing',
    detail: 'Salicylic acid clears pores; niacinamide reduces sebum and redness and supports the barrier. Niacinamide has no pH conflict with BHA.',
    how: 'BHA first (or as a cleanser/toner), then niacinamide.' },
  { pair: ['niacinamide', 'aha'], verdict: 'fine', evidence: 'inference', src: ['niacinamide', 'aha'],
    headline: 'Niacinamide softens the dryness of AHAs',
    detail: 'No interaction; niacinamide improves barrier lipids and hydration, which is what AHAs deplete.',
    how: 'AHA first, wait a minute, then niacinamide and moisturiser.' },
  { pair: ['barrier', 'retinoid'], verdict: 'synergy', evidence: 'direct', src: ['retinization', 'ceramide'],
    headline: 'Moisturiser before or with a retinoid reduces irritation ("buffering")',
    detail: 'Pre-conditioning with a barrier moisturiser for 2 weeks and continuing during tretinoin reduced early irritation and improved outcomes; ceramide moisturisers measurably improve barrier function.',
    how: 'Moisturiser, then retinoid (or the "sandwich": moisturiser–retinoid–moisturiser) while starting out.' },
  { pair: ['ha', 'retinoid'], verdict: 'fine', evidence: 'inference', src: ['ha', 'retinoids'],
    headline: 'Hydration under a retinoid helps with the dryness',
    detail: 'Hyaluronic acid is a humectant with no irritation profile; it does not change how a retinoid works.',
    how: 'HA on damp skin, then retinoid, then moisturiser to seal.' },
  { pair: ['bakuchiol', 'retinoid'], verdict: 'fine', evidence: 'direct', src: ['bakuchiol'],
    headline: 'Bakuchiol is the gentler alternative, not an add-on you need with retinol',
    detail: 'In a 12-week RCT bakuchiol 0.5% twice daily matched retinol 0.5% nightly on wrinkles and pigmentation with less scaling and stinging.',
    how: 'Use bakuchiol on retinoid-off nights or as the retinoid replacement for sensitive skin/pregnancy-safe routines (confirm with your doctor).' },
  { pair: ['tranexamic', 'niacinamide'], verdict: 'fine', evidence: 'inference', src: ['tranexamic', 'niacinamide'],
    headline: 'A common, gentle pigmentation pairing',
    detail: 'Topical tranexamic acid reduced melasma in a randomised trial; niacinamide reduces pigment transfer. Neither is acidic or photosensitising.',
    how: 'Layer freely, day or night, under sunscreen by day.' },
  { pair: ['arbutin', 'vitc'], verdict: 'fine', evidence: 'inference', src: ['pigment', 'vitc'],
    headline: 'Tyrosinase inhibitors and vitamin C work on different steps of pigment',
    detail: 'Arbutin / kojic acid / liquorice inhibit tyrosinase; vitamin C reduces oxidised melanin and is an antioxidant. Combining is standard in brightening routines.',
    how: 'Vitamin C in the morning, arbutin/kojic morning or night; sunscreen is what makes any of it hold.' },
  { pair: ['minoxidil', 'antidandruff'], verdict: 'fine', evidence: 'inference', src: ['minoxidil', 'dandruff'],
    headline: 'Minoxidil and a ketoconazole/ZPT shampoo target different things and are routinely used together',
    detail: 'Minoxidil is the evidence-graded topical for androgenetic hair fall; anti-dandruff shampoos treat the scalp condition. No interaction; the shampoo just needs rinsing before minoxidil goes on a dry scalp.',
    how: 'Shampoo, dry the scalp, then minoxidil. Minoxidil is a drug — check with a doctor for dose and pregnancy.' },
  { pair: ['heat', 'hairoil'], verdict: 'avoid', evidence: 'inference', src: ['thermalProtect', 'hairOils'],
    headline: 'Oil on the hair right before a hot tool is not heat protection',
    detail: 'Thermal protection in the cited study came from silicones, conditioning polymers and hydrolysed proteins that reduce heat transfer; plain oils are for pre-wash conditioning (coconut oil reduces protein loss) and can heat up on the fibre.',
    how: 'Oil before washing; a labelled heat protectant (silicones/polymers) on damp hair before drying, and on dry hair before a straightener.' },
  { pair: ['keratin', 'heat'], verdict: 'caution', evidence: 'regulatory', src: ['fdaFormaldehyde'],
    headline: 'Smoothening kits that release formaldehyde do so when heated',
    detail: 'The FDA warns that many "keratin"/smoothing products release formaldehyde gas when flat-ironed; formaldehyde and methylene glycol are banned in EU cosmetics.',
    how: 'Check the INCI for formaldehyde / methylene glycol / formalin and avoid those; use a ventilated space if a salon insists.' },
];

// Single-ingredient use notes the assistant can quote (start-up, timing, who should ask a doctor).
const USAGE = [
  { family: 'retinoid', src: ['retinoids', 'retinization'],
    notes: ['Start 2–3 nights a week with a pea-sized amount and build up; redness, peeling and dryness in the first weeks are expected retinization, not allergy.',
      'Night use only; broad-spectrum sunscreen every morning.',
      'Moisturiser before/after (buffering) reduces irritation without stopping it working.',
      'Prescription retinoids (tretinoin, adapalene) and pregnancy/breast-feeding: ask a doctor before using any retinoid.'] },
  { family: 'aha', src: ['aha', 'fdaAha'], notes: ['Increases sun sensitivity — daily sunscreen is not optional.', 'Home strengths: glycolic ≤10%, lactic ≤10%; leave stronger peels to a dermatologist.'] },
  { family: 'bha', src: ['bha'], notes: ['0.5–2% is the cosmetic range; works best at low pH and takes 6–8 weeks for pores.', 'Dries — pair with a moisturiser; avoid with aspirin allergy.'] },
  { family: 'vitc', src: ['vitc'], notes: ['L-ascorbic acid: 10–20%, pH under 3.5, in an opaque airtight pack; a brown/orange serum has oxidised.', 'Derivatives (ascorbyl glucoside, ethyl ascorbic acid, THD ascorbate) are more stable and gentler but have less direct evidence.'] },
  { family: 'niacinamide', src: ['niacinamide'], notes: ['2–5% is the studied range; higher % adds flushing risk without more evidence.', 'Well tolerated day or night and with almost every other active.'] },
  { family: 'azelaic', src: ['azelaic'], notes: ['10% is cosmetic; 15–20% is prescription in most countries. Mild transient itch/burn is normal at first.', 'Not photosensitising — fine in the morning.'] },
  { family: 'hydroquinone', src: ['cdscoHq'], notes: ['Prescription-only depigmenting drug; supervised courses only, with breaks — long unsupervised use risks ochronosis (darkening).'] },
  { family: 'sunscreen', src: ['sunFilters'], notes: ['Broad-spectrum SPF 30+ is the one step every active above depends on; reapply every 2 hours outdoors.'] },
  { family: 'minoxidil', src: ['minoxidil'], notes: ['Evidence-graded topical for androgenetic hair fall; shedding in the first weeks is expected; results need ~4–6 months and stop if you stop.', 'It is a drug — dose, pregnancy and heart conditions need a doctor.'] },
  { family: 'antidandruff', src: ['dandruff', 'dandruffIndia'], notes: ['Ketoconazole 1–2%, zinc pyrithione, piroctone olamine and selenium sulfide are the evidence-graded actives; leave the lather on the scalp 3–5 minutes before rinsing.', 'Use 2–3× a week, then taper to maintenance.'] },
  { family: 'heat', src: ['thermalProtect'], notes: ['A heat protectant (silicones, conditioning polymers, hydrolysed proteins) on damp hair before blow-drying and on dry hair before irons is what actually limits thermal damage.'] },
  { family: 'hairoil', src: ['hairOils'], notes: ['Coconut oil penetrates the shaft and reduces protein loss — as a pre-wash treatment; mineral and sunflower oil coat but do not penetrate.'] },
  { family: 'dryshampoo', src: ['hairCleansing'], notes: ['Absorbs sebum between washes; it does not clean the scalp, so it is a stopgap, not a shampoo replacement.'] },
  { family: 'keratin', src: ['fdaFormaldehyde'], notes: ['Check the INCI: formaldehyde, methylene glycol, formalin or paraformaldehyde mean the treatment releases formaldehyde when heated.'] },
];

module.exports = { FAMILIES, PAIRINGS, USAGE };
