// Maker accountability — WHO stands behind the product, verified from the company's own corporate / about page.
// Not brand reputation and not seller copy: it records the identifiable manufacturer or importer that carries
// warranty, BIS/CE compliance and service obligations in India. Brands absent here score "maker not verified".
const KIND = {
  global: { pts: 7.5, label: 'Global manufacturer with an Indian entity and service network' },
  india: { pts: 7.0, label: 'Established Indian manufacturer / listed company' },
  d2c: { pts: 5.0, label: 'Indian brand with its own company, website and warranty channel' },
  unknown: { pts: 2.5, label: 'Maker not verified — no company, official site or service channel found' },
};

// [brand keys (lowercase)], legal maker, kind, source URL (about / corporate page), official catalogue root
const MAKERS = [
  // Power & accessories
  [['anker', 'soundcore', 'eufy'], 'Anker Innovations', 'global', 'https://www.anker.com/about-anker', 'https://www.ankerindia.com'],
  [['xiaomi', 'mi', 'redmi'], 'Xiaomi Technology India', 'global', 'https://www.mi.com/in/about/', 'https://www.mi.com/in'],
  [['samsung'], 'Samsung India Electronics', 'global', 'https://www.samsung.com/in/about-us/company-info/', 'https://www.samsung.com/in'],
  [['philips'], 'Philips Domestic Appliances India (Versuni)', 'global', 'https://www.versuni.com/about-us/', 'https://www.philips.co.in'],
  [['panasonic'], 'Panasonic Life Solutions India', 'global', 'https://www.panasonic.com/in/corporate/profile.html', 'https://www.panasonic.com/in'],
  [['braun'], 'Braun (Procter & Gamble)', 'global', 'https://www.braun.com/en-in/about-braun', 'https://www.braun.com/en-in'],
  [['dyson'], 'Dyson Technology India', 'global', 'https://www.dyson.in/inside-dyson', 'https://www.dyson.in'],
  [['energizer'], 'Energizer Holdings (licensed India distributor)', 'global', 'https://www.energizer.com/about-energizer', 'https://www.energizer.com'],
  [['duracell'], 'Duracell (Berkshire Hathaway)', 'global', 'https://www.duracell.in/about-duracell/', 'https://www.duracell.in'],
  [['spigen'], 'Spigen Inc.', 'global', 'https://www.spigen.com/pages/about-us', 'https://www.spigen.in'],
  [['belkin'], 'Belkin International (Foxconn Interconnect)', 'global', 'https://www.belkin.com/about-us/', 'https://www.belkin.com/in'],
  [['ugreen'], 'UGREEN Group', 'global', 'https://www.ugreen.com/pages/about-us', 'https://www.ugreen.com'],
  [['baseus'], 'Baseus Technology', 'global', 'https://www.baseus.com/pages/about-us', 'https://www.baseus.com'],
  [['realme'], 'realme Mobile Telecommunications India', 'global', 'https://www.realme.com/in/about-us', 'https://www.realme.com/in'],
  [['oneplus'], 'OnePlus Technology India', 'global', 'https://www.oneplus.in/about-us', 'https://www.oneplus.in'],
  [['boat'], 'Imagine Marketing Ltd (boAt)', 'india', 'https://www.boat-lifestyle.com/pages/about-us', 'https://www.boat-lifestyle.com'],
  [['ambrane'], 'Ambrane India Pvt Ltd', 'india', 'https://www.ambraneindia.com/pages/about-us', 'https://www.ambraneindia.com'],
  [['portronics'], 'Portronics Digital Pvt Ltd', 'india', 'https://www.portronics.com/pages/about-us', 'https://www.portronics.com'],
  [['zebronics'], 'Zebronics India Pvt Ltd', 'india', 'https://zebronics.com/pages/about-us', 'https://zebronics.com'],
  [['syska'], 'Syska LED Lights Pvt Ltd (SSK Group)', 'india', 'https://www.syska.co.in/about-us', 'https://www.syska.co.in'],
  [['intex'], 'Intex Technologies (India) Ltd', 'india', 'https://www.intex.in/about-us', 'https://www.intex.in'],
  [['noise'], 'Nexxbase Marketing Pvt Ltd (Noise)', 'india', 'https://www.gonoise.com/pages/about-us', 'https://www.gonoise.com'],
  [['ptron'], 'Palred Electronics (pTron)', 'india', 'https://www.ptron.in/pages/about-us', 'https://www.ptron.in'],
  [['urbn'], 'URBN (Imagine Marketing / boAt group)', 'india', 'https://www.urbn.in/pages/about-us', 'https://www.urbn.in'],
  [['stuffcool'], 'Stuffcool (Mobicom Enterprises)', 'd2c', 'https://www.stuffcool.com/pages/about-us', 'https://www.stuffcool.com'],
  [['lifelong'], 'Lifelong Online Retail Pvt Ltd', 'india', 'https://www.lifelongindiaonline.com/pages/about-us', 'https://www.lifelongindiaonline.com'],
  [['beetel'], 'Beetel Teletech Ltd (Bharti group)', 'india', 'https://www.beetel.in/pages/about-us', 'https://www.beetel.in'],
  [['callmate'], 'Callmate India', 'd2c', 'https://www.callmateindia.com/about-us', 'https://www.callmateindia.com'],
  [['agaro'], 'Agaro (Cosmo Brands)', 'd2c', 'https://agarolifestyle.com/pages/about-us', 'https://agarolifestyle.com'],
  [['gravl'], 'GRAVL (Ancestor Digital)', 'd2c', 'https://gravl.in/pages/about-us', 'https://gravl.in'],
  [['ubon'], 'UBON (Star Electronics)', 'd2c', 'https://www.ubon.in/pages/about-us', 'https://www.ubon.in'],
  [['goboult', 'boult'], 'Boult Audio (Exotic Mile)', 'india', 'https://www.boultaudio.com/pages/about-us', 'https://www.boultaudio.com'],
  [['toreto'], 'Toreto Retail Pvt Ltd', 'd2c', 'https://www.toreto.in/pages/about-us', 'https://www.toreto.in'],
  [['eveready'], 'Eveready Industries India Ltd', 'india', 'https://www.evereadyindia.com/about-us', 'https://www.evereadyindia.com'],
  [['foxin'], 'Foxin (Foxin Electronics)', 'd2c', 'https://foxin.in/pages/about-us', 'https://foxin.in'],
  [['lapcare'], 'Lapcare (Kevin Overseas)', 'd2c', 'https://www.lapcare.com/pages/about-us', 'https://www.lapcare.com'],
  [['hammer'], 'Hammer Lifestyle', 'd2c', 'https://www.hammeronline.in/pages/about-us', 'https://www.hammeronline.in'],
  [['frontech'], 'Frontech (Jil Electronics)', 'd2c', 'https://frontech.in/about-us/', 'https://frontech.in'],
  [['kratos'], 'Kratos (Sarvottam Retail)', 'd2c', 'https://kratos.co.in/pages/about-us', 'https://kratos.co.in'],
  [['onelife'], 'OneLife (Onestop Stores)', 'd2c', 'https://onelifeindia.in/pages/about-us', 'https://onelifeindia.in'],
  [['calmora'], 'Calmora', 'd2c', 'https://calmora.in/pages/about-us', 'https://calmora.in'],
  // Grooming
  [['nova'], 'Nova Home Appliances', 'india', 'https://www.novaindia.com/about-us', 'https://www.novaindia.com'],
  [['havells', 'lloyd'], 'Havells India Ltd', 'india', 'https://www.havells.com/en/about-us.html', 'https://www.havells.com'],
  [['vega'], 'VEGA (Sanchi Impex)', 'india', 'https://www.vega.co.in/pages/about-us', 'https://www.vega.co.in'],
  [['wahl'], 'Wahl Clipper Corporation (Wahl India)', 'global', 'https://www.wahl.com/about-wahl', 'https://www.wahlindia.com'],
  [['mi trimmer'], 'Xiaomi Technology India', 'global', 'https://www.mi.com/in/about/', 'https://www.mi.com/in'],
  [['bombay shaving company', 'bombay shaving'], 'Visage Lines Personal Care (Bombay Shaving Company)', 'd2c', 'https://bombayshavingcompany.com/pages/about-us', 'https://bombayshavingcompany.com'],
  [['beardo'], 'Marico Ltd (Beardo)', 'india', 'https://marico.com/india/brands', 'https://beardo.in'],
  [['ikonic'], 'Ikonic Professional', 'd2c', 'https://ikonicworld.com/pages/about-us', 'https://ikonicworld.com'],
  [['kubra'], 'Kubra (Sunrise Products)', 'd2c', 'https://kubra.in/pages/about-us', 'https://kubra.in'],
  [['kemei'], 'Kemei (Zhejiang Kemei Electric)', 'unknown', null, null],
  [['zlade'], 'Zlade Cosmetics', 'd2c', 'https://zlade.com/pages/about-us', 'https://zlade.com'],
  [['remington'], 'Remington (Spectrum Brands)', 'global', 'https://www.spectrumbrands.com/brands/', 'https://in.remington-europe.com'],
  [['ghd'], 'ghd (Coty)', 'global', 'https://www.ghdhair.com/in/about-us', 'https://www.ghdhair.com/in'],
  [['gillette'], 'Gillette India Ltd (Procter & Gamble)', 'global', 'https://www.pg.com/en-in/brands/gillette', 'https://www.gillette.co.in'],
  [['winston'], 'Winston (Winston Electronics)', 'd2c', 'https://winstonindia.com/pages/about-us', 'https://winstonindia.com'],
  [['urbangabru', 'urban gabru'], 'UrbanGabru (Natural Vibes)', 'd2c', 'https://urbangabru.in/pages/about-us', 'https://urbangabru.in'],
  [['marq by flipkart', 'marq'], 'MarQ (Flipkart private label)', 'india', 'https://www.flipkart.com/marq-store', 'https://www.flipkart.com/marq-store'],
  // Kitchen
  [['prestige'], 'TTK Prestige Ltd', 'india', 'https://www.ttkprestige.com/about-us', 'https://www.ttkprestige.com'],
  [['pigeon', 'gilma'], 'Stove Kraft Ltd', 'india', 'https://www.stovekraft.com/about-us/', 'https://www.stovekraft.com'],
  [['bajaj'], 'Bajaj Electricals Ltd', 'india', 'https://www.bajajelectricals.com/about-us/', 'https://shop.bajajelectricals.com'],
  [['usha'], 'Usha International Ltd', 'india', 'https://www.usha.com/about-us', 'https://www.usha.com'],
  [['butterfly'], 'Butterfly Gandhimathi Appliances (Crompton)', 'india', 'https://www.butterflyindia.com/about-us', 'https://www.butterflyindia.com'],
  [['crompton'], 'Crompton Greaves Consumer Electricals', 'india', 'https://www.crompton.co.in/pages/about-us', 'https://www.crompton.co.in'],
  [['preethi'], 'Preethi Kitchen Appliances (Versuni)', 'global', 'https://www.preethi.in/pages/about-us', 'https://www.preethi.in'],
  [['morphy richards'], 'Morphy Richards (Bajaj Electricals licensee)', 'india', 'https://www.morphyrichardsindia.com/about-us', 'https://www.morphyrichardsindia.com'],
  [['wonderchef'], 'Wonderchef Home Appliances', 'india', 'https://www.wonderchef.com/pages/about-us', 'https://www.wonderchef.com'],
  [['kent'], 'Kent RO Systems Ltd', 'india', 'https://www.kent.co.in/about-us', 'https://www.kent.co.in'],
  [['inalsa'], 'Inalsa Appliances (Taurus Group)', 'india', 'https://www.inalsa.com/about-us', 'https://www.inalsa.com'],
  [['borosil'], 'Borosil Ltd', 'india', 'https://www.borosil.com/pages/about-us', 'https://www.borosil.com'],
  [['milton'], 'Hamilton Housewares (Milton)', 'india', 'https://www.milton.in/about-us', 'https://www.milton.in'],
  [['cello'], 'Cello World Ltd', 'india', 'https://www.celloworld.com/about-us', 'https://www.celloworld.com'],
  [['stanley'], 'Stanley (PMI Worldwide)', 'global', 'https://www.stanley1913.com/pages/about-us', 'https://www.stanley1913.com'],
  [['tupperware'], 'Tupperware Brands', 'global', 'https://www.tupperware.com/pages/about-us', 'https://www.tupperwareindia.com'],
  [['nutribullet', 'nutri bullet'], 'NutriBullet LLC', 'global', 'https://www.nutribullet.com/about-us/', 'https://www.nutribullet.in'],
  [['blendjet'], 'BlendJet Inc.', 'global', 'https://blendjet.com/pages/about-us', 'https://blendjet.com'],
  [['ninja', 'shark'], 'SharkNinja', 'global', 'https://www.sharkninja.com/about-us/', 'https://ninjakitchen.in'],
  [['ibell'], 'iBELL (Ibell Electronics)', 'd2c', 'https://ibell.in/about-us/', 'https://ibell.in'],
  [['v-guard', 'v guard', 'vguard'], 'V-Guard Industries Ltd', 'india', 'https://www.vguard.in/about-us', 'https://www.vguard.in'],
  [['hawkins'], 'Hawkins Cookers Ltd', 'india', 'https://www.hawkinscookers.com/about-us.aspx', 'https://www.hawkinscookers.com'],
  [['bosch'], 'BSH Household Appliances India (Bosch)', 'global', 'https://www.bosch-home.in/about-bosch', 'https://www.bosch-home.in'],
  [['midea'], 'Midea India (Carrier Midea)', 'global', 'https://www.midea.com/in/about-midea', 'https://www.midea.com/in'],
  [['greenchef'], 'Greenchef Appliances Ltd', 'india', 'https://www.greenchef.in/about-us', 'https://www.greenchef.in'],
  [['cellecor'], 'Cellecor Gadgets Ltd', 'india', 'https://cellecor.com/about-us/', 'https://cellecor.com'],
  [['longway'], 'Longway (Longway Industries)', 'd2c', 'https://longway.in/about-us/', 'https://longway.in'],
  [['boldfit'], 'Boldfit (Sportsfit World)', 'd2c', 'https://www.boldfit.in/pages/about-us', 'https://www.boldfit.in'],
  [['instacuppa'], 'InstaCuppa (Tapasya Products)', 'd2c', 'https://instacuppa.com/pages/about-us', 'https://instacuppa.com'],
  [['jaypee', 'jaypee plus'], 'Jaypee Plus (Jai Prakash Plastics)', 'india', 'https://jaypeeplus.com/pages/about-us', 'https://jaypeeplus.com'],
  [['flair'], 'Flair Writing Industries Ltd', 'india', 'https://flairworld.in/about-us/', 'https://flairworld.in'],
  [['kutchina'], 'Kutchina Home Makers', 'india', 'https://www.kutchina.com/about-us', 'https://www.kutchina.com'],
  [['kaff'], 'KAFF Appliances (India)', 'india', 'https://www.kaff.in/about-us', 'https://www.kaff.in'],
  [['baltra'], 'Baltra Home Products', 'india', 'https://www.baltra.in/about-us', 'https://www.baltra.in'],
  // Outdoor
  [['quechua', 'forclaz', 'decathlon', 'kalenji', 'simond'], 'Decathlon Sports India', 'global', 'https://www.decathlon.in/corporate-about-us', 'https://www.decathlon.in'],
  [['wildcraft'], 'Wildcraft India Pvt Ltd', 'india', 'https://wildcraft.com/pages/about-us', 'https://wildcraft.com'],
  [['columbia'], 'Columbia Sportswear', 'global', 'https://www.columbia.com/about-us/', 'https://www.columbiasportswear.co.in'],
  [['the north face', 'north face'], 'The North Face (VF Corporation)', 'global', 'https://www.thenorthface.com/en-us/about-us', 'https://www.thenorthface.com'],
  [['salomon'], 'Salomon (Amer Sports)', 'global', 'https://www.salomon.com/en-us/about-us', 'https://www.salomon.com'],
  [['merrell'], 'Merrell (Wolverine World Wide)', 'global', 'https://www.merrell.com/US/en/about-us', 'https://www.merrell.com'],
  [['woodland'], 'Aero Group (Woodland)', 'india', 'https://www.woodlandworldwide.com/about-us', 'https://www.woodlandworldwide.com'],
  [['red chief'], 'Leayan Global (Red Chief)', 'india', 'https://redchief.in/pages/about-us', 'https://redchief.in'],
  [['campus'], 'Campus Activewear Ltd', 'india', 'https://www.campusshoes.com/about-us', 'https://www.campusshoes.com'],
  [['bata', 'power', 'hush puppies'], 'Bata India Ltd', 'india', 'https://www.bata.in/about-us', 'https://www.bata.in'],
  [['puma'], 'PUMA India', 'global', 'https://about.puma.com/en', 'https://in.puma.com'],
  [['adidas'], 'adidas India', 'global', 'https://www.adidas-group.com/en/about/', 'https://www.adidas.co.in'],
  [['nike'], 'Nike India', 'global', 'https://about.nike.com/en', 'https://www.nike.com/in'],
  [['skechers'], 'Skechers South Asia', 'global', 'https://about.skechers.com/', 'https://www.skechers.in'],
  [['red tape', 'redtape'], 'Redtape Ltd', 'india', 'https://redtape.com/pages/about-us', 'https://redtape.com'],
  [['liberty'], 'Liberty Shoes Ltd', 'india', 'https://www.libertyshoes.com/about-us', 'https://www.libertyshoes.com'],
  [['lakhani'], 'Lakhani Footwear', 'india', 'https://www.lakhanifootwear.com/about-us', 'https://www.lakhanifootwear.com'],
  [['sparx', 'relaxo', 'bahamas', 'flite'], 'Relaxo Footwears Ltd', 'india', 'https://www.relaxofootwear.com/about-us', 'https://www.relaxofootwear.com'],
  [['asian'], 'Asian Footwears Pvt Ltd', 'india', 'https://www.asianfootwears.com/pages/about-us', 'https://www.asianfootwears.com'],
  [['bacca bucci'], 'Bacca Bucci (BB Fashion)', 'd2c', 'https://www.baccabucci.com/pages/about-us', 'https://www.baccabucci.com'],
  [['unistar'], 'Unistar Footwear (Unistar Industries)', 'india', 'https://unistarindia.com/about-us/', 'https://unistarindia.com'],
  [['hrx by hrithik roshan', 'hrx'], 'HRX (Exceed Entertainment / Myntra)', 'india', 'https://www.hrxbrand.com/pages/about-us', 'https://www.hrxbrand.com'],
  [['wrogn'], 'WROGN (Universal Sportsbiz)', 'india', 'https://www.wrogn.com/pages/about-us', 'https://www.wrogn.com'],
  [['trawoc'], 'Trawoc (Bag Studio)', 'd2c', 'https://trawoc.com/pages/about-us', 'https://trawoc.com'],
  [['nivia'], 'Nivia Sports (Freewill Sports)', 'india', 'https://niviasports.com/pages/about-us', 'https://niviasports.com'],
  [['abros'], 'Abros (Abros Footwear)', 'd2c', 'https://abros.in/pages/about-us', 'https://abros.in'],
  [['timberland'], 'Timberland (VF Corporation)', 'global', 'https://www.timberland.com/en-us/about-us', 'https://www.timberland.in'],
  [['keen'], 'KEEN Footwear', 'global', 'https://www.keenfootwear.com/about-us/', 'https://www.keenfootwear.com'],
  [['lowa'], 'LOWA Sportschuhe GmbH', 'global', 'https://www.lowa.com/en/about-lowa', 'https://www.lowa.com'],
  [['scarpa'], 'SCARPA (Calzaturificio S.C.A.R.P.A.)', 'global', 'https://www.scarpa.com/company', 'https://www.scarpa.com'],
  [['la sportiva'], 'La Sportiva S.p.A.', 'global', 'https://www.lasportiva.com/en/company', 'https://www.lasportiva.com'],
  [['hoka'], 'HOKA (Deckers Brands)', 'global', 'https://www.deckers.com/brands/hoka', 'https://www.hoka.com'],
  [['zippo'], 'Zippo Manufacturing Company', 'global', 'https://www.zippo.com/pages/about-us', 'https://www.zippo.com'],
  [['yeti'], 'YETI Holdings', 'global', 'https://www.yeti.com/about-us.html', 'https://www.yeti.com'],
  [['hydro flask'], 'Hydro Flask (Helen of Troy)', 'global', 'https://www.hydroflask.com/about-us', 'https://www.hydroflask.com'],
  [['owala'], 'Owala (Trove Brands)', 'global', 'https://owalalife.com/pages/about-us', 'https://owalalife.com'],
  [['dyson supersonic'], 'Dyson Technology India', 'global', 'https://www.dyson.in/inside-dyson', 'https://www.dyson.in'],
  [['american tourister', 'samsonite'], 'Samsonite South Asia', 'global', 'https://www.samsonite.com/about-us/', 'https://www.americantourister.in'],
  [['skybags', 'vip', 'aristocrat', 'carlton'], 'VIP Industries Ltd', 'india', 'https://www.vipindustries.co.in/about-us', 'https://www.skybags.co.in'],
  [['safari'], 'Safari Industries (India) Ltd', 'india', 'https://www.safaribags.com/about-us', 'https://www.safaribags.com'],
  [['f gear', 'fgear'], 'F Gear (Shivam Bags)', 'd2c', 'https://www.fgear.in/pages/about-us', 'https://www.fgear.in'],
  [['gear'], 'Gear (Glow Bags)', 'd2c', 'https://www.gearbags.com/pages/about-us', 'https://www.gearbags.com'],
  [['tripole'], 'Tripole Gears', 'd2c', 'https://www.tripole.in/pages/about-us', 'https://www.tripole.in'],
  [['mufubu'], 'Mufubu (Genex Bags)', 'd2c', 'https://mufubu.com/pages/about-us', 'https://mufubu.com'],
  [['impulse'], 'Impulse Bags', 'd2c', 'https://impulsebags.in/pages/about-us', 'https://impulsebags.in'],
  [['osprey'], 'Osprey Packs (Helen of Troy)', 'global', 'https://www.osprey.com/about-osprey', 'https://www.osprey.com'],
  [['deuter'], 'Deuter Sport GmbH', 'global', 'https://www.deuter.com/int-en/about-deuter', 'https://www.deuter.com'],
  [['fjallraven', 'fjällräven'], 'Fjällräven (Fenix Outdoor)', 'global', 'https://www.fjallraven.com/about-fjallraven', 'https://www.fjallraven.com'],
];

const norm = (s) => String(s || '').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9 ]+/g, ' ').replace(/\s+/g, ' ').trim();

// Longest key wins so "bombay shaving company" beats "company" and "the north face" beats "north".
const INDEX = MAKERS.flatMap(([keys, parent, kind, source, site]) => keys.map((k) => ({ key: norm(k), parent, kind, source, site }))).sort((a, b) => b.key.length - a.key.length);

function makerOf(brand) {
  const b = norm(brand);
  const hit = INDEX.find((e) => b === e.key || b.startsWith(e.key + ' ') || b.endsWith(' ' + e.key) || b.includes(' ' + e.key + ' '));
  if (!hit) return { parent: null, kind: 'unknown', label: KIND.unknown.label, pts: KIND.unknown.pts, url: null, site: null };
  return { parent: hit.parent, kind: hit.kind, label: KIND[hit.kind].label, pts: KIND[hit.kind].pts, url: hit.source, site: hit.site };
}

module.exports = { makerOf, KIND, MAKERS };
