// Researched market data: trekking / hiking shoes sold in India under ~₹3,000.
// Prices in INR, researched 19 Jul 2026 — Decathlon.in, Flipkart, baccabucci.com,
// thesouledstore.com verified live in the browser; Amazon.in cross-checked via
// search/price trackers (direct browsing blocked from this VM). Where a maker
// does not publish a figure it is marked "Not officially published" — never guessed.
// The requester's priority: keep sand/dirt/water OUT (avoid open mesh), plus
// looks and comfort — see scoring.js weights.
const SHOES = [
  {
    id: "quechua-mh100-low",
    brand: "Quechua (Decathlon)",
    model: "MH100 Mountain Hiking Shoes (low, grey)",
    price: 2999,
    upper: "Synthetic + mesh panels",
    sealing: "Water-repellent coating only (not waterproof)",
    ankle: "Low ankle",
    outsole: "Decathlon Contact rubber, 4mm lugs",
    highlight: "Indiahikes-recommended budget classic — best grip and comfort of any sub-₹3k trekking shoe, but the low-cut mesh version lets in dust; lace them tight or add gaiters.",
    pros: [
      "Proven on easy–moderate Himalayan treks (Indiahikes pick)",
      "Excellent Contact-sole traction on rock and mud",
      "Cushioned EVA midsole, comfortable out of the box",
      "6.8k+ Decathlon ratings, easy in-store returns/repairs",
    ],
    cons: [
      "Mesh panels let fine sand/dust in — your key complaint",
      "This ₹2,999 grey version is NOT the waterproof MH100 (that's ₹3,999)",
      "Low ankle gives less debris protection",
    ],
    scores: { sealing: 5.5, grip: 9.0, comfort: 8.5, build: 8.0, looks: 7.0, value: 8.0 },
    fullSpec: {
      upperMaterial: "Synthetic PU + breathable mesh panels",
      waterproofing: "Water-repellent coating; no membrane",
      dustSealing: "Partial — mesh panels admit fine dust",
      ankleHeight: "Low ankle",
      outsole: "Contact rubber outsole, 4 mm lugs",
      midsole: "EVA cushioning",
      insole: "Removable EVA footbed",
      toeProtection: "Rubber toe bumper",
      closure: "Standard laces",
      weight: "~390 g per shoe (UK 9, Decathlon figure)",
      colours: "Grey",
      sizes: "UK 6–12",
      bestFor: "Dry-season day hikes, easy–moderate Himalayan treks",
      warranty: "2-year Decathlon warranty",
      rating: "4.6★ (5.7k Decathlon reviews)",
      madeIn: "India",
    },
    buyUrl: "https://www.decathlon.in/search?query=MH100%20hiking%20shoes%20men",
    buyStore: "Decathlon",
  },
  {
    id: "quechua-nh100-mid",
    brand: "Quechua (Decathlon)",
    model: "NH100 Mid Ankle Hiking Shoes",
    price: 1999,
    upper: "Synthetic (minimal mesh)",
    sealing: "No waterproofing; closed synthetic upper keeps most dust out",
    ankle: "Mid ankle",
    outsole: "Rubber, moderate lugs",
    highlight: "Sturdy mid-ankle build with a mostly-closed upper — good dust protection for the price, but zero water resistance.",
    pros: [
      "Mid-ankle collar blocks sand and pebbles",
      "Abuse-friendly build (trekker-reviewed on Indiahikes)",
      "3.1k Decathlon ratings, 2-year warranty",
      "Cheap enough to be a beater pair",
    ],
    cons: [
      "No water resistance at all — dry hikes only",
      "Heavier feel than the MH100",
      "Basic cushioning on long descents",
    ],
    scores: { sealing: 6.5, grip: 7.5, comfort: 7.0, build: 7.5, looks: 6.5, value: 8.5 },
    fullSpec: {
      upperMaterial: "Synthetic leather-look upper, minimal mesh",
      waterproofing: "None",
      dustSealing: "Good — closed upper + mid collar",
      ankleHeight: "Mid ankle",
      outsole: "Rubber outsole, moderate lugs",
      midsole: "EVA",
      insole: "Fixed cushioned footbed",
      toeProtection: "Reinforced toe cap",
      closure: "Standard laces",
      weight: "Not officially published",
      colours: "Black",
      sizes: "UK 6–12",
      bestFor: "Western Ghats / dry trails, light loads",
      warranty: "2-year Decathlon warranty",
      rating: "4.5★ (3.1k Decathlon reviews)",
      madeIn: "India",
    },
    buyUrl: "https://www.decathlon.in/search?query=NH100%20mid%20hiking",
    buyStore: "Decathlon",
  },
  {
    id: "quechua-nh50",
    brand: "Quechua (Decathlon)",
    model: "NH50 Hiking Boots",
    price: 999,
    upper: "Synthetic",
    sealing: "No membrane; closed upper",
    ankle: "Mid ankle",
    outsole: "Rubber",
    highlight: "The cheapest real hiking boot in India (₹999, 60% off MRP) — 8.1k ratings; fine for casual trails, limited for serious treks.",
    pros: [
      "Unbeatable price for a branded boot",
      "Closed synthetic upper keeps dust out",
      "8.1k Decathlon ratings",
    ],
    cons: [
      "Entry-level grip and cushioning",
      "No water resistance",
      "Not built for multi-day treks",
    ],
    scores: { sealing: 6.0, grip: 6.0, comfort: 6.0, build: 6.0, looks: 6.0, value: 9.5 },
    fullSpec: {
      upperMaterial: "Synthetic",
      waterproofing: "None",
      dustSealing: "Good — closed upper",
      ankleHeight: "Mid ankle",
      outsole: "Rubber outsole",
      midsole: "EVA",
      insole: "Fixed footbed",
      toeProtection: "Basic toe bumper",
      closure: "Standard laces",
      weight: "Not officially published",
      colours: "Black, Green",
      sizes: "UK 6–12",
      bestFor: "Casual walks, easy trails, first-time hikers",
      warranty: "2-year Decathlon warranty",
      rating: "4.4★ (8.1k Decathlon reviews)",
      madeIn: "India",
    },
    buyUrl: "https://www.decathlon.in/search?query=NH50%20hiking%20boots",
    buyStore: "Decathlon",
  },
  {
    id: "wildcraft-sphere2-boot",
    brand: "Wildcraft",
    model: "Amphibia Sphere 2 Boot (high ankle)",
    price: 2149,
    upper: "Water-repellent synthetic/nubuck-look, no open mesh",
    sealing: "DWR water-repellent finish + closed upper",
    ankle: "High ankle",
    outsole: "HypaGrip™ rubber",
    highlight: "Best dust-and-splash sealing under ₹2.5k — water-repellent closed upper, high ankle, nylon shank stability and Wildcraft's HypaGrip traction.",
    pros: [
      "Closed water-repellent upper — exactly the non-mesh build you asked for",
      "High ankle + nylon shank for stability on uneven terrain",
      "HypaGrip outsole rated well by trekkers (Sandakphu-tested reviews)",
      "55% off MRP ₹4,799 on Flipkart",
    ],
    cons: [
      "Water-repellent, not fully waterproof — avoid monsoon stream crossings",
      "Runs warm in summer",
      "Wildcraft service is via stores, no formal shoe warranty stated",
    ],
    scores: { sealing: 8.5, grip: 8.5, comfort: 7.5, build: 8.0, looks: 8.0, value: 8.0 },
    fullSpec: {
      upperMaterial: "Water-repellent synthetic, closed weave (no open mesh)",
      waterproofing: "Durable water-repellent (DWR) finish; no membrane",
      dustSealing: "Very good — closed upper + high collar",
      ankleHeight: "High ankle",
      outsole: "HypaGrip™ rubber, aggressive lugs",
      midsole: "EVA + nylon shank for torsional stability",
      insole: "Cushioned footbed",
      toeProtection: "Rubber toe guard",
      closure: "Standard laces with metal eyelets",
      weight: "Not officially published",
      colours: "Tan, Black, Olive",
      sizes: "UK 6–11",
      bestFor: "Mixed/rocky terrain, easy–moderate Himalayan treks",
      warranty: "Not officially published (Flipkart 30-day replacement)",
      rating: "4.2★ (Flipkart)",
      madeIn: "India",
    },
    buyUrl: "https://www.flipkart.com/wildcraft-sphere-2-boot-low-ankle-outdoors-men/p/itm3a24207fb3926",
    buyStore: "Flipkart",
  },
  {
    id: "wildcraft-terra-lite",
    brand: "Wildcraft",
    model: "Terra Lite MA Hiking & Trekking Shoes",
    price: 2088,
    upper: "Closed synthetic",
    sealing: "Water-repellent finish",
    ankle: "Mid ankle",
    outsole: "HypaGrip™ rubber",
    highlight: "Lighter Wildcraft option with the same HypaGrip sole — good balance of weight, dust sealing and looks.",
    pros: [
      "Lightweight for all-day comfort",
      "HypaGrip traction",
      "Modern styling works off-trail too",
    ],
    cons: [
      "Less ankle protection than the Sphere Boot",
      "Water resistance is basic",
    ],
    scores: { sealing: 7.5, grip: 8.0, comfort: 8.0, build: 7.5, looks: 8.0, value: 8.0 },
    fullSpec: {
      upperMaterial: "Closed synthetic upper",
      waterproofing: "Water-repellent finish; no membrane",
      dustSealing: "Good — closed upper, mid collar",
      ankleHeight: "Mid ankle",
      outsole: "HypaGrip™ rubber",
      midsole: "EVA",
      insole: "Cushioned footbed",
      toeProtection: "Toe bumper",
      closure: "Standard laces",
      weight: "Not officially published (marketed as lightweight)",
      colours: "Multiple",
      sizes: "UK 6–11",
      bestFor: "Day hikes, mixed terrain, travel",
      warranty: "Not officially published (Flipkart 30-day replacement)",
      rating: "4.1★ (Flipkart)",
      madeIn: "India",
    },
    buyUrl: "https://www.flipkart.com/search?q=wildcraft%20terra%20lite%20ma",
    buyStore: "Flipkart",
  },
  {
    id: "wildcraft-volga-nx",
    brand: "Wildcraft",
    model: "Volga NX Low Ankle Outdoor Shoes",
    price: 1789,
    upper: "Closed synthetic",
    sealing: "Water-repellent finish",
    ankle: "Low ankle",
    outsole: "Rubber, multi-directional lugs",
    highlight: "Cheapest Wildcraft trekker — closed upper at ₹1,789, decent for weekend trails.",
    pros: [
      "Closed non-mesh upper at a low price",
      "Branded build vs generic imports",
      "55% off MRP ₹3,999",
    ],
    cons: [
      "Low ankle — less debris/sprain protection",
      "Basic cushioning",
    ],
    scores: { sealing: 7.0, grip: 7.0, comfort: 7.0, build: 7.0, looks: 7.0, value: 8.5 },
    fullSpec: {
      upperMaterial: "Closed synthetic upper",
      waterproofing: "Water-repellent finish; no membrane",
      dustSealing: "Good — closed upper",
      ankleHeight: "Low ankle",
      outsole: "Rubber, multi-directional lugs",
      midsole: "EVA",
      insole: "Cushioned footbed",
      toeProtection: "Toe bumper",
      closure: "Standard laces",
      weight: "Not officially published",
      colours: "Multiple",
      sizes: "UK 6–11",
      bestFor: "Weekend trails, city + light outdoor mixed use",
      warranty: "Not officially published (Flipkart 30-day replacement)",
      rating: "4.1★ (Flipkart)",
      madeIn: "India",
    },
    buyUrl: "https://www.flipkart.com/search?q=wildcraft%20volga%20nx",
    buyStore: "Flipkart",
  },
  {
    id: "redtape-ozark-high",
    brand: "Red Tape (Ozark)",
    model: "Ozark High-Top Hiking & Trekking Shoes",
    price: 1925,
    upper: "Synthetic leather (closed)",
    sealing: "Closed leather-look upper, splash-resistant",
    ankle: "High top",
    outsole: "TPR + EVA",
    highlight: "The looks pick — boot-style styling that doubles as streetwear, with a fully closed synthetic-leather upper that seals out sand.",
    pros: [
      "Best-looking budget trek boot (styles like a fashion boot)",
      "Fully closed upper — no mesh anywhere",
      "High top keeps debris out",
      "Deep Flipkart discounts (~70–80% off inflated MRP)",
    ],
    cons: [
      "TPR sole grips less than rubber on wet rock",
      "Runs hot; synthetic leather doesn't breathe",
      "Inflated MRP (₹11,299) is a marketing gimmick",
    ],
    scores: { sealing: 8.0, grip: 6.5, comfort: 7.0, build: 7.0, looks: 9.0, value: 7.5 },
    fullSpec: {
      upperMaterial: "Synthetic leather, fully closed",
      waterproofing: "Splash-resistant closed upper; no membrane",
      dustSealing: "Very good — no mesh, high collar",
      ankleHeight: "High top",
      outsole: "TPR outsole",
      midsole: "EVA",
      insole: "Cushioned footbed",
      toeProtection: "Round-toe reinforced cap",
      closure: "Standard laces",
      weight: "Not officially published (reviewers note it is heavy)",
      colours: "Grey, Brown, Black",
      sizes: "UK 6–11",
      bestFor: "Looks-first buyers, dry rough terrain, casual wear",
      warranty: "Not officially published (Flipkart 30-day replacement)",
      rating: "4.2★ (Flipkart)",
      madeIn: "India",
    },
    buyUrl: "https://www.flipkart.com/hi/red-tape-ozark-high-top-outdoor-hiking-trekking-shoes-men/p/itmf2c042d516bcc",
    buyStore: "Flipkart",
  },
  {
    id: "redtape-ozark-low",
    brand: "Red Tape (Ozark)",
    model: "Ozark Low-Cut Hiking & Trekking Shoes",
    price: 1587,
    upper: "Synthetic leather (closed)",
    sealing: "Closed upper, splash-resistant",
    ankle: "Low cut",
    outsole: "TPR + EVA",
    highlight: "Same closed-upper Ozark styling in a lighter low-cut — the budget looks pick.",
    pros: [
      "Closed non-mesh upper under ₹1,600",
      "Lighter than the high-top",
      "Sharp styling",
    ],
    cons: [
      "Low cut lets in debris on scree",
      "TPR sole is average on wet surfaces",
    ],
    scores: { sealing: 7.0, grip: 6.5, comfort: 7.0, build: 6.5, looks: 8.5, value: 8.0 },
    fullSpec: {
      upperMaterial: "Synthetic leather, fully closed",
      waterproofing: "Splash-resistant closed upper; no membrane",
      dustSealing: "Good — no mesh (low collar though)",
      ankleHeight: "Low cut",
      outsole: "TPR outsole",
      midsole: "EVA",
      insole: "Cushioned footbed",
      toeProtection: "Reinforced toe",
      closure: "Standard laces",
      weight: "Not officially published",
      colours: "Light grey, Brown, Black",
      sizes: "UK 6–11",
      bestFor: "Light trails + daily wear crossover",
      warranty: "Not officially published (Flipkart 30-day replacement)",
      rating: "4.2★ (Flipkart)",
      madeIn: "India",
    },
    buyUrl: "https://www.flipkart.com/red-tape-ozark-low-cut-outdoor-hiking-trekking-shoes-men/p/itmb2beb691afa6d",
    buyStore: "Flipkart",
  },
  {
    id: "bacca-discovery-trek",
    brand: "Bacca Bucci",
    model: "Discovery Trek 0.1",
    price: 1999,
    upper: "Synthetic leather + textile (closed)",
    sealing: "Water-resistant closed upper",
    ankle: "Mid/high ankle",
    outsole: "Rubber, aggressive lugs",
    highlight: "Bacca Bucci's flagship budget trekker — 'terrain ready' aggressive-lug outsole with a closed water-resistant upper and strong styling.",
    pros: [
      "Aggressive lug pattern for loose terrain",
      "Closed upper, good dust sealing",
      "Streetwear-grade looks (BB's design strength)",
      "60% off MRP ₹4,999 on brand site",
    ],
    cons: [
      "D2C brand — service via returns portal only",
      "Durability beyond 1–2 seasons unproven",
    ],
    scores: { sealing: 7.5, grip: 8.0, comfort: 7.5, build: 7.0, looks: 8.5, value: 8.0 },
    fullSpec: {
      upperMaterial: "Synthetic leather + closed textile",
      waterproofing: "Water-resistant; no membrane",
      dustSealing: "Good — closed upper + padded collar",
      ankleHeight: "Mid/high ankle",
      outsole: "Rubber, aggressive multi-directional lugs",
      midsole: "EVA/Phylon",
      insole: "Memory-foam footbed",
      toeProtection: "Rubber toe guard",
      closure: "Standard laces, speed hooks",
      weight: "Not officially published",
      colours: "Brown, Black, Olive",
      sizes: "UK 6–13",
      bestFor: "Mixed terrain treks + style-conscious buyers",
      warranty: "Not officially published (7-day return/exchange)",
      rating: "4.0★ (brand site)",
      madeIn: "India",
    },
    buyUrl: "https://baccabucci.com/collections/boots-for-men",
    buyStore: "baccabucci.com",
  },
  {
    id: "bacca-evertrek",
    brand: "Bacca Bucci",
    model: "EverTrek",
    price: 1699,
    upper: "Synthetic (closed)",
    sealing: "Water-resistant closed upper",
    ankle: "Mid ankle",
    outsole: "Rubber lugs",
    highlight: "Cheaper BB trekking boot with the same closed-upper formula — solid value at ₹1,699.",
    pros: [
      "Closed upper at a budget price",
      "Good-looking boot silhouette",
      "58% off MRP ₹3,999",
    ],
    cons: [
      "Less aggressive outsole than Discovery Trek",
      "Unproven long-term durability",
    ],
    scores: { sealing: 7.0, grip: 7.0, comfort: 7.0, build: 6.5, looks: 8.0, value: 8.0 },
    fullSpec: {
      upperMaterial: "Closed synthetic upper",
      waterproofing: "Water-resistant; no membrane",
      dustSealing: "Good — closed upper",
      ankleHeight: "Mid ankle",
      outsole: "Rubber, moderate lugs",
      midsole: "EVA/Phylon",
      insole: "Cushioned footbed",
      toeProtection: "Toe bumper",
      closure: "Standard laces",
      weight: "Not officially published",
      colours: "Brown, Black",
      sizes: "UK 6–13",
      bestFor: "Weekend treks, travel",
      warranty: "Not officially published (7-day return/exchange)",
      rating: "4.0★ (brand site)",
      madeIn: "India",
    },
    buyUrl: "https://baccabucci.com/collections/boots-for-men",
    buyStore: "baccabucci.com",
  },
  {
    id: "bacca-hunter",
    brand: "Bacca Bucci",
    model: "Hunter 6-inch Outdoor Hiking Boots",
    price: 1699,
    upper: "Synthetic leather (closed)",
    sealing: "Water-resistant, 6-inch shaft",
    ankle: "High (6-inch shaft)",
    outsole: "Rubber",
    highlight: "6-inch shaft gives the most debris protection here — a favourite in budget-trek Reddit threads.",
    pros: [
      "Tall 6-inch shaft seals out sand, scree and splash",
      "Reddit/YouTube budget-trek favourite",
      "Rugged work-boot looks",
    ],
    cons: [
      "Heavy for long walking days",
      "Warm in summer",
    ],
    scores: { sealing: 8.5, grip: 7.0, comfort: 6.5, build: 7.0, looks: 8.0, value: 8.0 },
    fullSpec: {
      upperMaterial: "Synthetic leather, fully closed",
      waterproofing: "Water-resistant; no membrane",
      dustSealing: "Excellent — 6-inch closed shaft",
      ankleHeight: "High (6-inch)",
      outsole: "Rubber outsole",
      midsole: "EVA",
      insole: "Cushioned footbed",
      toeProtection: "Reinforced toe",
      closure: "Laces with speed hooks",
      weight: "Not officially published (heavy build)",
      colours: "Brown, Black, Tan",
      sizes: "UK 6–13",
      bestFor: "Rough dusty terrain, winter, style crossover",
      warranty: "Not officially published (7-day return/exchange)",
      rating: "4.1★ (Amazon, cross-checked)",
      madeIn: "India",
    },
    buyUrl: "https://baccabucci.com/collections/boots-for-men",
    buyStore: "baccabucci.com",
  },
  {
    id: "bacca-sprite",
    brand: "Bacca Bucci",
    model: "Sprite Snow Boots",
    price: 1599,
    upper: "Synthetic + fleece lining (closed)",
    sealing: "Water-resistant shell, snow-oriented",
    ankle: "Mid/high ankle",
    outsole: "Rubber",
    highlight: "Snow-oriented budget boot recommended in r/SoloTravel_India for waterproof needs at ~₹1.5k.",
    pros: [
      "Best splash/snow sealing under ₹1,600",
      "Warm fleece lining for winter treks",
      "Reddit-recommended budget waterproof pick",
    ],
    cons: [
      "Too warm for summer plains",
      "Casual snow-boot grip, not trek lugs",
    ],
    scores: { sealing: 8.0, grip: 6.0, comfort: 7.0, build: 6.5, looks: 7.0, value: 8.5 },
    fullSpec: {
      upperMaterial: "Closed synthetic shell + fleece lining",
      waterproofing: "Water-resistant shell (marketed as snow boot)",
      dustSealing: "Very good — sealed closed shell",
      ankleHeight: "Mid/high ankle",
      outsole: "Rubber outsole",
      midsole: "EVA",
      insole: "Warm lined footbed",
      toeProtection: "Toe bumper",
      closure: "Standard laces",
      weight: "Not officially published",
      colours: "Black, Brown",
      sizes: "UK 6–12",
      bestFor: "Winter/snow trips, cold dusty terrain",
      warranty: "Not officially published (7-day return/exchange)",
      rating: "4.0★ (Amazon, cross-checked)",
      madeIn: "India",
    },
    buyUrl: "https://baccabucci.com/collections/boots-for-men",
    buyStore: "baccabucci.com",
  },
  {
    id: "asian-everest22",
    brand: "ASIAN",
    model: "Everest-22 Hi-Neck Trekking Shoes",
    price: 1399,
    upper: "Synthetic + some mesh",
    sealing: "Marketed water-resistant; partial mesh",
    ankle: "Hi-neck (mid)",
    outsole: "Rubber",
    highlight: "India's best-selling budget trekker — memory-foam comfort and hi-neck support at ₹1,399, but the upper has mesh zones.",
    pros: [
      "Memory-foam insole, comfortable straight away",
      "Rubber outsole with real lugs at this price",
      "Huge sales volume; easy availability everywhere",
    ],
    cons: [
      "Mesh zones admit dust — partial fail on your requirement",
      "Water 'resistance' is marketing-grade only",
      "No stated warranty",
    ],
    scores: { sealing: 5.5, grip: 7.0, comfort: 7.5, build: 6.0, looks: 7.0, value: 9.0 },
    fullSpec: {
      upperMaterial: "Synthetic with mesh panels",
      waterproofing: "Claimed water-resistant (no membrane)",
      dustSealing: "Partial — mesh zones admit fine dust",
      ankleHeight: "Hi-neck (mid ankle)",
      outsole: "Rubber, aggressive tread",
      midsole: "High-cushion EVA",
      insole: "Memory-foam footbed",
      toeProtection: "Toe bumper",
      closure: "Standard laces",
      weight: "Not officially published",
      colours: "Dark grey, Black, Olive",
      sizes: "UK 6–11",
      bestFor: "Budget buyers, dry easy treks",
      warranty: "Not officially published",
      rating: "4.0★ (Amazon, ~830 ratings via price tracker)",
      madeIn: "India",
    },
    buyUrl: "https://www.amazon.in/ASIAN-Everest-22-Trekking-Walking-Hi-Neck/dp/B0CMCL7Y7Y",
    buyStore: "Amazon.in",
  },
  {
    id: "unistar-jungle-7100",
    brand: "Unistar",
    model: "Jungle Boots 7100",
    price: 1499,
    upper: "Canvas/synthetic, fully closed",
    sealing: "Closed canvas shaft (not waterproof but sand-proof)",
    ankle: "High (jungle-boot shaft)",
    outsole: "Direct-vulcanised rubber",
    highlight: "Army-pattern jungle boot — the toughest debris sealing here; used by forest staff and hunters, though heavy and utilitarian-looking.",
    pros: [
      "Tall closed shaft: nothing gets in",
      "Vulcanised rubber sole is near-indestructible",
      "Trusted by forest/paramilitary users",
    ],
    cons: [
      "Utilitarian looks",
      "Heavy; canvas soaks water if submerged",
      "Basic cushioning",
    ],
    scores: { sealing: 9.0, grip: 7.5, comfort: 5.5, build: 8.0, looks: 5.0, value: 8.5 },
    fullSpec: {
      upperMaterial: "Heavy canvas + synthetic, fully closed",
      waterproofing: "None (canvas absorbs if submerged)",
      dustSealing: "Excellent — tall sealed shaft",
      ankleHeight: "High (jungle shaft)",
      outsole: "Direct-vulcanised rubber",
      midsole: "Rubber/EVA",
      insole: "Basic footbed",
      toeProtection: "Rubber toe cap",
      closure: "Laces, full-length",
      weight: "Not officially published (heavy)",
      colours: "Olive green, Black",
      sizes: "UK 5–11",
      bestFor: "Jungle/dusty trails, thorny scrub, abuse",
      warranty: "Not officially published",
      rating: "4.1★ (brand site)",
      madeIn: "India",
    },
    buyUrl: "https://buyunistar.com/collections/trekking-boots",
    buyStore: "buyunistar.com",
  },
  {
    id: "campus-trek-pro",
    brand: "Campus",
    model: "Trek (trekking/outdoor line)",
    price: 2399,
    upper: "Synthetic + mesh",
    sealing: "Partial — mesh zones",
    ankle: "Low/mid",
    outsole: "Phylon/rubber",
    highlight: "Ultra-light hiking sneaker from Campus — great comfort for day hikes, but a meshy upper that won't keep sand out.",
    pros: [
      "Very light — easy on long day hikes",
      "Wide availability and Campus's scale",
      "Comfortable Phylon cushioning",
    ],
    cons: [
      "Mesh upper — fails your dust requirement",
      "Not water-resistant",
      "Sneaker-grade ankle support",
    ],
    scores: { sealing: 4.5, grip: 6.5, comfort: 8.0, build: 6.5, looks: 7.0, value: 7.5 },
    fullSpec: {
      upperMaterial: "Synthetic + breathable mesh",
      waterproofing: "None",
      dustSealing: "Poor — open mesh zones",
      ankleHeight: "Low/mid",
      outsole: "Rubberised Phylon",
      midsole: "Phylon (ultra-light)",
      insole: "Memory-foam footbed",
      toeProtection: "Minimal",
      closure: "Standard laces",
      weight: "Not officially published (marketed ultra-light)",
      colours: "Multiple",
      sizes: "UK 6–11",
      bestFor: "Casual day hikes, gym/trail crossover",
      warranty: "90-day manufacturing warranty (Campus standard)",
      rating: "4.0★ (Amazon, cross-checked)",
      madeIn: "India",
    },
    buyUrl: "https://www.amazon.in/Campus-Mens-Trek-Running-Sport/dp/B09RBQ3RRK",
    buyStore: "Amazon.in",
  },
  {
    id: "action-trekking",
    brand: "Action",
    model: "Trekking Boot (synthetic hiking line)",
    price: 1999,
    upper: "Synthetic leather (closed)",
    sealing: "Closed upper, survives light showers",
    ankle: "High ankle available",
    outsole: "Dual-grip PVC/rubber",
    highlight: "Old-school Indian trekker used by 20% of Indiahikes' surveyed budget trekkers — closed synthetic upper, best bought offline.",
    pros: [
      "Closed synthetic upper handles light rain",
      "Proven by Sahyadri trekkers for years",
      "High-ankle variant available",
    ],
    cons: [
      "Gets heavy when wet, slow to dry",
      "Hard to find the right model online",
      "Dated styling",
    ],
    scores: { sealing: 7.0, grip: 7.0, comfort: 6.5, build: 7.0, looks: 5.5, value: 8.5 },
    fullSpec: {
      upperMaterial: "Synthetic leather, closed",
      waterproofing: "Survives light showers; no membrane",
      dustSealing: "Good — closed upper",
      ankleHeight: "Low and high-ankle variants",
      outsole: "Dual-grip PVC/rubber",
      midsole: "EVA",
      insole: "Basic footbed",
      toeProtection: "Toe cap",
      closure: "Standard laces",
      weight: "Not officially published (heavy when wet)",
      colours: "Black, Brown, Olive",
      sizes: "UK 6–10",
      bestFor: "Western Ghats treks, rain-prone trails on a budget",
      warranty: "Not officially published",
      rating: "Trekker-recommended (Indiahikes survey); no aggregate online rating",
      madeIn: "India",
    },
    buyUrl: "https://www.flipkart.com/mens-footwear/sports-shoes/hiking-trekking-shoes~type/pr?sid=osp,cil,1cu",
    buyStore: "Flipkart",
  },
  {
    id: "souled-urban-blaze",
    brand: "The Souled Store",
    model: "Urban Blaze Low-Top Sneakers",
    price: 2599,
    upper: "Canvas/synthetic sneaker upper",
    sealing: "Not designed for dust/water sealing",
    ankle: "Low top",
    outsole: "Flat rubber cupsole",
    highlight: "Included on your request — great-looking street sneaker, but it is NOT a trekking shoe: flat sole, low top, no sealing.",
    pros: [
      "Standout looks and colourways",
      "Comfortable for city wear",
      "Souled Store's design-first branding",
    ],
    cons: [
      "Flat cupsole has no trail grip",
      "Low top + sneaker upper lets sand straight in",
      "No water resistance",
    ],
    scores: { sealing: 3.0, grip: 3.5, comfort: 7.0, build: 6.0, looks: 9.0, value: 6.0 },
    fullSpec: {
      upperMaterial: "Canvas/synthetic sneaker upper",
      waterproofing: "None",
      dustSealing: "Poor — casual sneaker construction",
      ankleHeight: "Low top",
      outsole: "Flat rubber cupsole (no lugs)",
      midsole: "EVA",
      insole: "Cushioned footbed",
      toeProtection: "None",
      closure: "Standard laces",
      weight: "Not officially published",
      colours: "Many graphic colourways",
      sizes: "UK 6–12",
      bestFor: "City wear, cafe-to-campsite style (not the trail)",
      warranty: "Not officially published (15-day return/exchange)",
      rating: "Not published on brand site",
      madeIn: "India",
    },
    buyUrl: "https://www.thesouledstore.com/men-footwear",
    buyStore: "The Souled Store",
  },
  {
    id: "souled-ubz-mid",
    brand: "The Souled Store",
    model: "UBZ Mid-Top Sneakers",
    price: 2599,
    upper: "Synthetic/canvas mid-top",
    sealing: "Not designed for dust/water sealing",
    ankle: "Mid top",
    outsole: "Flat rubber cupsole",
    highlight: "Souled Store's mid-top — slightly better debris coverage than the low-top, still a fashion sneaker, not trail gear.",
    pros: [
      "Mid collar covers the ankle bone",
      "Distinctive looks",
      "Comfortable casual fit",
    ],
    cons: [
      "No trail grip or toe protection",
      "Sneaker upper admits dust",
      "No water resistance",
    ],
    scores: { sealing: 3.5, grip: 3.5, comfort: 7.0, build: 6.0, looks: 8.5, value: 6.0 },
    fullSpec: {
      upperMaterial: "Synthetic/canvas mid-top sneaker upper",
      waterproofing: "None",
      dustSealing: "Poor — casual sneaker construction",
      ankleHeight: "Mid top",
      outsole: "Flat rubber cupsole (no lugs)",
      midsole: "EVA",
      insole: "Cushioned footbed",
      toeProtection: "None",
      closure: "Standard laces",
      weight: "Not officially published",
      colours: "Multiple colourways",
      sizes: "UK 6–12",
      bestFor: "Casual wear with outdoorsy styling",
      warranty: "Not officially published (15-day return/exchange)",
      rating: "Not published on brand site",
      madeIn: "India",
    },
    buyUrl: "https://www.thesouledstore.com/men-footwear",
    buyStore: "The Souled Store",
  },
];
