// Global routine styles, named methods, and occasion routines — same rules as
// data.js: every entry transcribed from a real published guide read live in the
// browser on 14 Aug 2026. Nothing invented.
const MORE_ROUTINES = [
  {
    id: "kbeauty-10step",
    category: "global",
    brand: "K-Beauty (Korea)",
    model: "10-Step Korean Routine \u2014 the full glass-skin framework",
    source: "KoreaPeek 'Korean Skincare Routine: 10-Step Guide' + Healthline layering order",
    sourceUrl: "https://koreapeek.com/korean-skincare-routine-10-step-guide/",
    sourceUrl2: "https://www.healthline.com/health/beauty-skin-care/order-of-skin-care",
    author: "K-beauty editorial (Seoul-based); layering order corroborated by Healthline (medically reviewed)",
    timePerDay: "15\u201325 min",
    stepsPerDay: 10,
    highlight: "The famous framework: oil cleanse \u2192 foam cleanse \u2192 exfoliate (2\u20133\u00d7/wk) \u2192 toner \u2192 serum/ampoule \u2192 sheet mask (2\u20133\u00d7/wk) \u2192 light AM / rich PM moisturizer \u2192 eye care \u2192 SPF. The source itself is honest: most Koreans run 5\u20136 of the 10 daily \u2014 it's a menu of purposes, not a law.",
    steps: {
      morning: [
        { name: "Foam cleanse", phase: "CLEANSE", how: "Gentle, low-pH foaming wash \u2014 Korean cleansers prioritize non-stripping formulas." },
        { name: "Toner / essence", phase: "PREP", how: "Pat on a hydrating toner or essence to rebalance and prep skin to absorb treatments. Twice daily." },
        { name: "Serum / ampoule", phase: "TREAT", how: "Concern-targeted serum (hydration, brightening, texture). Daily or as needed." },
        { name: "Light moisturizer", phase: "SEAL", how: "Lotion or gel texture for daytime." },
        { name: "Eye care", phase: "SEAL", how: "Eye cream or patch, daily." },
        { name: "Sunscreen SPF 30+", phase: "PROTECT", how: "The essential morning step \u2014 prevention is the whole philosophy." },
      ],
      evening: [
        { name: "Oil / balm cleanse", phase: "CLEANSE", how: "PM only: massage an oil or balm cleanser 30\u201360 s to dissolve sunscreen, sebum and grime ('like dissolves like'), emulsify with water, rinse. Optional if you wore neither makeup nor SPF." },
        { name: "Foam cleanse (second cleanse)", phase: "CLEANSE", how: "Gentle low-pH foam removes remaining residue without stripping." },
        { name: "Toner / essence", phase: "PREP", how: "Second application of the hydration core." },
        { name: "Serum / ampoule", phase: "TREAT", how: "Evening treatment layer." },
        { name: "Rich moisturizer", phase: "SEAL", how: "Cream or balm texture at night to seal everything in." },
      ],
      weekly: [
        { name: "Exfoliate 2\u20133\u00d7/week", phase: "TREAT", how: "Physical or (preferably gentle) chemical exfoliation \u2014 never daily." },
        { name: "Sheet mask 2\u20133\u00d7/week", phase: "TREAT", how: "15\u201320-minute hydrating sheet mask as a boost, not a daily requirement." },
      ],
    },
    pros: [
      "The most complete layering menu \u2014 covers every skincare purpose",
      "Source honestly states the 'real version': ~5\u20136 steps daily, 10 is the menu",
      "Hydration-and-prevention philosophy, not correction",
    ],
    cons: [
      "Editorial/travel-guide source, not dermatologist-authored",
      "Full 10 steps daily is slow, expensive and unnecessary by the source's own admission",
    ],
    scores: { evidence: 5.5, coverage: 9.5, adherence: 4.0, fit: 8.0, time: 3.5 },
    fullSpec: {
      am: "Foam cleanse \u00b7 toner \u00b7 serum \u00b7 light moisturizer \u00b7 eye \u00b7 SPF",
      pm: "Oil cleanse \u00b7 foam cleanse \u00b7 toner \u00b7 serum \u00b7 rich moisturizer",
      weekly: "Exfoliation 2\u20133\u00d7/wk \u00b7 sheet mask 2\u20133\u00d7/wk",
      exfoliation: "2\u20133\u00d7/week, step 3 of 10",
      activeIngredients: "Serums/ampoules by concern; essence; sheet-mask boosters",
      spf: "SPF 30+ every morning (step 10)",
      skinTypes: "All \u2014 pick the steps your skin needs",
      complexity: "Up to 10 steps + 2 weekly boosts",
      timeCost: "15\u201325 min/day in full",
      cautions: "Don't run all 10 daily; exfoliation stays 2\u20133\u00d7/week",
      authorType: "K-beauty editorial guide (Seoul)",
      costTier: "High \u2014 6\u201310 products",
    },
  },
  {
    id: "jbeauty-7step",
    category: "global",
    brand: "J-Beauty (Japan)",
    model: "7-Step Japanese Layering (kasanezuke) \u2014 water before oil",
    source: "J-Beauty Decoded 'How to Layer J-Beauty Skincare: The 7-Step Japanese Routine'",
    sourceUrl: "https://jbeautydecoded.com/7-step-japanese-skincare-routine-decoded",
    author: "Tokyo cosmetic-chemist editorial, translating @cosme / Biteki guides",
    timePerDay: "10\u201315 min",
    stepsPerDay: 7,
    highlight: "Japan's answer to the 10-step: oil cleanse \u2192 foam cleanse \u2192 keshousui (watery lotion) \u2192 essence \u2192 milky emulsion \u2192 cream \u2192 SPF (AM). The cardinal rule of jyunban (order): water before oil, thinnest to richest \u2014 each layer hydrates, the next seals. Philosophy: yobou biyou, preventive beauty with mild ingredients.",
    steps: {
      morning: [
        { name: "Foam cleanse", phase: "CLEANSE", how: "Gentle sengan (foam wash)." },
        { name: "Keshousui lotion", phase: "PREP", how: "Watery hydrating toner patted in \u2014 in Japan it comes FIRST after cleansing, never last. The hydration base for everything above it." },
        { name: "Essence (biyoueki)", phase: "TREAT", how: "Light-gel concentrated treatment layer." },
        { name: "Emulsion (nyuueki)", phase: "SEAL", how: "Milky lotion \u2014 lighter than cream; partially seals hydration while adding lipids." },
        { name: "Sunscreen", phase: "PROTECT", how: "AM only; Japanese formulas set the global standard for daily-wear SPF." },
      ],
      evening: [
        { name: "Oil cleanse (kurenjingu)", phase: "CLEANSE", how: "Oil first cleanse to dissolve SPF and sebum \u2014 daburu sengan (double cleanse) is standard practice." },
        { name: "Foam cleanse", phase: "CLEANSE", how: "Second, water-based cleanse." },
        { name: "Keshousui lotion", phase: "PREP", how: "Watery hydration layer first." },
        { name: "Essence", phase: "TREAT", how: "Treatment layer." },
        { name: "Emulsion, then cream", phase: "SEAL", how: "Milky emulsion, finished with a rich cream to fully seal the night layers (cream is skippable for oily skin)." },
      ],
      weekly: [],
    },
    pros: [
      "Clear, teachable layering logic: thinnest \u2192 richest, water before oil",
      "Prevention-over-correction philosophy \u2014 mild ingredients, low irritation",
      "Fewer steps than K-beauty with near-identical coverage",
    ],
    cons: [
      "Editorial/affiliate source, not dermatologist-authored",
      "Emulsion + cream double-seal is excessive for oily skin (source says skip cream)",
    ],
    scores: { evidence: 5.5, coverage: 9.0, adherence: 5.5, fit: 8.0, time: 5.0 },
    fullSpec: {
      am: "Foam cleanse \u00b7 lotion \u00b7 essence \u00b7 emulsion \u00b7 SPF",
      pm: "Oil cleanse \u00b7 foam cleanse \u00b7 lotion \u00b7 essence \u00b7 emulsion \u00b7 cream",
      weekly: "\u2014",
      exfoliation: "Not a core step \u2014 mildness is the philosophy",
      activeIngredients: "Essence/serum layer; otherwise humectants and lipids",
      spf: "Daily AM (step 7)",
      skinTypes: "All \u2014 oily skin skips the cream layer",
      complexity: "7 steps/day",
      timeCost: "10\u201315 min/day",
      cautions: "Order matters most: water-based before oil-based, always",
      authorType: "Tokyo cosmetic-chemist editorial (translated Japanese sources)",
      costTier: "Mid-high \u2014 5\u20137 products",
    },
  },
  {
    id: "french-pharmacy",
    category: "global",
    brand: "French Pharmacy (France)",
    model: "French Girl Minimalism \u2014 gentle daily 5, weekly ritual",
    source: "French Girl Beauty 'The French Skincare Routine'",
    sourceUrl: "https://frenchgirlbeauty.com/skincare-routine/",
    author: "French beauty editorial",
    timePerDay: "6\u20138 min",
    stepsPerDay: 5,
    highlight: "Less-is-more, decades-long consistency: micellar-water cleanse \u2192 gentle toner \u2192 targeted serum \u2192 cream \u2192 SPF, with exfoliation and a mask saved for a weekly ritual. Avoids harsh scrubs, soaps and alcohol; massage over aggression; prevention started early and kept for life.",
    steps: {
      morning: [
        { name: "Micellar / gentle cleanse", phase: "CLEANSE", how: "Micellar water on a cotton pad (or a gentle cleanser) \u2014 removes grime without stripping natural moisture." },
        { name: "Toner", phase: "PREP", how: "Gentle, skin-type-matched toner patted onto face and neck to rebalance pH." },
        { name: "Serum", phase: "TREAT", how: "One concentrated serum for your main concern (lines, spots, dehydration), massaged in." },
        { name: "Face cream", phase: "SEAL", how: "Hydrating cream in upward strokes on face and neck." },
        { name: "Sunscreen", phase: "PROTECT", how: "Non-negotiable \u2014 generously on face and neck, even cloudy days and winter." },
      ],
      evening: [
        { name: "Cleanse + repeat layers", phase: "CLEANSE", how: "Same gentle cleanse; toner, serum and cream repeat at night without SPF." },
      ],
      weekly: [
        { name: "Gentle exfoliation (weekly)", phase: "TREAT", how: "Fine, gentle exfoliant on damp skin in circular motions, once a week \u2014 never harsh scrubs." },
        { name: "Face mask (weekly)", phase: "TREAT", how: "15-minute targeted mask on clean skin; massage the residue in afterwards." },
      ],
    },
    pros: [
      "Sustainable philosophy: gentle, consistent, started early, kept for decades",
      "Explicitly avoids harsh scrubs, stripping soaps and alcohol",
      "Weekly-ritual structure keeps the daily routine fast",
    ],
    cons: [
      "Beauty-editorial source with product placement, not derm-authored",
      "Micellar-only cleansing can under-clean after sweat or heavy sunscreen",
    ],
    scores: { evidence: 5.0, coverage: 7.5, adherence: 7.5, fit: 7.5, time: 7.0 },
    fullSpec: {
      am: "Micellar cleanse \u00b7 toner \u00b7 serum \u00b7 cream \u00b7 SPF",
      pm: "Cleanse \u00b7 toner \u00b7 serum \u00b7 cream",
      weekly: "Gentle exfoliation 1\u00d7/wk \u00b7 mask 1\u00d7/wk",
      exfoliation: "Weekly, gentle only",
      activeIngredients: "One targeted serum; otherwise gentle basics",
      spf: "Daily, all seasons",
      skinTypes: "All \u2014 especially sensitive/normal",
      complexity: "5 steps/day + 2 weekly",
      timeCost: "6\u20138 min/day",
      cautions: "No harsh scrubs, soaps or alcohol-based products",
      authorType: "French beauty editorial",
      costTier: "Mid \u2014 pharmacy staples",
    },
  },
  {
    id: "ayurveda-dinacharya",
    category: "global",
    brand: "Ayurveda (India)",
    model: "Dinacharya Skin Ritual \u2014 the classical daily sequence",
    source: "Art of Vedas 'Dinacharya: The Complete Ayurvedic Daily Routine' (Ashtanga Hridayam / Charaka Samhita)",
    sourceUrl: "https://artofvedas.com/pages/dinacharya-complete-daily-routine",
    author: "Classical Ayurvedic texts, compiled by an Ayurveda retailer \u2014 traditional, not clinical, evidence",
    timePerDay: "20\u201330 min",
    stepsPerDay: 7,
    highlight: "India's classical daily ritual, skin-relevant core: wake before sunrise (Brahma Muhurta), tongue scraping, oil pulling, Abhyanga full-body warm-oil self-massage before bathing, gentle herbal cleansing \u2014 alignment with natural rhythms over product-stacking. Included as a cultural tradition: its claims are classical, not clinically verified.",
    steps: {
      morning: [
        { name: "Wake at Brahma Muhurta", phase: "CARE", how: "~90 minutes before sunrise; classical texts link the pre-dawn window to clarity and stable daily rhythm." },
        { name: "Tongue scraping (Jihwa Nirlekhana)", phase: "CLEANSE", how: "First physical act after rising: scrape the overnight coating (Ama) off the tongue \u2014 copper is the classical material." },
        { name: "Oil pulling / mouth rinse", phase: "CLEANSE", how: "Swish warm sesame-based oil, then herbal tooth cleaning (neem, Triphala)." },
        { name: "Abhyanga oil massage", phase: "SEAL", how: "Warm oil (sesame base, dosha-matched) massaged over body and face before bathing \u2014 the classical moisturizing and circulation step." },
        { name: "Warm bathe, gentle cleanse", phase: "CLEANSE", how: "Bathe after the oil has absorbed; gentle herbal cleansers (ubtan-style), never harsh soap." },
      ],
      evening: [
        { name: "Early, light evening", phase: "CARE", how: "Early dinner and sleep aligned with sunset rhythms; the texts treat sleep as a core skin-and-health practice." },
      ],
      weekly: [
        { name: "Dosha-specific adjustments", phase: "CARE", how: "Oil choice and frequency adapt to constitution (Vata/Pitta/Kapha) and season \u2014 the system is individualized by design." },
      ],
    },
    pros: [
      "Millennia-old, deeply systematized daily discipline \u2014 the original 'routine'",
      "Abhyanga oil massage is a genuinely strong moisturization practice",
      "Whole-day rhythm (sleep, food, stress) treated as part of skin health",
    ],
    cons: [
      "Classical-text authority, not clinical evidence \u2014 scored accordingly",
      "No SPF concept; a modern sunscreen must be added",
      "Time-heavy morning sequence",
    ],
    scores: { evidence: 4.0, coverage: 6.5, adherence: 4.5, fit: 6.0, time: 3.5 },
    fullSpec: {
      am: "Pre-dawn wake \u00b7 tongue scrape \u00b7 oil pull \u00b7 Abhyanga oil massage \u00b7 warm bathe",
      pm: "Early light evening, sleep-aligned",
      weekly: "Dosha/seasonal adaptation",
      exfoliation: "Herbal ubtan cleansing paste (gentle)",
      activeIngredients: "Sesame-based oils, herbal powders (neem, Triphala)",
      spf: "Not stated in source \u2014 predates SPF; add modern sunscreen",
      skinTypes: "Individualized by dosha",
      complexity: "7 steps/day",
      timeCost: "20\u201330 min/day",
      cautions: "Traditional claims are not clinically verified; patch-test oils",
      authorType: "Classical texts via Ayurveda retailer \u2014 traditional evidence",
      costTier: "Low-mid \u2014 oils and herbal powders",
    },
  },
  {
    id: "skin-cycling",
    category: "method",
    brand: "Skin Cycling (Dr. Whitney Bowe)",
    model: "4-Night Cycle \u2014 exfoliate, retinoid, recover, recover",
    source: "Dr. Whitney Bowe 'Skin Cycling: my viral method' + Skin Science Hub night-by-night guide",
    sourceUrl: "https://drwhitneybowebeauty.com/blogs/derm-scribbles/skin-cycling-dr-bowes-viral-beauty-editor-approved-skincare-method",
    sourceUrl2: "https://skinsciencehub.com/skin-cycling-routine-guide/",
    author: "Dr. Whitney Bowe, MD, board-certified dermatologist (method creator)",
    timePerDay: "5\u20137 min (PM)",
    stepsPerDay: 4,
    highlight: "The dermatologist-invented night schedule that fixes the 'kitchen sink' mistake: Night 1 chemical exfoliation, Night 2 retinoid, Nights 3+4 recovery (hydration + barrier repair only) \u2014 then repeat. Your barrier needs 48\u201372 h to rebuild after actives; the cycle builds that in.",
    steps: {
      morning: [
        { name: "Normal AM baseline", phase: "PROTECT", how: "Cycling is an evening system \u2014 mornings stay gentle cleanse, moisturizer, SPF." },
      ],
      evening: [
        { name: "Night 1: Chemical exfoliation", phase: "TREAT", how: "Chemical exfoliating serum on fully DRY skin (damp skin drives too-deep penetration), wait a few minutes, then moisturize. Salicylic 0.5\u20132% if acne-prone, glycolic 5\u201310% for tone/aging, lactic/PHA if sensitive. No gritty scrubs." },
        { name: "Night 2: Retinoid", phase: "TREAT", how: "Pea-sized amount on dry skin 2\u20133 min after cleansing. New users: start 0.25% retinol, once per 4-night cycle, building frequency only when there's no redness/peeling." },
        { name: "Nights 3+4: Recovery", phase: "SEAL", how: "No acids, no retinoids. Hyaluronic-acid serum to draw water in, ceramide-rich moisturizer to rebuild the barrier; optionally seal night 4 with a face oil/occlusive." },
      ],
      weekly: [
        { name: "Repeat the 4-night cycle", phase: "CARE", how: "Exfoliate \u2192 retinoid \u2192 recover \u2192 recover, repeating. Sensitive skin can run 'gentle cycling' (more recovery nights); tolerant skin can advance." },
      ],
    },
    pros: [
      "Created by a board-certified dermatologist; hugely adopted since",
      "Builds barrier-recovery nights in \u2014 targets the most common actives mistake",
      "Personalizable: gentle or advanced cycles",
    ],
    cons: [
      "Creator's page doubles as a storefront for her product line",
      "Results build over months, not days \u2014 requires patience",
    ],
    scores: { evidence: 8.5, coverage: 8.0, adherence: 7.5, fit: 8.5, time: 7.5 },
    fullSpec: {
      am: "Unchanged gentle AM (cleanse \u00b7 moisturize \u00b7 SPF)",
      pm: "4-night rotation: acid / retinoid / recover / recover",
      weekly: "Cycle repeats every 4 nights",
      exfoliation: "Every 4th night, chemical only, applied to dry skin",
      activeIngredients: "AHA/BHA/PHA night 1; retinoid night 2; HA + ceramides nights 3\u20134",
      spf: "Daily AM \u2014 mandatory alongside retinoid use",
      skinTypes: "All \u2014 explicitly good for sensitive skin via gentle cycling",
      complexity: "1 focused PM step/night + AM baseline",
      timeCost: "5\u20137 min PM",
      cautions: "Never stack acid + retinoid same night; ramp retinoid slowly",
      authorType: "Board-certified dermatologist (method creator)",
      costTier: "Mid \u2014 one acid, one retinoid, one barrier moisturizer",
    },
  },
  {
    id: "slugging",
    category: "method",
    brand: "Slugging (K-beauty via US derms)",
    model: "3-Step Occlusive Night Seal \u2014 barrier repair",
    source: "Remedy 'The Ultimate Guide to Slugging: A Dermatologist's Perspective' (Dr. Muneeb Shah)",
    sourceUrl: "https://remedyskin.com/blogs/skinpedia-advice/a-dermatologist-s-guide-to-slugging",
    author: "Dr. Muneeb Shah, double board-certified dermatologist (cites petrolatum barrier-repair study, JACI 2016)",
    timePerDay: "3\u20134 min (PM)",
    stepsPerDay: 3,
    highlight: "The simplest method on this list: cleanse \u2192 moisturize \u2192 seal the whole face with a petrolatum ointment overnight. Restores the skin barrier by blocking overnight water loss \u2014 backed by a cited peer-reviewed petrolatum study. For dry/normal skin; acne-prone and milia-prone should sit it out.",
    steps: {
      morning: [
        { name: "Rinse off + normal AM", phase: "CLEANSE", how: "Wash the ointment off in the morning; continue your usual AM routine + SPF." },
      ],
      evening: [
        { name: "Cleanse", phase: "CLEANSE", how: "Thorough cleanse with a gentle, fragrance-free cleanser." },
        { name: "Moisturize", phase: "SEAL", how: "Apply a hydrating moisturizer to damp skin." },
        { name: "Slug (occlusive seal)", phase: "SEAL", how: "Thin, even layer of plain petrolatum ointment (Vaseline preferred; Aquaphor carries lanolin-allergy risk) over the moisturizer. That's it." },
      ],
      weekly: [
        { name: "Frequency by need", phase: "CARE", how: "Use on dry-skin nights or a few nights a week in dry seasons \u2014 not a mandate for every night." },
      ],
    },
    pros: [
      "Double board-certified dermatologist author, with a cited peer-reviewed study",
      "Cheapest method possible \u2014 one tub of petrolatum",
      "Excellent for compromised/dry barriers and harsh winters",
    ],
    cons: [
      "Not for acne-prone or milia-prone skin (occlusion traps bacteria)",
      "Never slug over retinol or exfoliating acids \u2014 drives irritation deeper",
      "Pillowcase gets greasy \u2014 practical downside",
    ],
    scores: { evidence: 8.0, coverage: 5.5, adherence: 9.0, fit: 5.5, time: 9.0 },
    fullSpec: {
      am: "Rinse off \u00b7 usual AM + SPF",
      pm: "Cleanse \u00b7 moisturize \u00b7 petrolatum seal",
      weekly: "As-needed frequency (dry nights/seasons)",
      exfoliation: "Explicitly do NOT slug over acids or retinoids",
      activeIngredients: "None \u2014 pure occlusion (petrolatum)",
      spf: "Usual AM SPF (slugging is night-only)",
      skinTypes: "Dry/normal; avoid if acne- or milia-prone",
      complexity: "3 PM steps",
      timeCost: "3\u20134 min PM",
      cautions: "Skip active-ingredient nights; watch for breakouts/milia",
      authorType: "Double board-certified dermatologist, study-cited",
      costTier: "Minimal \u2014 petrolatum + basics",
    },
  },
  {
    id: "seven-skin",
    category: "method",
    brand: "7-Skin Method (Korea)",
    model: "Layered Toner Hydration \u2014 3 to 7 thin layers",
    source: "Care to Beauty 'The Korean 7-Skin Method: How To'",
    sourceUrl: "https://blog.caretobeauty.com/en/korean-7-skin-method-how-to/",
    author: "K-beauty retailer editorial",
    timePerDay: "8\u201312 min",
    stepsPerDay: 5,
    highlight: "One product, many layers: after cleansing, apply 3\u20137 thin layers of a hydrating, alcohol-free toner ('skin' = toner in Korean), letting each absorb before the next, then seal with moisturizer (+ SPF in the AM). Deep hydration from a single bottle \u2014 oily skin needs fewer layers, dry skin more.",
    steps: {
      morning: [
        { name: "Cleanse", phase: "CLEANSE", how: "Standard gentle cleanse (double cleanse optional but recommended at night)." },
        { name: "Toner layers 1\u20137", phase: "PREP", how: "Thin layer of hydrating toner/essence from driest areas outward; wait for full absorption; repeat until skin feels comfortable (3\u20137 layers). Same toner every layer." },
        { name: "Seal + SPF", phase: "PROTECT", how: "Follow with serum or moisturizer to seal, then sunscreen in the morning." },
      ],
      evening: [
        { name: "Cleanse, layer, seal", phase: "PREP", how: "Same layering at night, sealed with your moisturizer." },
      ],
      weekly: [
        { name: "Adapt layer count daily", phase: "CARE", how: "Your skin changes daily \u2014 vary the number of layers with its condition." },
      ],
    },
    pros: [
      "Maximum hydration from one affordable product",
      "Clear do/don't rules: no exfoliating acids, no high-alcohol toners in the layers",
      "Layer count adapts naturally to skin type",
    ],
    cons: [
      "Retailer editorial source with product plugs",
      "Hydration-only \u2014 no treatment, exfoliation or targeted actives",
      "Waiting for each layer to absorb takes real time",
    ],
    scores: { evidence: 5.0, coverage: 5.5, adherence: 6.5, fit: 8.0, time: 6.0 },
    fullSpec: {
      am: "Cleanse \u00b7 3\u20137 toner layers \u00b7 seal \u00b7 SPF",
      pm: "Cleanse \u00b7 3\u20137 toner layers \u00b7 moisturizer",
      weekly: "Layer count varies with skin condition",
      exfoliation: "Explicitly excluded from the layered toner",
      activeIngredients: "None in the layers \u2014 hydrators only (no acids/retinoids/alcohol)",
      spf: "Morning, after sealing",
      skinTypes: "All \u2014 dehydrated skin benefits most; oily uses fewer layers",
      complexity: "5 effective steps/day",
      timeCost: "8\u201312 min/day",
      cautions: "Never layer acid- or alcohol-heavy toners",
      authorType: "K-beauty retailer editorial",
      costTier: "Low \u2014 one hydrating toner + basics",
    },
  },
  {
    id: "double-cleanse",
    category: "method",
    brand: "Double Cleansing (K-beauty standard)",
    model: "Oil-First Two-Step Cleanse \u2014 PM method",
    source: "OneKind 'How to Double Cleanse: A Step-by-Step Guide for Every Skin Type'",
    sourceUrl: "https://onekind.us/blogs/skin-school/how-to-double-cleanse-a-step-by-step-guide-for-every-skin-type",
    author: "Skincare-brand product-development editorial",
    timePerDay: "4\u20135 min (PM)",
    stepsPerDay: 3,
    highlight: "If you wear sunscreen daily (you should), one water-based cleanse often leaves an SPF/sebum film behind. The fix: an oil-based first cleanse dissolves oil-soluble buildup ('oil dissolves oil'), then a gentle water-based cleanse finishes. Evening only \u2014 morning stays a single gentle cleanse.",
    steps: {
      morning: [
        { name: "Single gentle cleanse", phase: "CLEANSE", how: "Morning needs only one gentle water-based cleanse (or water rinse if dry)." },
      ],
      evening: [
        { name: "Oil-based first cleanse", phase: "CLEANSE", how: "Massage a cleansing oil, balm or non-foaming emollient cream onto dry skin ~60 s to dissolve SPF, sebum and grime; emulsify and rinse." },
        { name: "Water-based second cleanse", phase: "CLEANSE", how: "Gentle, low-pH water-based cleanser removes remaining residue; pat dry, continue your normal routine." },
      ],
      weekly: [],
    },
    pros: [
      "Solves a real chemistry problem: water-based cleansers under-remove SPF/silicones",
      "Per-skin-type first-cleanse guidance (oil, balm, or cream)",
      "Slots under any other routine on this list",
    ],
    cons: [
      "Brand editorial source",
      "Unnecessary on days without sunscreen/makeup; overdone it can strip skin",
    ],
    scores: { evidence: 5.5, coverage: 5.0, adherence: 8.5, fit: 8.0, time: 8.5 },
    fullSpec: {
      am: "One gentle cleanse",
      pm: "Oil cleanse \u2192 water-based cleanse",
      weekly: "\u2014",
      exfoliation: "Not part of the method",
      activeIngredients: "None \u2014 a cleansing technique",
      spf: "Not stated in source (it's the thing being removed)",
      skinTypes: "All \u2014 first-cleanse texture picked by type",
      complexity: "3 cleansing steps/day",
      timeCost: "4\u20135 min PM",
      cautions: "PM only; skip when skin is bare all day",
      authorType: "Brand product-development editorial",
      costTier: "Low \u2014 two cleansers",
    },
  },
  {
    id: "skinimalism",
    category: "method",
    brand: "Skinimalism (derm-quoted)",
    model: "3-Product Minimalist Routine + one active max",
    source: "IPSY 'Skinimalism' (Dr. Nkem Ugonabo, MD)",
    sourceUrl: "https://www.ipsy.com/blog/skinimalism-minimalist-skincare-routine",
    author: "Editorial quoting Dr. Nkem Ugonabo, MD, board-certified dermatologist",
    timePerDay: "4\u20135 min",
    stepsPerDay: 5,
    highlight: "The anti-12-step: exactly three core products \u2014 gentle non-foaming cleanser, barrier-safe moisturizer (ceramides/hyaluronic acid), SPF 30+ \u2014 plus at most ONE active for your main concern (vitamin C to brighten, retinol for lines, or niacinamide to calm). Over-layering actives is what breaks skin barriers.",
    steps: {
      morning: [
        { name: "Gentle cleanse", phase: "CLEANSE", how: "Non-foaming, fragrance-free cleanser with lukewarm water." },
        { name: "One active (optional)", phase: "TREAT", how: "Pick a single concern and its single ingredient: vitamin C (brightening), retinol (fine lines \u2014 PM), or niacinamide (calming). Don't mix and match." },
        { name: "Barrier moisturizer", phase: "SEAL", how: "Ceramide/hyaluronic-acid moisturizer \u2014 barrier repair over ingredient-stacking." },
        { name: "SPF 30+", phase: "PROTECT", how: "Sunscreen SPF 30 or higher, every morning." },
      ],
      evening: [
        { name: "Cleanse + moisturize", phase: "CLEANSE", how: "Same gentle cleanse and barrier moisturizer at night (retinol night here if it's your one active)." },
      ],
      weekly: [],
    },
    pros: [
      "Board-certified dermatologist's product list, near-identical to the AAD baseline",
      "One-active rule directly prevents the most common irritation mistake",
      "Cheap, fast, sustainable \u2014 highest realistic adherence of any 'trend'",
    ],
    cons: [
      "Won't tackle multiple concerns simultaneously by design",
      "Editorial wrapper with subscription-box promotion",
    ],
    scores: { evidence: 7.5, coverage: 7.0, adherence: 9.5, fit: 8.5, time: 9.5 },
    fullSpec: {
      am: "Cleanse \u00b7 one active \u00b7 moisturizer \u00b7 SPF 30+",
      pm: "Cleanse \u00b7 moisturizer (\u00b1 the one active)",
      weekly: "\u2014",
      exfoliation: "Not included \u2014 cited as a common over-use trauma",
      activeIngredients: "Exactly one: vitamin C, retinol, OR niacinamide",
      spf: "SPF 30+ daily (one of the three core products)",
      skinTypes: "All \u2014 especially compromised/sensitive barriers",
      complexity: "5 steps/day max",
      timeCost: "4\u20135 min/day",
      cautions: "Resist adding more actives; ceramides + HA for the barrier",
      authorType: "Editorial quoting a board-certified dermatologist",
      costTier: "Low \u2014 three products + one active",
    },
  },
  {
    id: "cc-simple-men",
    category: "core",
    brand: "Cleveland Clinic (Dr. Wu)",
    model: "Simple Men's 3-Step + shave add-ons",
    source: "Cleveland Clinic 'Skin Care for Men'",
    sourceUrl: "https://health.clevelandclinic.org/skin-care-for-men",
    author: "Cleveland Clinic, quoting dermatologist Dr. Wu",
    timePerDay: "4\u20136 min",
    stepsPerDay: 5,
    highlight: "Hospital-grade basics tuned for men: cleanse 2\u00d7 (and after workouts) with warm not hot water \u2192 moisturize on damp skin to lock water in \u2192 SPF every morning. Skin type matters more than sex; fragrance-free everything; alcohol aftershave is out, moisturizer is the better aftershave.",
    steps: {
      morning: [
        { name: "Cleanse (warm, not hot)", phase: "CLEANSE", how: "Gentle pH-balanced cleanser with fingertips, warm water (hot strips oils); pat \u2014 don't rub \u2014 dry. Cream cleanser if dry/sensitive, foaming if oily/combination. Also cleanse right after workouts." },
        { name: "Moisturize on damp skin", phase: "SEAL", how: "While skin is still damp, lock water in with a hyaluronic-acid + ceramide moisturizer to replenish the lipid barrier." },
        { name: "Sunscreen", phase: "PROTECT", how: "Every morning, even cloudy days \u2014 UV accelerates aging, pigmentation and skin cancer risk." },
      ],
      evening: [
        { name: "Cleanse + moisturize again", phase: "CLEANSE", how: "Second round before bed." },
      ],
      weekly: [
        { name: "Shave-day add-ons", phase: "SHAVE", how: "Cleanse first (warm shower softens hair); bland shaving cream or oil; shave WITH the grain; moisturizer as your aftershave \u2014 never alcohol splash. Ingrown-prone: gentle exfoliant 2\u00d7/week; electric razor with guards if irritated." },
      ],
    },
    pros: [
      "Hospital source with a named dermatologist \u2014 top-tier evidence",
      "Fragrance-free and anti-alcohol-aftershave guidance is specific and actionable",
      "Explicit optional upgrade path (antioxidant serum AM, retinol PM)",
    ],
    cons: [
      "No treatment step in the core three (upgrades are optional extras)",
    ],
    scores: { evidence: 9.0, coverage: 7.0, adherence: 9.5, fit: 9.0, time: 9.5 },
    fullSpec: {
      am: "Cleanse \u00b7 moisturize damp \u00b7 SPF",
      pm: "Cleanse \u00b7 moisturize",
      weekly: "Shave protocol \u00b7 exfoliant 2\u00d7/wk if ingrown-prone",
      exfoliation: "Only if ingrown-prone, 2\u00d7/week gentle",
      activeIngredients: "Optional upgrades: antioxidant serum (AM), retinol (PM)",
      spf: "Every morning, all weather",
      skinTypes: "All four types \u2014 cleanser texture picked by type",
      complexity: "5 steps/day",
      timeCost: "4\u20136 min/day",
      cautions: "Fragrance-free only; no alcohol aftershave; warm not hot water",
      authorType: "Hospital (Cleveland Clinic) + named dermatologist",
      costTier: "Low \u2014 three basics",
    },
  },
  {
    id: "mayo-habits",
    category: "core",
    brand: "Mayo Clinic",
    model: "5 Healthy-Skin Habits \u2014 lifestyle-first routine",
    source: "Mayo Clinic 'Skin care: 5 tips for healthy skin'",
    sourceUrl: "https://www.mayoclinic.org/healthy-lifestyle/adult-health/in-depth/skin-care/art-20048237",
    author: "Mayo Clinic staff",
    timePerDay: "3\u20135 min + habits",
    stepsPerDay: 5,
    highlight: "The zoomed-out view: protect from sun (SPF 15+ daily, shade 10am\u20134pm, protective clothing), don't smoke, treat skin gently (\u22645-min warm baths, mild cleansers, shave after bathing with the grain, moisturize your type), eat well, manage stress and sleep. Skin health as lifestyle, not just product order.",
    steps: {
      morning: [
        { name: "Sun protection", phase: "PROTECT", how: "Broad-spectrum SPF 15+ (generous, reapplied ~2-hourly outdoors), shade between 10am\u20134pm, tightly-woven or UPF clothing." },
        { name: "Gentle cleanse", phase: "CLEANSE", how: "Mild cleansers, warm water, baths \u22645 minutes; pat dry, moisturize damp skin if dry." },
        { name: "Moisturize (your type)", phase: "SEAL", how: "Skin-type-matched moisturizer; consider SPF-containing for daytime." },
      ],
      evening: [
        { name: "Gentle night care", phase: "CLEANSE", how: "Second gentle cleanse; moisturize. Shave after bathing, with the grain, with a clean sharp razor and shave cream." },
        { name: "Lifestyle block", phase: "CARE", how: "Don't smoke (collagen/elastin damage + duller skin); eat fruits/vegetables/whole grains/lean protein; hydrate; manage stress and get enough sleep." },
      ],
      weekly: [],
    },
    pros: [
      "Mayo Clinic authority \u2014 as strong as evidence gets in this list",
      "Only routine here that scores smoking, diet, stress and sleep",
      "Nearly free \u2014 mostly habit changes",
    ],
    cons: [
      "SPF 15 floor is lower than the AAD's SPF 30 standard",
      "Not a product-order guide \u2014 pair with any daily structure above",
    ],
    scores: { evidence: 9.5, coverage: 6.0, adherence: 9.0, fit: 9.0, time: 9.0 },
    fullSpec: {
      am: "SPF + shade + clothing \u00b7 gentle cleanse \u00b7 moisturize",
      pm: "Gentle cleanse \u00b7 moisturize \u00b7 lifestyle habits",
      weekly: "\u2014 (habits are continuous)",
      exfoliation: "Not stated in source",
      activeIngredients: "None \u2014 habit-based",
      spf: "SPF 15+ daily (AAD would say 30+), reapplied outdoors",
      skinTypes: "All",
      complexity: "5 steps/day + habits",
      timeCost: "3\u20135 min/day",
      cautions: "Limit bath time; strong soaps and hot water strip skin",
      authorType: "Hospital (Mayo Clinic staff)",
      costTier: "Minimal",
    },
  },
  {
    id: "post-workout",
    category: "occasion",
    brand: "Post-Workout Protocol (derm-quoted)",
    model: "Gym-Day Skin Routine \u2014 before, during, after sweat",
    source: "Healf 'Post-workout skin protocol: dermatologist guide' (Dr. Nora) + AAD sweat guidance",
    sourceUrl: "https://healf.com/blogs/health-journal/post-workout-skin-protocol-dermatologist-guide",
    sourceUrl2: "https://www.aad.org/public/everyday-care/skin-care-basics/care/face-washing-101",
    author: "Editorial quoting dermatologist Dr. Nora; AAD corroborates wash-after-sweat",
    timePerDay: "5\u20137 min (gym days)",
    stepsPerDay: 5,
    highlight: "Sweat + oil + friction is a breakout recipe. Before: strip to lightweight non-comedogenic layers. After: cleanse promptly and gently (no acids/scrubs on sensitized post-gym skin), optional hypochlorous-acid mist to cut bacterial load, then light hydration. AAD agrees: wash after sweating heavily, always.",
    steps: {
      morning: [
        { name: "Pre-workout: go minimal", phase: "PREP", how: "Remove heavy products; lightweight, non-comedogenic hydrating gel only. Mist hypochlorous acid on clean skin and friction zones (jawline, helmet/strap lines) if prone to breakouts." },
        { name: "During: manage friction", phase: "CARE", how: "Long/hot sessions or headgear: quick HOCl mist mid-session; keep towels clean and don't share equipment contact with your face." },
      ],
      evening: [
        { name: "Cleanse promptly after sweat", phase: "CLEANSE", how: "As soon as possible post-workout: gentle gel/ceramide cleanser (salicylic-acid cleanser if acne-prone). Explicitly NO strong exfoliating acids, scrubs or tight-foaming cleansers on sensitized skin." },
        { name: "Calm + hydrate", phase: "SEAL", how: "Optional HOCl mist on warm post-shower skin (face, chest, back if body-acne-prone), then a light non-comedogenic moisturizer." },
      ],
      weekly: [
        { name: "Kit hygiene", phase: "CARE", how: "Wash headwear, helmet pads and towels regularly \u2014 trapped sweat is extra irritating (per the AAD)." },
      ],
    },
    pros: [
      "Fills a real gap for anyone training regularly",
      "Derm-quoted; the wash-after-sweating core is AAD-corroborated",
      "Anti-acid-after-gym warning prevents a common over-treatment mistake",
    ],
    cons: [
      "Wellness-retailer editorial wrapper",
      "HOCl mist is helpful-but-optional \u2014 the cleanse is the real step",
    ],
    scores: { evidence: 6.5, coverage: 6.0, adherence: 8.0, fit: 8.5, time: 8.0 },
    fullSpec: {
      am: "Pre-gym: minimal non-comedogenic layer (\u00b1 HOCl mist)",
      pm: "Prompt gentle cleanse \u00b7 calm \u00b7 light moisturize",
      weekly: "Gear/towel hygiene",
      exfoliation: "Explicitly avoided right after workouts",
      activeIngredients: "Optional hypochlorous acid; SA cleanser if acne-prone",
      spf: "Usual AM SPF (outdoor training: water-resistant, reapplied)",
      skinTypes: "All \u2014 highest value for acne-prone and helmet/headgear users",
      complexity: "5 steps on training days",
      timeCost: "5\u20137 min on gym days",
      cautions: "Skin is sensitized post-sweat \u2014 no acids, scrubs or tight foams",
      authorType: "Editorial quoting a dermatologist + AAD corroboration",
      costTier: "Low \u2014 cleanser (+ optional HOCl mist)",
    },
  },
  {
    id: "flight-routine",
    category: "occasion",
    brand: "Long-Haul Flight Routine",
    model: "Travel-Day Skin Plan \u2014 pre-flight, in-flight, landing",
    source: "Zennora 'The Long-Haul Flight Skincare Routine'",
    sourceUrl: "https://zennora.com/the-long-haul-flight-skincare-routine/",
    author: "Travel-skincare editorial",
    timePerDay: "10\u201315 min (travel days)",
    stepsPerDay: 6,
    highlight: "Cabin humidity is 10\u201320% \u2014 drier than the Sahara (~25%). Plan: 24\u201348 h pre-flight hydration loading (skip retinoids/AHAs, mask + heavy moisturize, hydrate internally), on board cleanse then layer serum + rich moisturizer + lip balm, re-mist mid-flight, SPF in a window seat \u2014 UVA passes through windows and is stronger at altitude.",
    steps: {
      morning: [
        { name: "24\u201348 h before: load hydration", phase: "PREP", how: "Extra water, less alcohol/caffeine; overnight hydrating mask (HA/ceramides/squalane) the night before; skip retinoids and strong acids for 24\u201348 h; moisturize thicker than usual." },
        { name: "Board clean", phase: "CLEANSE", how: "After boarding, remove makeup/grime with micellar water or wipes \u2014 start the flight with clean skin." },
        { name: "Layer up", phase: "SEAL", how: "Hydrating serum (HA/glycerin), then a rich moisturizer \u2014 thicker than your daily one; occlusive lip balm; urea hand cream." },
      ],
      evening: [
        { name: "Mid-flight top-ups", phase: "PREP", how: "Hydrating mist (glycerin/HA, not plain water) and lip balm every few hours; keep drinking water. Skip in-flight sheet masks \u2014 in 10\u201320% humidity a drying mask pulls moisture back OUT (\u226410\u201315 min if you must)." },
        { name: "Window-seat SPF", phase: "PROTECT", how: "UV is stronger at altitude and windows don't block UVA \u2014 wear sunscreen on day flights, especially window seats." },
        { name: "On landing: reset", phase: "CLEANSE", how: "Proper cleanse and normal routine as soon as you're settled; another rich-moisturizer night helps skin rebound." },
      ],
      weekly: [],
    },
    pros: [
      "Concrete physics: cabin humidity numbers and altitude-UVA reasoning",
      "Actionable 24\u201348 h prep window most people skip",
      "Honest anti-tip: in-flight sheet masks can backfire",
    ],
    cons: [
      "Editorial source, no named dermatologist",
      "Only relevant a few days a year for most people",
    ],
    scores: { evidence: 4.5, coverage: 6.5, adherence: 6.5, fit: 7.5, time: 6.0 },
    fullSpec: {
      am: "Pre-flight: hydration load, no actives 24\u201348 h",
      pm: "In-flight: cleanse \u00b7 serum \u00b7 rich moisturizer \u00b7 mist \u00b7 lip balm \u00b7 SPF",
      weekly: "\u2014 (travel days only)",
      exfoliation: "Paused 24\u201348 h pre-flight",
      activeIngredients: "Humectants only (HA, glycerin, squalane, urea for hands)",
      spf: "Yes \u2014 in-flight on day flights (altitude UVA)",
      skinTypes: "All \u2014 dry skin suffers most in-cabin",
      complexity: "6 steps across a travel day",
      timeCost: "10\u201315 min spread over the flight",
      cautions: "No retinoids/AHAs before flying; skip in-flight sheet masks",
      authorType: "Travel-skincare editorial",
      costTier: "Low-mid \u2014 travel minis",
    },
  },
  {
    id: "event-prep",
    category: "occasion",
    brand: "Big-Event Prep (Dr. Heather Rogers)",
    model: "Going-Out / Event Timeline \u2014 months to day-of",
    source: "Doctor Rogers 'How to Prepare Skin Before a Big Event'",
    sourceUrl: "https://www.doctorrogers.com/blogs/blog/how-to-prepare-skin-before-big-event",
    author: "Dr. Heather Rogers, MD, board-certified dermatologist",
    timePerDay: "varies by timeline",
    stepsPerDay: 5,
    highlight: "A dermatologist's golden rule for weddings, interviews and nights out: real skin improvement (collagen, pigment, wrinkles) takes 3\u20136 months \u2014 so start retinoids and procedures months out, and in the final days switch to what works fast without irritation: hydration, de-puffing, circulation. The biggest mistake: aggressive treatments too close to the day.",
    steps: {
      morning: [
        { name: "3\u20136 months out: build", phase: "TREAT", how: "Start the slow movers now \u2014 retinoids, pigment correction, any procedures \u2014 so results land in time and irritation windows pass." },
        { name: "Final weeks: stabilize", phase: "CARE", how: "No new products, no experiments, no aggressive treatments \u2014 last-minute changes cause the breakouts and redness you're trying to avoid." },
      ],
      evening: [
        { name: "Final days: hydrate", phase: "SEAL", how: "Focus shifts to fast, safe wins: consistent hydration layers to plump fine lines and boost glow." },
        { name: "Day-of: de-puff + circulate", phase: "PREP", how: "Reduce puffiness (cool compress, sleep, low salt/alcohol) and boost circulation for brightness \u2014 appearance-level wins with zero irritation risk." },
        { name: "Keep the baseline", phase: "PROTECT", how: "Your normal gentle cleanse + moisturize + SPF continues throughout \u2014 the event plan sits on top, not instead." },
      ],
      weekly: [
        { name: "Timeline discipline", phase: "CARE", how: "Procedures (lasers, peels, injectables) belong months out, never days out \u2014 healing and final results take weeks to months." },
      ],
    },
    pros: [
      "Board-certified dermatologist author writing directly",
      "The timeline framing (months vs days) is the highest-value insight here",
      "Explicit warning list of what NOT to do before an event",
    ],
    cons: [
      "Half the article covers in-clinic procedures beyond home routines",
      "Less prescriptive on exact day-of product steps",
    ],
    scores: { evidence: 8.5, coverage: 6.5, adherence: 7.0, fit: 7.5, time: 7.0 },
    fullSpec: {
      am: "Months out: start actives \u00b7 weeks out: stabilize",
      pm: "Days out: hydrate \u00b7 day-of: de-puff, circulate",
      weekly: "Timeline rules for procedures",
      exfoliation: "Nothing aggressive near the event date",
      activeIngredients: "Retinoids/pigment correctors \u2014 started months early only",
      spf: "Daily baseline continues throughout",
      skinTypes: "All",
      complexity: "Timeline plan over months \u2192 day-of",
      timeCost: "Normal daily time; planning is the work",
      cautions: "No new products or procedures close to the event",
      authorType: "Board-certified dermatologist (direct author)",
      costTier: "Low at home; procedures optional and costly",
    },
  },
];
ROUTINES.push(...MORE_ROUTINES);
