const BLENDERS = [
  {
    id: "instacuppa-4000",
    name: "InstaCuppa Portable Blender (4000mAh Edition)",
    brand: "InstaCuppa",
    price: 2799,
    capacityMl: 500,
    motorWatts: 230,
    batteryMah: 4000,
    charging: "USB Type-C",
    blades: "6 stainless steel blades",
    icecrush: true,
    warranty: "1 year + 10-day money-back",
    rating: 4.2,
    reliabilityNote: "Indian brand with responsive local support; consistent motor performance reported; 1-yr warranty honoured via brand store.",
    pros: ["230W motor crushes ice", "4000mAh = 15-20 blends per charge", "500ml good capacity", "Local warranty + money-back guarantee"],
    cons: ["Slightly bulky", "Costs more than budget options"],
    link: "https://instacuppastore.com/products/portable-blender-smoothie-milk-shakes-crushing-ice-juices-1"
  },
  {
    id: "agaro-galaxy",
    name: "AGARO Galaxy Portable Blender",
    brand: "AGARO",
    price: 1799,
    capacityMl: 450,
    motorWatts: 126,
    batteryMah: 3000,
    charging: "USB Type-C",
    blades: "6 stainless steel blades",
    icecrush: false,
    warranty: "1 year",
    rating: 4.0,
    reliabilityNote: "Established Indian appliance brand with wide service network; motor is modest but consistent; few failure reports.",
    pros: ["Best value (~₹1,600-1,800 street price)", "450ml BPA-free jar", "Reputed Indian brand, easy warranty claims", "Type-C fast charging"],
    cons: ["126W motor struggles with ice/hard fruit", "No LED battery indicator"],
    link: "https://www.amazon.in/AGARO-Portable-Smoothie-Rechargeable-Stainless/dp/B0CL7KY93F"
  },
  {
    id: "instacuppa-6000",
    name: "InstaCuppa Portable Blender (6000mAh LED Edition)",
    brand: "InstaCuppa",
    price: 3499,
    capacityMl: 600,
    motorWatts: 230,
    batteryMah: 6000,
    charging: "USB Type-C fast charging",
    blades: "6 stainless steel blades",
    icecrush: true,
    warranty: "1 year",
    rating: 4.2,
    reliabilityNote: "Same proven 230W motor platform as the 4000mAh edition; LED battery display avoids mid-blend surprises.",
    pros: ["Biggest battery in class (6000mAh)", "LED battery display + 40s blend timer", "600ml capacity", "Sipper lid — blend and drink from same bottle"],
    cons: ["Most expensive in this list", "Heavier to carry"],
    link: "https://www.amazon.in/InstaCuppa-6000-Detachable-600-ML/dp/B0DFY8ZPCL"
  },
  {
    id: "blendjet2",
    name: "BlendJet 2",
    brand: "BlendJet (USA)",
    price: 2999,
    capacityMl: 475,
    motorWatts: 150,
    batteryMah: 2000,
    charging: "USB Type-C",
    blades: "Stainless steel 6-point blade",
    icecrush: true,
    warranty: "1 year (via BlendJet.in)",
    rating: 3.9,
    reliabilityNote: "Polished design and self-cleaning, but history of a 4.8M-unit US recall (blade/overheating) and 'Poor' Trustpilot rating; units failing within months is a commonly reported complaint. Redesigned base passed Consumer Reports durability retest.",
    pros: ["Best-in-class design, quiet, self-cleaning mode", "TurboJet mode crushes ice", "Officially launched in India (BlendJet.in, ₹2,999)", "Huge accessory/recipe ecosystem"],
    cons: ["Track record of early failures + past recall", "After-sales support in India is new/unproven", "Small 2000mAh battery (~10-15 blends)"],
    link: "https://blendjet.com"
  },
  {
    id: "butterfly-flash",
    name: "Butterfly Flash+ Nutri Blender",
    brand: "Butterfly",
    price: 1399,
    capacityMl: 300,
    motorWatts: 40,
    batteryMah: 1200,
    charging: "USB Type-C",
    blades: "Stainless steel blades",
    icecrush: false,
    warranty: "1 year",
    rating: 3.9,
    reliabilityNote: "Big Indian kitchen brand with nationwide service; low-power motor is under-stressed so failures are rare, but it's slow.",
    pros: ["Cheapest branded option (~₹1,400)", "Trusted Indian brand + service network", "Very light and compact"],
    cons: ["Only 40W — soft fruits/shakes only, no ice", "Small 300ml jar and 1200mAh battery"],
    link: "https://www.amazon.in/Butterfly-Nutri-Blender-Portable-Charging-Rechargeable/dp/B0GGJ16993"
  },
  {
    id: "wonderchef-nutricup",
    name: "Wonderchef Nutri-Cup Portable Blender",
    brand: "Wonderchef",
    price: 2500,
    capacityMl: 300,
    motorWatts: 40,
    batteryMah: 2000,
    charging: "USB",
    blades: "Stainless steel blades",
    icecrush: false,
    warranty: "1 year",
    rating: 3.8,
    reliabilityNote: "Reputed brand and decent build, but you pay a brand premium for a 40W motor other brands sell cheaper.",
    pros: ["Premium look and finish", "Known brand with service support"],
    cons: ["40W motor is weak for the price", "300ml only", "Poor value vs AGARO/Butterfly"],
    link: "https://cashkaro.com/wonderchef-40w-300ml-nutri-cup-portable-blender/CKS-Juicer-Mixer-Grinder-000249"
  },
  {
    id: "superstud-360",
    name: "SUPERSTUD Portable USB Juicer Blender 360W (your previous one)",
    brand: "SUPERSTUD",
    price: 1999,
    capacityMl: 700,
    motorWatts: 360,
    batteryMah: 6000,
    charging: "USB Type-C fast charging",
    blades: "Stainless steel blades",
    icecrush: true,
    warranty: "Limited / seller-dependent",
    rating: 3.6,
    reliabilityNote: "Spec sheet looks great (360W, 700ml, 6000mAh) but it's an unbranded import with weak QC — your unit stopped working twice, and its 3.6★ rating reflects similar failures. No real service network.",
    pros: ["Biggest claimed specs per rupee (360W, 700ml, 6000mAh)"],
    cons: ["Failed twice for you — poor reliability", "3.6★ Amazon rating", "No trustworthy warranty or service network", "Claimed wattage likely overstated"],
    link: "https://www.amazon.in/SUPERSTUD-Portable-Blender-Smoothie-Compact/dp/B0FT3RQ6KX"
  }
];
if (typeof module !== "undefined") module.exports = { BLENDERS };
