// Researched market data: portable USB-rechargeable blenders sold in India.
// Prices in INR, researched 19 Jul 2026 from Amazon.in, Flipkart, brand
// stores (instacuppastore.com, agarolifestyle.com, solara.in, blendlife.in,
// blendjet.com) and price trackers. Where a maker does not publish a figure
// it is marked "Not officially published" rather than guessed.
// `fullSpec` holds every spec field for the side-by-side table.
const BLENDERS = [
  {
    id: "instacuppa-6000",
    brand: "InstaCuppa",
    model: "6000mAh Premium (LED Edition)",
    price: 3199,
    motor: "230 W",
    battery: "6000 mAh",
    capacity: "600 ml",
    charging: "USB Type-C fast charging",
    icecrush: "Yes (small cubes with liquid)",
    highlight: "Biggest battery + jar in the segment, LED battery display, Indian warranty",
    pros: ["6000mAh — a week+ of daily blends", "LED display shows battery % and 40s blend timer", "600ml fits meal-replacement smoothies", "1-yr Indian warranty, BIS certified"],
    cons: ["Priciest Indian option (₹3,199-3,499)", "Bulky — won't fit car cup holders", "Heaviest to carry"],
    scores: { reliability: 8.5, power: 8.5, battery: 10, value: 7.5, support: 8.5, capacity: 9.5 },
    fullSpec: {
      motorWatts: "230 W",
      motorVoltage: "7.4 V (dual cell)",
      rpm: "~22,000 RPM",
      blades: "6-blade, 304 stainless steel",
      iceCrushing: "Yes — small cubes with liquid",
      blendTime: "40 s cycle (auto timer)",
      batteryMah: "6000 mAh Li-ion",
      blendsPerCharge: "20+ blends",
      chargePort: "USB Type-C, fast charging",
      chargeTime: "~90 min",
      batteryIndicator: "LED display (percentage)",
      jarCapacity: "600 ml",
      jarMaterial: "BPA-free Tritan plastic",
      lid: "Sipper lid + detachable bottom cap",
      leakProof: "Yes — silicone seal",
      selfCleaning: "Yes (water + soap pulse)",
      safetyLock: "Magnetic safety interlock",
      weight: "~750 g",
      dimensions: "Not officially published",
      colours: "Black, White",
      bisCertified: "Yes",
      warranty: "1 year (Indian support, WhatsApp/email)",
      rating: "4.2\u2605 (Amazon.in)",
      madeIn: "China (Indian brand, BIS certified)",
    },
    buyUrl: "https://www.amazon.in/InstaCuppa-6000-Detachable-600-ML/dp/B0DFY8ZPCL",
    buyStore: "Amazon.in",
  },
  {
    id: "instacuppa-4000",
    brand: "InstaCuppa",
    model: "4000mAh Edition",
    price: 2799,
    motor: "230 W",
    battery: "4000 mAh",
    capacity: "500 ml",
    charging: "Micro-USB",
    icecrush: "Yes (small cubes with liquid)",
    highlight: "Best balance of power, battery and price in the InstaCuppa lineup",
    pros: ["Same 230W motor as the flagship", "4000mAh = 15-20 blends per charge", "500ml sweet-spot capacity", "10-day money-back + 1-yr warranty"],
    cons: ["Micro-USB, not USB-C (slower 2-3h charging)", "No battery level indicator"],
    scores: { reliability: 8.5, power: 8.5, battery: 8.5, value: 8.0, support: 8.5, capacity: 8.0 },
    fullSpec: {
      motorWatts: "230 W",
      motorVoltage: "7.4 V (dual cell)",
      rpm: "~22,000 RPM",
      blades: "6-blade, 304 stainless steel",
      iceCrushing: "Yes — small cubes with liquid",
      blendTime: "30-40 s per cycle",
      batteryMah: "4000 mAh Li-ion",
      blendsPerCharge: "15-20 blends",
      chargePort: "Micro-USB",
      chargeTime: "2-3 h",
      batteryIndicator: "Charging light only",
      jarCapacity: "500 ml",
      jarMaterial: "BPA-free plastic",
      lid: "Screw-top travel lid",
      leakProof: "Yes — silicone seal",
      selfCleaning: "Yes (water + soap pulse)",
      safetyLock: "Contact-based interlock",
      weight: "~650 g",
      dimensions: "Not officially published",
      colours: "Black, Green",
      bisCertified: "Yes",
      warranty: "1 year + 10-day money-back",
      rating: "4.2\u2605 (Amazon.in)",
      madeIn: "China (Indian brand, BIS certified)",
    },
    buyUrl: "https://instacuppastore.com/products/portable-blender-smoothie-milk-shakes-crushing-ice-juices-1",
    buyStore: "InstaCuppa Store",
  },
  {
    id: "instacuppa-v3",
    brand: "InstaCuppa",
    model: "V3 Upgraded",
    price: 2999,
    motor: "230 W",
    battery: "Not officially published",
    capacity: "450 ml",
    charging: "USB Type-C",
    icecrush: "Yes (frozen fruit, small cubes)",
    highlight: "Most powerful motor in a mid-size USB-C bottle — best for daily power blending",
    pros: ["230W + 22,000 RPM handles frozen banana/oats in 30-40s", "USB-C fast charging", "Compact 450ml form factor"],
    cons: ["No battery indicator — you guess remaining charge", "450ml tight for large smoothies"],
    scores: { reliability: 8.5, power: 9.0, battery: 7.0, value: 7.5, support: 8.5, capacity: 7.0 },
    fullSpec: {
      motorWatts: "230 W",
      motorVoltage: "7.4 V (dual cell)",
      rpm: "22,000 RPM",
      blades: "6-blade, 304 stainless steel",
      iceCrushing: "Yes — frozen fruit and small cubes",
      blendTime: "30-40 s per cycle",
      batteryMah: "Not officially published",
      blendsPerCharge: "~12-15 blends",
      chargePort: "USB Type-C",
      chargeTime: "60-90 min",
      batteryIndicator: "None",
      jarCapacity: "450 ml",
      jarMaterial: "BPA-free plastic",
      lid: "Screw-top travel lid",
      leakProof: "Yes — silicone seal",
      selfCleaning: "Yes (water + soap pulse)",
      safetyLock: "Contact-based interlock",
      weight: "~600 g",
      dimensions: "Not officially published",
      colours: "Black",
      bisCertified: "Yes",
      warranty: "1 year (Indian support)",
      rating: "4.2\u2605 (Amazon.in)",
      madeIn: "China (Indian brand, BIS certified)",
    },
    buyUrl: "https://instacuppastore.com/collections/instacuppa-best-selling-products",
    buyStore: "InstaCuppa Store",
  },
  {
    id: "instacuppa-slim",
    brand: "InstaCuppa",
    model: "Ultra Slim (Magnetic Lock)",
    price: 2699,
    motor: "180 W",
    battery: "3000 mAh",
    capacity: "480 ml",
    charging: "USB Type-C",
    icecrush: "No (soft/frozen-soft only)",
    highlight: "Built for the gym bag — slim body, magnetic lock, leak-proof",
    pros: ["Magnetic lock seal won't pop open in a bag", "Slim — fits gym bag side pockets", "480ml is exactly one protein shake", "USB-C"],
    cons: ["180W struggles with ice/frozen fruit", "Not a power blender"],
    scores: { reliability: 8.5, power: 6.5, battery: 7.5, value: 7.5, support: 8.5, capacity: 7.5 },
    fullSpec: {
      motorWatts: "180 W",
      motorVoltage: "7.4 V",
      rpm: "~18,000 RPM",
      blades: "6-blade, 304 stainless steel",
      iceCrushing: "No — protein powder, banana, soft fruit",
      blendTime: "30-40 s per cycle",
      batteryMah: "3000 mAh Li-ion",
      blendsPerCharge: "12-15 blends",
      chargePort: "USB Type-C",
      chargeTime: "~90 min",
      batteryIndicator: "Charging light only",
      jarCapacity: "480 ml (with ml markings)",
      jarMaterial: "BPA-free plastic",
      lid: "Magnetic lock lid",
      leakProof: "Yes — magnetic lock seal",
      selfCleaning: "Yes (water + soap pulse)",
      safetyLock: "Magnetic safety lock",
      weight: "~550 g",
      dimensions: "Slim profile (fits bag side pocket)",
      colours: "Black, White",
      bisCertified: "Yes",
      warranty: "1 year (Indian support)",
      rating: "4.1\u2605 (Amazon.in)",
      madeIn: "China (Indian brand, BIS certified)",
    },
    buyUrl: "https://instacuppa.com/products/instacuppa-ultra-slim-portable-blender-bottle-180w-power-3000mah-battery-usb-type-c-rechargeable-6-stainless-steel-blades-480ml-capacity-with-markings-magnetic-lock-safety-upgraded-edition",
    buyStore: "InstaCuppa Store",
  },
  {
    id: "instacuppa-normal",
    brand: "InstaCuppa",
    model: "Normal Edition (150W)",
    price: 2199,
    motor: "150 W",
    battery: "2000 mAh",
    capacity: "400 ml",
    charging: "Micro-USB",
    icecrush: "No",
    highlight: "InstaCuppa's budget entry point — basic but from a serviceable brand",
    pros: ["Cheapest InstaCuppa (₹2,199)", "Same 1-yr Indian warranty", "Light and compact"],
    cons: ["Micro-USB, 2-3h charging", "2000mAh = charge every 2-3 days", "Friction seal — carry upright"],
    scores: { reliability: 8.0, power: 5.5, battery: 5.5, value: 6.5, support: 8.5, capacity: 6.0 },
    fullSpec: {
      motorWatts: "150 W",
      motorVoltage: "7.4 V",
      rpm: "~15,000-18,000 RPM",
      blades: "6-blade, stainless steel",
      iceCrushing: "No — soft fruit and shakes",
      blendTime: "30-40 s per cycle",
      batteryMah: "2000 mAh Li-ion",
      blendsPerCharge: "8-10 blends",
      chargePort: "Micro-USB",
      chargeTime: "2-3 h",
      batteryIndicator: "Charging light only",
      jarCapacity: "400 ml (built-in jar)",
      jarMaterial: "BPA-free plastic",
      lid: "Friction-fit travel lid",
      leakProof: "Friction seal — carry upright",
      selfCleaning: "Yes (water + soap pulse)",
      safetyLock: "Contact-based interlock",
      weight: "~500 g",
      dimensions: "Not officially published",
      colours: "Green, Pink, Black",
      bisCertified: "Yes",
      warranty: "1 year (Indian support)",
      rating: "4.1\u2605 (Amazon.in)",
      madeIn: "China (Indian brand, BIS certified)",
    },
    buyUrl: "https://instacuppastore.com/products/instacuppa-portable-blender-usb-rechargeable",
    buyStore: "InstaCuppa Store",
  },
  {
    id: "agaro-galaxy",
    brand: "AGARO",
    model: "Galaxy Portable Blender",
    price: 1799,
    motor: "126 W",
    battery: "3000 mAh",
    capacity: "450 ml",
    charging: "USB Type-C",
    icecrush: "No",
    highlight: "Best value from a big Indian appliance brand — street price often under ₹1,700",
    pros: ["₹1,569-1,799 street price", "Reputed brand, wide service network", "450ml BPA-free jar, 6 SS blades", "USB-C"],
    cons: ["126W — soft fruits and shakes only", "No battery indicator", "Can stall on thick mixes"],
    scores: { reliability: 8.5, power: 5.0, battery: 7.0, value: 9.0, support: 9.0, capacity: 7.0 },
    fullSpec: {
      motorWatts: "126 W (400W peak claimed on some listings)",
      motorVoltage: "7.4 V copper motor",
      rpm: "~15,000 RPM",
      blades: "6-blade, stainless steel",
      iceCrushing: "No — soft fruit, shakes, juices",
      blendTime: "30-40 s per cycle",
      batteryMah: "3000 mAh Li-ion",
      blendsPerCharge: "12-15 blends",
      chargePort: "USB Type-C",
      chargeTime: "~2 h",
      batteryIndicator: "Charging light only",
      jarCapacity: "450 ml",
      jarMaterial: "BPA-free food-grade plastic",
      lid: "Screw-top lid",
      leakProof: "Yes — silicone seal",
      selfCleaning: "Yes (water pulse)",
      safetyLock: "Contact-based interlock",
      weight: "~590 g",
      dimensions: "7.5 \u00D7 7.5 \u00D7 25 cm",
      colours: "Black",
      bisCertified: "Yes",
      warranty: "1 year (AGARO service network)",
      rating: "4.0\u2605 (Amazon.in)",
      madeIn: "China (Indian brand)",
    },
    buyUrl: "https://www.amazon.in/AGARO-Portable-Smoothie-Rechargeable-Stainless/dp/B0CL7KY93F",
    buyStore: "Amazon.in",
  },
  {
    id: "blendjet2",
    brand: "BlendJet (USA)",
    model: "BlendJet 2",
    price: 2999,
    motor: "~175 W equivalent (5V TurboJet)",
    battery: "2000 mAh",
    capacity: "475 ml (16 oz)",
    charging: "USB Type-C",
    icecrush: "Yes (TurboJet mode, small cubes)",
    highlight: "The best-designed portable blender — now officially in India at ₹2,999, but with a rocky reliability record",
    pros: ["Premium build, quietest in class", "Self-cleaning + TurboJet ice mode", "Official India launch (BlendJet.in) — no more import markup", "Huge accessory/recipe ecosystem"],
    cons: ["4.8M-unit US recall (blade breakage/overheating) in its history", "'Poor' Trustpilot rating; many 'died in 3 months' reports", "India after-sales network is new and unproven", "2000mAh — only 10-15 blends per charge"],
    scores: { reliability: 5.5, power: 7.0, battery: 5.5, value: 6.0, support: 5.0, capacity: 7.5 },
    fullSpec: {
      motorWatts: "Not officially published (~175 W equivalent)",
      motorVoltage: "5 V TurboJet motor",
      rpm: "Not officially published",
      blades: "6-point stainless steel blade",
      iceCrushing: "Yes — TurboJet mode, small cubes",
      blendTime: "20 s per cycle",
      batteryMah: "2000 mAh Li-ion",
      blendsPerCharge: "10-15 blends",
      chargePort: "USB Type-C",
      chargeTime: "~60 min",
      batteryIndicator: "LED ring (colour-coded)",
      jarCapacity: "475 ml (16 oz)",
      jarMaterial: "BPA-free Tritan",
      lid: "Screw-top with carry loop",
      leakProof: "Yes — water-resistant base",
      selfCleaning: "Yes — one-touch self-clean",
      safetyLock: "Redesigned locked-base (post-recall)",
      weight: "~610 g",
      dimensions: "23 \u00D7 7.6 cm",
      colours: "20+ colours/patterns",
      bisCertified: "Not officially published",
      warranty: "1 year via BlendJet.in (7-day return window reported)",
      rating: "3.9\u2605 (global avg); Trustpilot 'Poor'",
      madeIn: "China (US brand)",
    },
    buyUrl: "https://blendjet.com",
    buyStore: "BlendJet.in",
  },
  {
    id: "solara-blendkwik",
    brand: "Solara",
    model: "BlendKwik",
    price: 1999,
    motor: "180 W",
    battery: "4000 mAh",
    capacity: "450 ml",
    charging: "USB Type-C",
    icecrush: "Yes (small cubes with liquid)",
    highlight: "Strongest specs under ₹2,000 from a known Indian D2C brand",
    pros: ["180W + 4000mAh at ₹1,999", "USB-C", "Well-reviewed after months of daily use", "Indian brand with responsive support"],
    cons: ["D2C brand — service is courier-based, no walk-in centres", "Lid threading feels less premium"],
    scores: { reliability: 7.5, power: 6.5, battery: 8.5, value: 9.0, support: 7.0, capacity: 7.0 },
    fullSpec: {
      motorWatts: "180 W",
      motorVoltage: "7.4 V",
      rpm: "~18,000 RPM",
      blades: "6-blade, stainless steel",
      iceCrushing: "Yes — small cubes with liquid",
      blendTime: "30-40 s per cycle",
      batteryMah: "4000 mAh Li-ion",
      blendsPerCharge: "15-18 blends",
      chargePort: "USB Type-C",
      chargeTime: "2-3 h",
      batteryIndicator: "Charging light only",
      jarCapacity: "450 ml",
      jarMaterial: "BPA-free plastic",
      lid: "Screw-top travel lid",
      leakProof: "Yes — silicone seal",
      selfCleaning: "Yes (water pulse)",
      safetyLock: "Contact-based interlock",
      weight: "~560 g",
      dimensions: "Not officially published",
      colours: "Multiple",
      bisCertified: "Yes",
      warranty: "1 year (Solara India)",
      rating: "4.1\u2605 (Amazon.in)",
      madeIn: "China (Indian brand)",
    },
    buyUrl: "https://www.solara.in/products/blendkwik-portable-blender",
    buyStore: "Solara.in",
  },
  {
    id: "solara-blendkwik-pro",
    brand: "Solara",
    model: "BlendKwik Pro",
    price: 2499,
    motor: "200 W",
    battery: "4000 mAh",
    capacity: "500 ml",
    charging: "USB Type-C",
    icecrush: "Yes (small cubes with liquid)",
    highlight: "The upgraded BlendKwik — more power and capacity, still under ₹2,500",
    pros: ["200W motor, 500ml jar", "4000mAh battery", "USB-C (0-100% in 2-3h)", "Good value at ₹2,499"],
    cons: ["Same courier-based service model", "Bulkier than the standard BlendKwik"],
    scores: { reliability: 7.5, power: 7.5, battery: 8.5, value: 8.5, support: 7.0, capacity: 8.0 },
    fullSpec: {
      motorWatts: "200 W",
      motorVoltage: "7.4 V",
      rpm: "~20,000 RPM",
      blades: "6-blade, stainless steel",
      iceCrushing: "Yes — small cubes with liquid",
      blendTime: "30-40 s per cycle",
      batteryMah: "4000 mAh Li-ion",
      blendsPerCharge: "15-18 blends",
      chargePort: "USB Type-C",
      chargeTime: "2-3 h (0-100%)",
      batteryIndicator: "Charging light only",
      jarCapacity: "500 ml",
      jarMaterial: "BPA-free plastic",
      lid: "Screw-top travel lid",
      leakProof: "Yes — silicone seal",
      selfCleaning: "Yes (water pulse)",
      safetyLock: "Contact-based interlock",
      weight: "~620 g",
      dimensions: "Not officially published",
      colours: "Multiple",
      bisCertified: "Yes",
      warranty: "1 year (Solara India)",
      rating: "4.1\u2605 (Amazon.in)",
      madeIn: "China (Indian brand)",
    },
    buyUrl: "https://www.solara.in/products/blendkwik-portable-blender-pro",
    buyStore: "Solara.in",
  },
  {
    id: "blendlife-go",
    brand: "BlendLife",
    model: "GO",
    price: 1499,
    motor: "7.4 V motor (watts not published)",
    battery: "2000 mAh",
    capacity: "420 ml",
    charging: "USB Type-C",
    icecrush: "No",
    highlight: "Made-in-India, BIS certified, 1-yr full replacement warranty — at ₹1,499 with a free extra jar",
    pros: ["₹1,499 launch price incl. free extra 420ml jar", "Made in India, BIS certified", "Full 1-yr replacement (not repair) warranty", "32-blade titanium-coated assembly, magnetic safety lock"],
    cons: ["Wattage not published — modest power, soft ingredients only", "Young brand — long-term track record unknown", "2000mAh battery"],
    scores: { reliability: 7.0, power: 5.0, battery: 5.5, value: 9.0, support: 7.0, capacity: 6.5 },
    fullSpec: {
      motorWatts: "Not officially published",
      motorVoltage: "7.4 V",
      rpm: "Not officially published",
      blades: "32-blade titanium-coated assembly",
      iceCrushing: "No — soft fruits and shakes",
      blendTime: "~30 s per cycle",
      batteryMah: "2000 mAh Li-ion",
      blendsPerCharge: "10-12 blends",
      chargePort: "USB Type-C",
      chargeTime: "~2 h",
      batteryIndicator: "Charging light only",
      jarCapacity: "420 ml (+ free extra 420 ml jar)",
      jarMaterial: "BPA-free plastic",
      lid: "Screw-top travel lid",
      leakProof: "Yes — magnetic safety lock",
      selfCleaning: "Yes — self-cleaning mode",
      safetyLock: "Magnetic safety lock",
      weight: "~500 g",
      dimensions: "Not officially published",
      colours: "Camo Black, more",
      bisCertified: "Yes",
      warranty: "1 year full replacement",
      rating: "4.2\u2605 (Amazon.in, early reviews)",
      madeIn: "India",
    },
    buyUrl: "https://blendlife.in/product/go",
    buyStore: "BlendLife.in",
  },
  {
    id: "butterfly-flash",
    brand: "Butterfly",
    model: "Flash+ Nutri Blender",
    price: 1399,
    motor: "40 W",
    battery: "1200 mAh",
    capacity: "300 ml",
    charging: "USB Type-C",
    icecrush: "No",
    highlight: "Cheapest big-brand option — fine for soft shakes, backed by Butterfly's service network",
    pros: ["₹1,185-1,445 street price", "Butterfly nationwide service network", "Very light and compact", "USB-C"],
    cons: ["Only 40W — slow, soft ingredients only", "300ml jar, 1200mAh battery", "No ice, no frozen fruit"],
    scores: { reliability: 8.0, power: 3.0, battery: 4.0, value: 7.0, support: 9.0, capacity: 4.5 },
    fullSpec: {
      motorWatts: "40 W",
      motorVoltage: "3.7 V",
      rpm: "~12,000 RPM",
      blades: "4-blade, stainless steel",
      iceCrushing: "No",
      blendTime: "~40 s per cycle",
      batteryMah: "1200 mAh Li-ion",
      blendsPerCharge: "6-8 blends",
      chargePort: "USB Type-C",
      chargeTime: "~2 h",
      batteryIndicator: "Charging light only",
      jarCapacity: "300 ml (built-in jar)",
      jarMaterial: "Food-grade plastic",
      lid: "Flip sipper lid",
      leakProof: "Yes",
      selfCleaning: "Rinse-clean",
      safetyLock: "Contact-based interlock",
      weight: "~400 g",
      dimensions: "Not officially published",
      colours: "Pink, Blue",
      bisCertified: "Yes",
      warranty: "1 year (Butterfly service network)",
      rating: "3.9\u2605 (Amazon.in)",
      madeIn: "India",
    },
    buyUrl: "https://www.amazon.in/Butterfly-Nutri-Blender-Portable-Charging-Rechargeable/dp/B0GGJ16993",
    buyStore: "Amazon.in",
  },
  {
    id: "wonderchef-nutricup",
    brand: "Wonderchef",
    model: "Nutri-Cup",
    price: 2500,
    motor: "40 W",
    battery: "2000 mAh",
    capacity: "300 ml",
    charging: "USB (Micro-USB)",
    icecrush: "No",
    highlight: "Premium brand finish, but you pay ₹2,500 for the same 40W others sell at ₹1,400",
    pros: ["Premium look and colours", "Known brand with service support", "Compact"],
    cons: ["40W at ₹2,500 — poor value", "300ml only", "Micro-USB"],
    scores: { reliability: 7.5, power: 3.0, battery: 5.5, value: 4.0, support: 8.0, capacity: 4.5 },
    fullSpec: {
      motorWatts: "40 W",
      motorVoltage: "3.7 V",
      rpm: "~12,000 RPM",
      blades: "4-blade, stainless steel",
      iceCrushing: "No",
      blendTime: "~40 s per cycle",
      batteryMah: "2000 mAh Li-ion",
      blendsPerCharge: "8-10 blends",
      chargePort: "Micro-USB",
      chargeTime: "~3 h",
      batteryIndicator: "Charging light only",
      jarCapacity: "300 ml",
      jarMaterial: "Food-grade plastic",
      lid: "Screw-top lid",
      leakProof: "Yes",
      selfCleaning: "Rinse-clean",
      safetyLock: "Contact-based interlock",
      weight: "~420 g",
      dimensions: "Not officially published",
      colours: "Blue, Pink, Green",
      bisCertified: "Yes",
      warranty: "1 year (Wonderchef)",
      rating: "3.8\u2605 (Amazon.in)",
      madeIn: "China (Indian brand)",
    },
    buyUrl: "https://cashkaro.com/wonderchef-40w-300ml-nutri-cup-portable-blender/CKS-Juicer-Mixer-Grinder-000249",
    buyStore: "Amazon/Flipkart",
  },
  {
    id: "nutribullet-go",
    brand: "Nutribullet (import)",
    model: "Go Portable Blender",
    price: 4999,
    motor: "~70 W (13,000 RPM)",
    battery: "2000 mAh",
    capacity: "385 ml",
    charging: "USB Type-C",
    icecrush: "No",
    highlight: "Premium global brand and build — but imported, pricey, and no Indian warranty",
    pros: ["Excellent build quality", "Trusted global blender brand", "USB-C"],
    cons: ["₹4,500-6,000 import pricing", "No local warranty/service in India", "Small 385ml jar", "Modest power for the price"],
    scores: { reliability: 8.0, power: 4.5, battery: 5.5, value: 3.0, support: 3.0, capacity: 6.0 },
    fullSpec: {
      motorWatts: "~70 W",
      motorVoltage: "7.4 V",
      rpm: "13,000 RPM",
      blades: "6-blade, stainless steel",
      iceCrushing: "No — soft ingredients",
      blendTime: "30 s per cycle",
      batteryMah: "2000 mAh Li-ion",
      blendsPerCharge: "~15 blends",
      chargePort: "USB Type-C",
      chargeTime: "~2 h",
      batteryIndicator: "LED light",
      jarCapacity: "385 ml (13 oz)",
      jarMaterial: "BPA-free plastic",
      lid: "To-go lid",
      leakProof: "Yes",
      selfCleaning: "Rinse-clean",
      safetyLock: "Twist-lock activation",
      weight: "~540 g",
      dimensions: "Not officially published",
      colours: "Multiple",
      bisCertified: "No (grey import)",
      warranty: "None in India (import)",
      rating: "4.3\u2605 (global)",
      madeIn: "China (US brand)",
    },
    buyUrl: "https://www.amazon.in/s?k=nutribullet+go+portable+blender",
    buyStore: "Amazon.in (imports)",
  },
  {
    id: "superstud-360",
    brand: "SUPERSTUD",
    model: "360W Portable Blender (your previous one)",
    price: 1999,
    motor: "360 W claimed",
    battery: "6000 mAh claimed",
    capacity: "700 ml",
    charging: "USB Type-C fast charging",
    icecrush: "Claimed yes",
    highlight: "The spec-sheet king that died twice on you — a case study in why unbranded claims get discounted",
    pros: ["Biggest claimed specs per rupee (360W, 700ml, 6000mAh)", "Type-C fast charging"],
    cons: ["Stopped working twice for you", "3.6\u2605 rating with similar failure reports", "No service network; seller-dependent 'warranty'", "Claimed wattage likely overstated"],
    scores: { reliability: 2.5, power: 7.0, battery: 8.0, value: 3.0, support: 2.0, capacity: 10 },
    fullSpec: {
      motorWatts: "360 W claimed (unverified)",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "6-blade, stainless steel",
      iceCrushing: "Claimed yes",
      blendTime: "Not officially published",
      batteryMah: "6000 mAh claimed",
      blendsPerCharge: "Not officially published",
      chargePort: "USB Type-C fast charging",
      chargeTime: "Not officially published",
      batteryIndicator: "Charging light only",
      jarCapacity: "700 ml",
      jarMaterial: "Plastic (grade not published)",
      lid: "Screw-top lid",
      leakProof: "Claimed yes",
      selfCleaning: "Rinse-clean",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Black",
      bisCertified: "Not officially published",
      warranty: "Seller-dependent, effectively none",
      rating: "3.6\u2605 (Amazon.in)",
      madeIn: "China (unbranded import)",
    },
    buyUrl: "https://www.amazon.in/SUPERSTUD-Portable-Blender-Smoothie-Compact/dp/B0FT3RQ6KX",
    buyStore: "Amazon.in",
  },
  {
    id: "kilig-vortex-pro",
    brand: "Kilig",
    model: "Vortex Pro 360W (Dual Mode)",
    price: 2490,
    motor: "360 W claimed (12V copper motor)",
    battery: "6000 mAh",
    capacity: "700 ml",
    charging: "USB Type-C",
    icecrush: "Yes (small cubes with liquid)",
    highlight: "Big 700ml 2-in-1 jar with dual blend modes and 6000mAh battery at a mid price",
    pros: ["700 ml 2-in-1 convertible jar", "6000 mAh battery, USB-C", "Dual blend modes, 22,000 RPM", "Widely stocked (Amazon, Flipkart, Zepto)"],
    cons: ["Only 3.7\u2605 on Flipkart (10 ratings) \u2014 thin track record", "Newer brand, service depth unproven", "360 W claim from a compact 12 V motor is optimistic"],
    scores: { reliability: 6.0, power: 8.0, battery: 9.5, value: 7.5, support: 5.5, capacity: 9.5 },
    fullSpec: {
      motorWatts: "360 W claimed (12 V copper motor)",
      motorVoltage: "12 V",
      rpm: "22,000 RPM",
      blades: "6-sided stainless steel",
      iceCrushing: "Yes \u2014 small cubes with liquid",
      blendTime: "Dual mode, auto cut-off cycle",
      batteryMah: "6000 mAh Li-ion",
      blendsPerCharge: "Not officially published",
      chargePort: "USB Type-C",
      chargeTime: "Not officially published",
      batteryIndicator: "LED indicator",
      jarCapacity: "700 ml (2-in-1 convertible jar)",
      jarMaterial: "BPA-free plastic",
      lid: "Screw-top with detachable jar",
      leakProof: "Claimed yes",
      selfCleaning: "Rinse-clean pulse",
      safetyLock: "Auto shut-off",
      weight: "Not officially published",
      dimensions: "8.5 \u00D7 8.5 \u00D7 29.5 cm",
      colours: "Black/Transparent, White",
      bisCertified: "Not officially published",
      warranty: "1 year (brand claimed)",
      rating: "3.7\u2605 (Flipkart, 10 ratings)",
      madeIn: "China (Indian seller brand)",
    },
    buyUrl: "https://www.amazon.in/Portable-Blender-Smoothie-Battery-22000RPM/dp/B0DNN1MRDJ",
    buyStore: "Amazon.in",
  },
  {
    id: "kilig-vortex-next",
    brand: "Kilig",
    model: "Vortex Next 380W (Triple Mode)",
    price: 2499,
    motor: "380 W claimed",
    battery: "6000 mAh",
    capacity: "700 ml",
    charging: "USB Type-C",
    icecrush: "Yes (small cubes with liquid)",
    highlight: "Kilig's newest triple-mode flagship \u2014 same 700ml/6000mAh platform with a higher power claim",
    pros: ["Triple blend modes", "700 ml 2-in-1 jar + 6000 mAh", "USB Type-C", "22,000 RPM 6-sided blade"],
    cons: ["Very new listing \u2014 almost no reviews yet", "380 W claim unverified", "Service depth unproven"],
    scores: { reliability: 5.5, power: 8.0, battery: 9.5, value: 7.0, support: 5.5, capacity: 9.5 },
    fullSpec: {
      motorWatts: "380 W claimed (unverified)",
      motorVoltage: "12 V",
      rpm: "22,000 RPM",
      blades: "6-sided stainless steel",
      iceCrushing: "Yes \u2014 small cubes with liquid",
      blendTime: "Triple mode, auto cut-off",
      batteryMah: "6000 mAh Li-ion",
      blendsPerCharge: "Not officially published",
      chargePort: "USB Type-C",
      chargeTime: "Not officially published",
      batteryIndicator: "LED indicator",
      jarCapacity: "700 ml (2-in-1 convertible jar)",
      jarMaterial: "BPA-free plastic",
      lid: "Screw-top with detachable jar",
      leakProof: "Claimed yes",
      selfCleaning: "Rinse-clean pulse",
      safetyLock: "Auto shut-off",
      weight: "Not officially published",
      dimensions: "~8 \u00D7 8 \u00D7 30 cm",
      colours: "Black, White",
      bisCertified: "Not officially published",
      warranty: "1 year (brand claimed)",
      rating: "Too new \u2014 few ratings yet",
      madeIn: "China (Indian seller brand)",
    },
    buyUrl: "https://www.amazon.in/Portable-Convertible-6-Blades-Detachable-Charging/dp/B0FNMR75TX",
    buyStore: "Amazon.in",
  },
  {
    id: "pigeon-blendo",
    brand: "Pigeon (Stovekraft)",
    model: "Blendo 330ml",
    price: 899,
    motor: "~9 W rated (7.4 V DC)",
    battery: "2400 mAh",
    capacity: "330 ml",
    charging: "Micro-USB",
    icecrush: "No",
    highlight: "Cheapest big-brand option \u2014 Stovekraft's national service network at under \u20B91,000",
    pros: ["Very cheap (~\u20B9830\u2013900 street price)", "Stovekraft = real national service network", "20 s auto cut-off safety", "Fine for soft fruit shakes"],
    cons: ["Tiny 9 W rated motor \u2014 no ice, no hard fruit", "330 ml jar is small", "Micro-USB, slow 2.5 h charge", "Marketing says '150 W' but rated power is ~9 W"],
    scores: { reliability: 7.0, power: 2.5, battery: 5.5, value: 8.0, support: 8.5, capacity: 3.5 },
    fullSpec: {
      motorWatts: "~9 W rated (150 W peak marketing claim)",
      motorVoltage: "7.4 V DC",
      rpm: "Not officially published",
      blades: "4-blade stainless steel",
      iceCrushing: "No",
      blendTime: "20 s auto cut-off",
      batteryMah: "2400 mAh",
      blendsPerCharge: "Up to 20 blends (brand claim)",
      chargePort: "Micro-USB",
      chargeTime: "~2.5 h",
      batteryIndicator: "Charging light",
      jarCapacity: "330 ml",
      jarMaterial: "BPA-free plastic",
      lid: "Juicer cup lid",
      leakProof: "Claimed yes",
      selfCleaning: "Rinse-clean",
      safetyLock: "Auto cut-off after 20 s",
      weight: "~500 g",
      dimensions: "Not officially published",
      colours: "Blue, Green",
      bisCertified: "Yes (Stovekraft)",
      warranty: "1 year (Stovekraft service network)",
      rating: "3.9\u2605 (Amazon.in)",
      madeIn: "India brand (Stovekraft), made in China",
    },
    buyUrl: "https://www.amazon.in/Pigeon-rechargeable-Personal-Smoothies-19001314/dp/B08ZCRJ6VZ",
    buyStore: "Amazon.in",
  },
  {
    id: "borosil-nutrisip",
    brand: "Borosil",
    model: "NutriSip Portable Blender 40W",
    price: 2000,
    motor: "40 W",
    battery: "Not officially published",
    capacity: "~420 ml",
    charging: "USB (rechargeable)",
    icecrush: "No",
    highlight: "Trusted Borosil name and honest 40W rating \u2014 but weak reviews for the price",
    pros: ["Borosil brand + 1-year warranty against manufacturing defects", "Honest published wattage (no inflated claims)", "Decent build quality"],
    cons: ["Only 40 W \u2014 soft fruit and shakes only", "2.8\u2605 on Flipkart \u2014 weak user feedback", "Pricey for the power on offer", "Battery capacity not published"],
    scores: { reliability: 6.5, power: 3.0, battery: 4.5, value: 4.0, support: 8.0, capacity: 4.5 },
    fullSpec: {
      motorWatts: "40 W",
      motorVoltage: "DC motor (voltage not published)",
      rpm: "Not officially published",
      blades: "Stainless steel",
      iceCrushing: "No",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB rechargeable",
      chargeTime: "Not officially published",
      batteryIndicator: "Charging light",
      jarCapacity: "~420 ml",
      jarMaterial: "BPA-free plastic",
      lid: "Sipper-style lid",
      leakProof: "Claimed yes",
      selfCleaning: "Rinse-clean",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "White/Grey",
      bisCertified: "Yes",
      warranty: "1 year (Borosil, manufacturing defects)",
      rating: "2.8\u2605 (Flipkart)",
      madeIn: "India brand, made in China",
    },
    buyUrl: "https://www.flipkart.com/search?q=borosil%20nutrisip%20portable%20blender",
    buyStore: "Flipkart",
  },
  {
    id: "lifelong-650",
    brand: "Lifelong",
    model: "Portable Blender 650ml",
    price: 2799,
    motor: "Not officially published",
    battery: "4000 mAh",
    capacity: "650 ml",
    charging: "USB rechargeable",
    icecrush: "Not officially published",
    highlight: "Biggest jar after the 700ml pair, from an established Indian D2C brand",
    pros: ["Large 650 ml jar", "4000 mAh battery", "6 stainless-steel blades", "Established Indian brand with support desk"],
    cons: ["Motor wattage not published", "Often out of stock on brand store", "Mixed reviews on Lifelong small appliances generally"],
    scores: { reliability: 6.0, power: 5.5, battery: 8.0, value: 6.0, support: 7.0, capacity: 9.0 },
    fullSpec: {
      motorWatts: "Not officially published",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "6-blade, stainless steel",
      iceCrushing: "Not officially published",
      blendTime: "Not officially published",
      batteryMah: "4000 mAh",
      blendsPerCharge: "Not officially published",
      chargePort: "USB rechargeable",
      chargeTime: "Not officially published",
      batteryIndicator: "Charging light",
      jarCapacity: "650 ml",
      jarMaterial: "Durable ABS + plastic jar",
      lid: "Screw-top travel lid",
      leakProof: "Claimed yes",
      selfCleaning: "Rinse-clean",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Black, White, Green",
      bisCertified: "Yes",
      warranty: "1 year (Lifelong support desk)",
      rating: "Limited ratings on brand store",
      madeIn: "India brand, made in China",
    },
    buyUrl: "https://www.lifelongindiaonline.com/collections/blender",
    buyStore: "Lifelong Store",
  },
  {
    id: "balzano-180",
    brand: "Balzano",
    model: "Portable Blender 180W",
    price: 1999,
    motor: "180 W (copper motor)",
    battery: "Not officially published",
    capacity: "470 ml",
    charging: "USB Type-C",
    icecrush: "Yes (small cubes with liquid)",
    highlight: "110-year-old Italian-heritage brand with an honest 180W rating and 1-year Indian warranty",
    pros: ["Established brand, 1-year warranty", "Honest published 180 W copper motor", "470 ml ABS jar", "Steep street discount (MRP ₹4,999 → ~₹1,999)"],
    cons: ["Battery capacity not published", "Brand support network smaller than Stovekraft/Borosil", "Mid-tier blending power"],
    scores: {
      reliability: 6.5,
      power: 6.5,
      battery: 5,
      value: 6.5,
      support: 7,
      capacity: 6,
    },
    fullSpec: {
      motorWatts: "180 W (dynamic copper motor)",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "6-sided stainless steel",
      iceCrushing: "Yes — small cubes with liquid",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB Type-C",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "470 ml",
      jarMaterial: "ABS (BPA-free)",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "7 × 24.8 × 7 cm",
      colours: "Black, Green, Purple",
      bisCertified: "Yes",
      warranty: "1 year (Balzano India)",
      rating: "Not officially published",
      madeIn: "Italian-heritage brand, made in China",
    },
    buyUrl: "https://www.amazon.in/Balzano-Portable-Blender-Smoothie-Wireless/dp/B0DH4TGW5G",
    buyStore: "Amazon.in",
  },
  {
    id: "balzano-400",
    brand: "Balzano",
    model: "400W Portable Blender",
    price: 2499,
    motor: "400 W claimed",
    battery: "Not officially published",
    capacity: "470 ml",
    charging: "USB Type-C",
    icecrush: "Yes (small cubes with liquid)",
    highlight: "Balzano's higher-power model — up to 30 blends per charge, sold via Vijay Sales",
    pros: ["Up to 30 blends per charge (brand claim)", "Six-sided blade", "USB-C", "Retail availability (Vijay Sales) + 1-year warranty"],
    cons: ["400 W claim is a peak figure", "Battery mAh not published", "Same 470 ml jar as the 180W model"],
    scores: {
      reliability: 6,
      power: 7.5,
      battery: 6.5,
      value: 6,
      support: 7,
      capacity: 6,
    },
    fullSpec: {
      motorWatts: "400 W claimed (peak)",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "6-sided stainless steel",
      iceCrushing: "Yes — small cubes with liquid",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Up to 30 (brand claim)",
      chargePort: "USB Type-C",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "470 ml",
      jarMaterial: "ABS (BPA-free)",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Green",
      bisCertified: "Yes",
      warranty: "1 year (Balzano India)",
      rating: "Not officially published",
      madeIn: "Italian-heritage brand, made in China",
    },
    buyUrl: "https://www.vijaysales.com/p/234877/balzano-400w-portable-blender-wireless-travel-juicer-for-smoothie-and-juices-crush-ice-baby-food-blender-smoothie-blender-green",
    buyStore: "Vijay Sales",
  },
  {
    id: "instacuppa-steel",
    brand: "InstaCuppa",
    model: "Stainless Steel 230W (500ml)",
    price: 2999,
    motor: "230 W",
    battery: "4000 mAh",
    capacity: "500 ml",
    charging: "USB Type-C",
    icecrush: "Yes (small cubes with liquid)",
    highlight: "InstaCuppa's premium stainless-steel-bodied variant — same proven 230W motor in a metal shell",
    pros: ["Stainless steel body — most durable shell in the lineup", "Proven 230 W motor + 4000 mAh", "USB-C", "Indian warranty and responsive support"],
    cons: ["Heavier than plastic variants", "Costs as much as the 6000 mAh flagship", "500 ml mid-size jar"],
    scores: {
      reliability: 8.5,
      power: 8.5,
      battery: 8,
      value: 7,
      support: 8.5,
      capacity: 7,
    },
    fullSpec: {
      motorWatts: "230 W",
      motorVoltage: "7.4 V (dual cell)",
      rpm: "~22,000 RPM",
      blades: "6-blade, 304 stainless steel",
      iceCrushing: "Yes — small cubes with liquid",
      blendTime: "40 s cycle",
      batteryMah: "4000 mAh Li-ion",
      blendsPerCharge: "Not officially published",
      chargePort: "USB Type-C",
      chargeTime: "Not officially published",
      batteryIndicator: "LED indicator",
      jarCapacity: "500 ml",
      jarMaterial: "Stainless steel body, Tritan jar",
      lid: "Not officially published",
      leakProof: "Yes — silicone seal",
      selfCleaning: "Not officially published",
      safetyLock: "Magnetic safety interlock",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Steel/Black",
      bisCertified: "Yes",
      warranty: "1 year (Indian support)",
      rating: "4.2★ (Amazon.in)",
      madeIn: "China (Indian brand, BIS certified)",
    },
    buyUrl: "https://www.amazon.in/s?k=instacuppa+stainless+steel+portable+blender",
    buyStore: "Amazon.in",
  },
  {
    id: "kilig-vortex-base",
    brand: "Kilig",
    model: "Vortex (4000mAh)",
    price: 1999,
    motor: "Not officially published",
    battery: "4000 mAh",
    capacity: "Not officially published",
    charging: "USB Type-C",
    icecrush: "Claimed yes",
    highlight: "Kilig's entry model — 4000mAh and USB-C at a lower price than the Pro",
    pros: ["4000 mAh battery", "USB Type-C", "Cheapest way into the Kilig lineup"],
    cons: ["Motor wattage and jar size not published", "Thin review history", "Service depth unproven"],
    scores: {
      reliability: 5.5,
      power: 6,
      battery: 8,
      value: 6.5,
      support: 5.5,
      capacity: 6,
    },
    fullSpec: {
      motorWatts: "Not officially published",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Claimed yes",
      blendTime: "Not officially published",
      batteryMah: "4000 mAh Li-ion",
      blendsPerCharge: "Not officially published",
      chargePort: "USB Type-C",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "Not officially published",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "1 year (brand claimed)",
      rating: "Not officially published",
      madeIn: "China (Indian seller brand)",
    },
    buyUrl: "https://www.amazon.in/Portable-Blender-Smoothies-Rechargeable-Battery/dp/B0DNMK8GQJ",
    buyStore: "Amazon.in",
  },
  {
    id: "kilig-vortex-ultra",
    brand: "Kilig",
    model: "Vortex Ultra BL-03 (700ml)",
    price: 2799,
    motor: "Not officially published",
    battery: "6000 mAh",
    capacity: "700 ml",
    charging: "USB Type-C",
    icecrush: "Claimed yes",
    highlight: "Top of the Kilig range — 700ml jar, auto shut-off, USB-C",
    pros: ["700 ml jar", "Auto shut-off safety", "USB Type-C", "Lightweight for its size"],
    cons: ["Wattage not published for this SKU", "Very new — few reviews", "Service depth unproven"],
    scores: {
      reliability: 5.5,
      power: 7,
      battery: 9.5,
      value: 6,
      support: 5.5,
      capacity: 9.5,
    },
    fullSpec: {
      motorWatts: "Not officially published",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Claimed yes",
      blendTime: "Not officially published",
      batteryMah: "6000 mAh Li-ion",
      blendsPerCharge: "Not officially published",
      chargePort: "USB Type-C",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "700 ml",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Auto shut-off",
      weight: "Not officially published",
      dimensions: "8.5 × 8.5 × 29.5 cm",
      colours: "White",
      bisCertified: "Not officially published",
      warranty: "1 year (brand claimed)",
      rating: "Not officially published",
      madeIn: "China (Indian seller brand)",
    },
    buyUrl: "https://www.amazon.in/Portable-Blender-Smoothie-Battery-22000RPM/dp/B0FNMRZH2Y",
    buyStore: "Amazon.in",
  },
  {
    id: "qlect-45w-500",
    brand: "QLECT",
    model: "45W Ice-Crush (500ml)",
    price: 698,
    motor: "45 W",
    battery: "2200 mAh",
    capacity: "500 ml",
    charging: "USB",
    icecrush: "Claimed yes",
    highlight: "The honest budget pick — publishes a real 45W figure instead of a fantasy number",
    pros: ["Publishes honest wattage (45 W) unlike most budget rivals", "500 ml jar at under ₹700", "2200 mAh battery", "22,000 RPM blade speed"],
    cons: ["45 W is genuinely weak — soft fruit only, ice claim optimistic", "No real warranty", "Budget build quality"],
    scores: {
      reliability: 4.5,
      power: 3.5,
      battery: 5.5,
      value: 7.5,
      support: 3,
      capacity: 6.5,
    },
    fullSpec: {
      motorWatts: "45 W",
      motorVoltage: "Not officially published",
      rpm: "22,000 RPM",
      blades: "Not officially published",
      iceCrushing: "Claimed yes (with liquid)",
      blendTime: "Not officially published",
      batteryMah: "2200 mAh",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "500 ml",
      jarMaterial: "BPA-free plastic",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "Seller-dependent",
      rating: "Not officially published",
      madeIn: "China (rebadged import)",
    },
    buyUrl: "https://www.amazon.in/Qlect-Portable-Blender-Smoothie-Juices/dp/B0DHX76Y38",
    buyStore: "Amazon.in",
  },
  {
    id: "qlect-45w-400",
    brand: "QLECT",
    model: "45W Compact (400ml)",
    price: 628,
    motor: "45 W",
    battery: "1500–1800 mAh",
    capacity: "400 ml",
    charging: "USB",
    icecrush: "No",
    highlight: "QLECT's smaller sibling — removable base, 30×30×90mm-class compact build",
    pros: ["Cheapest listing in this comparison (~₹450–700 street)", "Removable base for cleaning", "Honest 45 W rating"],
    cons: ["Small 400 ml jar and 1500–1800 mAh battery", "Soft fruit only", "No real warranty"],
    scores: {
      reliability: 4.5,
      power: 3.5,
      battery: 4.5,
      value: 7,
      support: 3,
      capacity: 5,
    },
    fullSpec: {
      motorWatts: "45 W",
      motorVoltage: "Not officially published",
      rpm: "22,000 RPM",
      blades: "Not officially published",
      iceCrushing: "No",
      blendTime: "Not officially published",
      batteryMah: "1500–1800 mAh (listing varies)",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "400 ml",
      jarMaterial: "BPA-free plastic",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "Seller-dependent",
      rating: "Not officially published",
      madeIn: "China (rebadged import)",
    },
    buyUrl: "https://www.amazon.in/Portable-Electric-Rechargeable-Smoothie-Battery-Smoothie/dp/B0F9YGHHXG",
    buyStore: "Amazon.in",
  },
  {
    id: "ownair-180",
    brand: "OWNAIR",
    model: "180W (5000mAh, 450ml)",
    price: 2699,
    motor: "180 W",
    battery: "5000 mAh",
    capacity: "450 ml",
    charging: "USB",
    icecrush: "Claimed yes",
    highlight: "Second-biggest battery in the comparison after the 6000mAh models",
    pros: ["5000 mAh battery", "180 W published motor", "Decent 450 ml jar"],
    cons: ["Little-known brand, thin review history", "Support/service unproven", "Priced against far better-supported InstaCuppa"],
    scores: {
      reliability: 5,
      power: 7,
      battery: 9,
      value: 5,
      support: 4,
      capacity: 6,
    },
    fullSpec: {
      motorWatts: "180 W",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Claimed yes",
      blendTime: "Not officially published",
      batteryMah: "5000 mAh",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "450 ml",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "Seller-dependent",
      rating: "Not officially published",
      madeIn: "China (rebadged import)",
    },
    buyUrl: "https://www.amazon.in/s?k=OWNAIR+portable+blender",
    buyStore: "Amazon.in",
  },
  {
    id: "goodscity-gc141",
    brand: "Goodscity",
    model: "GC141 (400ml)",
    price: 1999,
    motor: "Not officially published",
    battery: "Not officially published",
    capacity: "400 ml",
    charging: "USB",
    icecrush: "Not officially published",
    highlight: "One of the few small brands offering a stated 1-year warranty",
    pros: ["Stated 1-year warranty (rare at this tier)", "6 sharp stainless blades", "Food-grade 400 ml jar"],
    cons: ["No published wattage or battery capacity", "Small brand, unknown service reality", "400 ml is on the small side"],
    scores: {
      reliability: 5,
      power: 5,
      battery: 4.5,
      value: 5,
      support: 4.5,
      capacity: 5,
    },
    fullSpec: {
      motorWatts: "Not officially published",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "6-blade stainless steel",
      iceCrushing: "Not officially published",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "400 ml",
      jarMaterial: "Food-grade plastic",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "1 year (brand stated)",
      rating: "Not officially published",
      madeIn: "China (rebadged import)",
    },
    buyUrl: "https://www.amazon.in/Goodscity-Smoothie-Portable-Rechargeable-Warranty/dp/B0C3VYBVDK",
    buyStore: "Amazon.in",
  },
  {
    id: "popbabies-360",
    brand: "Popbabies",
    model: "360W (700ml, IPX7)",
    price: 1899,
    motor: "360 W claimed (12 V copper motor)",
    battery: "6000 mAh",
    capacity: "700 ml",
    charging: "USB",
    icecrush: "Claimed yes",
    highlight: "Same 700ml/6000mAh/12V platform as Kilig and SUPERSTUD — with an IPX7 waterproof claim",
    pros: ["700 ml jar + 6000 mAh at under ₹2,000", "IPX7 waterproof claim", "10-day replacement window"],
    cons: ["Identical platform to the SUPERSTUD that failed twice — same reliability risk", "360 W claim unverified", "No warranty beyond 10-day replacement"],
    scores: {
      reliability: 3,
      power: 7,
      battery: 9.5,
      value: 6.5,
      support: 2.5,
      capacity: 10,
    },
    fullSpec: {
      motorWatts: "360 W claimed (unverified)",
      motorVoltage: "12 V",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Claimed yes",
      blendTime: "Not officially published",
      batteryMah: "6000 mAh",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "700 ml",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "IPX7 waterproof claim",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "10 × 10 × 30 cm",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "10-day replacement only",
      rating: "Not officially published",
      madeIn: "China (rebadged import)",
    },
    buyUrl: "https://www.amazon.in/360W-Portable-Blender-Smoothie-Juices/dp/B0DPXJ4RVP",
    buyStore: "Amazon.in",
  },
  {
    id: "cello-200",
    brand: "Cello",
    model: "Portable Blender 200W",
    price: 1800,
    motor: "200 W",
    battery: "Not officially published",
    capacity: "Not officially published",
    charging: "USB",
    icecrush: "Not officially published",
    highlight: "Household Indian name, but the portable model is only patchily distributed",
    pros: ["Well-known Indian kitchenware brand", "Published 200 W rating"],
    cons: ["Hard to find in mainline retail — mostly B2B/IndiaMART listings", "No published battery or jar specs", "Warranty handling unclear for this SKU"],
    scores: {
      reliability: 5.5,
      power: 6.5,
      battery: 4.5,
      value: 5,
      support: 6,
      capacity: 4.5,
    },
    fullSpec: {
      motorWatts: "200 W",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Not officially published",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "Not officially published",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Yes (brand)",
      warranty: "Unclear for this SKU",
      rating: "Not officially published",
      madeIn: "Indian brand, made in China",
    },
    buyUrl: "https://m.indiamart.com/proddetail/cello-portable-blender-2855212525391.html",
    buyStore: "IndiaMART",
  },
  {
    id: "keekos-210",
    brand: "Keekos",
    model: "210W USB-C (400ml)",
    price: 1824,
    motor: "210 W claimed",
    battery: "4000 mAh",
    capacity: "400 ml",
    charging: "USB Type-C",
    icecrush: "Claimed yes",
    highlight: "Best-reviewed of the Flipkart mid-tier — 4.1★ across 219 ratings",
    pros: ["4.1★ from 219 ratings — unusually good for this tier", "4000 mAh + USB-C", "Ice-crush claim with liquid"],
    cons: ["210 W claim unverified", "400 ml jar is small", "No stated warranty"],
    scores: {
      reliability: 5,
      power: 6,
      battery: 8,
      value: 6.5,
      support: 3,
      capacity: 5,
    },
    fullSpec: {
      motorWatts: "210 W claimed",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Claimed yes",
      blendTime: "Not officially published",
      batteryMah: "4000 mAh",
      blendsPerCharge: "Not officially published",
      chargePort: "USB Type-C",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "400 ml",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "Not stated",
      rating: "4.1★ (Flipkart, 219 ratings)",
      madeIn: "China (rebadged import)",
    },
    buyUrl: "https://www.flipkart.com/keekos-portable-blender-210watt-4000mah-shakes-ice-etc-usb-c-port-400ml-200-w-juicer-mixer-grinder/p/itmc8616d5baeba3",
    buyStore: "Flipkart",
  },
  {
    id: "vozica-25",
    brand: "Vozica",
    model: "Mini Personal Juicer (25W)",
    price: 920,
    motor: "25 W",
    battery: "Not officially published",
    capacity: "Not officially published",
    charging: "USB",
    icecrush: "No",
    highlight: "Well-rated (4.1★) but the weakest motor in the whole comparison",
    pros: ["4.1★ from 201 ratings", "Cheap and genuinely tiny"],
    cons: ["25 W — juice-only, will stall on anything firm", "No published battery or jar specs", "No warranty"],
    scores: {
      reliability: 5,
      power: 1.5,
      battery: 4,
      value: 5,
      support: 2.5,
      capacity: 4,
    },
    fullSpec: {
      motorWatts: "25 W",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "No",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "Not officially published",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "Not stated",
      rating: "4.1★ (Flipkart, 201 ratings)",
      madeIn: "China (rebadged import)",
    },
    buyUrl: "https://www.flipkart.com/vozica-portable-blender-juicerusb-rechargeable-mini-personal-juicer-shakes-and-smoothie-25-w-juicer-mixer-grinder/p/itmf07c95280d4ee",
    buyStore: "Flipkart",
  },
  {
    id: "wanzhow-450",
    brand: "Wanzhow",
    model: "Juicer Cup 450W (generic import)",
    price: 845,
    motor: "450 W claimed",
    battery: "Not officially published",
    capacity: "Not officially published",
    charging: "USB",
    icecrush: "Not officially published",
    highlight: "Rebadged generic Flipkart import — listed for completeness; specs are marketing claims",
    pros: ["Cheap (₹845)", "Widely available on Flipkart"],
    cons: ["450 W claimed claim is a peak/marketing figure — unverified", "10-day replacement only", "Rebadged generic import — same hardware sold under many names", "No published battery, jar or safety specs"],
    scores: {
      reliability: 3,
      power: 4,
      battery: 3.5,
      value: 5.5,
      support: 2.5,
      capacity: 4,
    },
    fullSpec: {
      motorWatts: "450 W claimed (peak marketing figure)",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Not officially published",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "Not officially published",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "10-day replacement only",
      rating: "3.3★ (Flipkart, 492 ratings)",
      madeIn: "China (rebadged generic import)",
    },
    buyUrl: "https://www.flipkart.com/wanzhow-juicer-cup-450-w/p/itme4800d26bb24a",
    buyStore: "Flipkart",
  },
  {
    id: "zinsy-40",
    brand: "Zinsy",
    model: "Mini Personal Juicer 40W (generic import)",
    price: 798,
    motor: "40 W",
    battery: "Not officially published",
    capacity: "Not officially published",
    charging: "USB",
    icecrush: "Not officially published",
    highlight: "Rebadged generic Flipkart import — listed for completeness; specs are marketing claims",
    pros: ["Cheap (₹798)", "Widely available on Flipkart"],
    cons: ["40 W claim is a peak/marketing figure — unverified", "No warranty", "Rebadged generic import — same hardware sold under many names", "No published battery, jar or safety specs"],
    scores: {
      reliability: 3.5,
      power: 2,
      battery: 3.5,
      value: 4.5,
      support: 1.5,
      capacity: 4,
    },
    fullSpec: {
      motorWatts: "40 W (peak marketing figure)",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Not officially published",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "Not officially published",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "No warranty",
      rating: "3.7★ (Flipkart, 41 ratings)",
      madeIn: "China (rebadged generic import)",
    },
    buyUrl: "https://www.flipkart.com/zinsy-portable-blender-juicerusb-rechargeable-mini-personal-juicer-shakes-and-smoothie-40-w-juicer-mixer-grinder/p/itmbf8adc1205d7b",
    buyStore: "Flipkart",
  },
  {
    id: "bhakti-200",
    brand: "Bhakti",
    model: "NG-01 200W (generic import)",
    price: 823,
    motor: "200 W claimed",
    battery: "Not officially published",
    capacity: "Not officially published",
    charging: "USB",
    icecrush: "Not officially published",
    highlight: "Rebadged generic Flipkart import — listed for completeness; specs are marketing claims",
    pros: ["Cheap (₹823)", "Widely available on Flipkart"],
    cons: ["200 W claimed claim is a peak/marketing figure — unverified", "No warranty", "Rebadged generic import — same hardware sold under many names", "No published battery, jar or safety specs"],
    scores: {
      reliability: 3,
      power: 3.5,
      battery: 3.5,
      value: 4.5,
      support: 1.5,
      capacity: 4,
    },
    fullSpec: {
      motorWatts: "200 W claimed (peak marketing figure)",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Not officially published",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "Not officially published",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "No warranty",
      rating: "3.2★ (Flipkart, 104 ratings)",
      madeIn: "China (rebadged generic import)",
    },
    buyUrl: "https://www.flipkart.com/bhakti-ng-01-200-w-juicer/p/itm38bf33cac1206",
    buyStore: "Flipkart",
  },
  {
    id: "sai-200",
    brand: "Sai Enterprises",
    model: "Portable USB Juicer Pro 200W (generic import)",
    price: 829,
    motor: "200 W claimed",
    battery: "Not officially published",
    capacity: "Not officially published",
    charging: "USB",
    icecrush: "Not officially published",
    highlight: "Rebadged generic Flipkart import — listed for completeness; specs are marketing claims",
    pros: ["Cheap (₹829)", "Widely available on Flipkart"],
    cons: ["200 W claimed claim is a peak/marketing figure — unverified", "10-day replacement only", "Rebadged generic import — same hardware sold under many names", "No published battery, jar or safety specs"],
    scores: {
      reliability: 3,
      power: 3.5,
      battery: 3.5,
      value: 4.5,
      support: 2.5,
      capacity: 4,
    },
    fullSpec: {
      motorWatts: "200 W claimed (peak marketing figure)",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Not officially published",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "Not officially published",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "10-day replacement only",
      rating: "3.2★ (Flipkart, 96 ratings)",
      madeIn: "China (rebadged generic import)",
    },
    buyUrl: "https://www.flipkart.com/sai-enterprises-portable-usb-juicer-pro-200-w/p/itmbd89b180bcd83",
    buyStore: "Flipkart",
  },
  {
    id: "guggu-450",
    brand: "GUGGU",
    model: "PRO 450W (generic import)",
    price: 589,
    motor: "450 W claimed",
    battery: "Not officially published",
    capacity: "Not officially published",
    charging: "USB",
    icecrush: "Not officially published",
    highlight: "Rebadged generic Flipkart import — listed for completeness; specs are marketing claims",
    pros: ["Cheap (₹589)", "Widely available on Flipkart"],
    cons: ["450 W claimed claim is a peak/marketing figure — unverified", "No warranty", "Rebadged generic import — same hardware sold under many names", "No published battery, jar or safety specs"],
    scores: {
      reliability: 2.5,
      power: 4,
      battery: 3.5,
      value: 5.5,
      support: 1.5,
      capacity: 4,
    },
    fullSpec: {
      motorWatts: "450 W claimed (peak marketing figure)",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Not officially published",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "Not officially published",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "No warranty",
      rating: "3.0★ (Flipkart, 30 ratings)",
      madeIn: "China (rebadged generic import)",
    },
    buyUrl: "https://www.flipkart.com/guggu-pro-450-w-juicer-mixer-grinder/p/itm33142c06ecf0b",
    buyStore: "Flipkart",
  },
  {
    id: "yaroh-200",
    brand: "YAROH",
    model: "Pro Fruit Juicer 200W (generic import)",
    price: 601,
    motor: "200 W claimed",
    battery: "Not officially published",
    capacity: "Not officially published",
    charging: "USB",
    icecrush: "Not officially published",
    highlight: "Rebadged generic Flipkart import — listed for completeness; specs are marketing claims",
    pros: ["Cheap (₹601)", "Widely available on Flipkart"],
    cons: ["200 W claimed claim is a peak/marketing figure — unverified", "No warranty", "Rebadged generic import — same hardware sold under many names", "No published battery, jar or safety specs"],
    scores: {
      reliability: 2.5,
      power: 3.5,
      battery: 3.5,
      value: 5,
      support: 1.5,
      capacity: 4,
    },
    fullSpec: {
      motorWatts: "200 W claimed (peak marketing figure)",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Not officially published",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "Not officially published",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "No warranty",
      rating: "3.0★ (Flipkart, 62 ratings)",
      madeIn: "China (rebadged generic import)",
    },
    buyUrl: "https://www.flipkart.com/yaroh-pro-fruit-juicer-200-w-mixer-grinder/p/itme9103c9486f05",
    buyStore: "Flipkart",
  },
  {
    id: "syara-200",
    brand: "SYARA",
    model: "Pro Fruit Juicer 200W (generic import)",
    price: 849,
    motor: "200 W claimed",
    battery: "Not officially published",
    capacity: "Not officially published",
    charging: "USB",
    icecrush: "Not officially published",
    highlight: "Rebadged generic Flipkart import — listed for completeness; specs are marketing claims",
    pros: ["Cheap (₹849)", "Widely available on Flipkart"],
    cons: ["200 W claimed claim is a peak/marketing figure — unverified", "No warranty", "Rebadged generic import — same hardware sold under many names", "No published battery, jar or safety specs"],
    scores: {
      reliability: 3,
      power: 3.5,
      battery: 3.5,
      value: 4,
      support: 1.5,
      capacity: 4,
    },
    fullSpec: {
      motorWatts: "200 W claimed (peak marketing figure)",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Not officially published",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "Not officially published",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "No warranty",
      rating: "3.5★ (Flipkart, 19 ratings)",
      madeIn: "China (rebadged generic import)",
    },
    buyUrl: "https://www.flipkart.com/syara-pro-fruit-juicer-200-w-mixer-grinder/p/itmb886dd7f937d8",
    buyStore: "Flipkart",
  },
  {
    id: "fellkon-220",
    brand: "Fellkon",
    model: "Juicer Mixer 220W (generic import)",
    price: 849,
    motor: "220 W claimed",
    battery: "Not officially published",
    capacity: "Not officially published",
    charging: "USB",
    icecrush: "Not officially published",
    highlight: "Rebadged generic Flipkart import — listed for completeness; specs are marketing claims",
    pros: ["Cheap (₹849)", "Widely available on Flipkart"],
    cons: ["220 W claimed claim is a peak/marketing figure — unverified", "Not stated", "Rebadged generic import — same hardware sold under many names", "No published battery, jar or safety specs"],
    scores: {
      reliability: 3,
      power: 3.5,
      battery: 3.5,
      value: 4,
      support: 2.5,
      capacity: 4,
    },
    fullSpec: {
      motorWatts: "220 W claimed (peak marketing figure)",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Not officially published",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "Not officially published",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "Not stated",
      rating: "3.0★ (Flipkart, 40 ratings)",
      madeIn: "China (rebadged generic import)",
    },
    buyUrl: "https://www.flipkart.com/fellkon-juicer-mixer-220-w/p/itm48c429b8f6e89",
    buyStore: "Flipkart",
  },
  {
    id: "nexushut-220",
    brand: "NexusHut",
    model: "Rechargeable Juicer 220W (generic import)",
    price: 567,
    motor: "220 W claimed",
    battery: "Not officially published",
    capacity: "Not officially published",
    charging: "USB",
    icecrush: "Not officially published",
    highlight: "Rebadged generic Flipkart import — listed for completeness; specs are marketing claims",
    pros: ["Cheap (₹567)", "Widely available on Flipkart"],
    cons: ["220 W claimed claim is a peak/marketing figure — unverified", "Not stated", "Rebadged generic import — same hardware sold under many names", "No published battery, jar or safety specs"],
    scores: {
      reliability: 3,
      power: 3.5,
      battery: 3.5,
      value: 5.5,
      support: 2.5,
      capacity: 4,
    },
    fullSpec: {
      motorWatts: "220 W claimed (peak marketing figure)",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Not officially published",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "Not officially published",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "Not stated",
      rating: "3.4★ (Flipkart, 33 ratings)",
      madeIn: "China (rebadged generic import)",
    },
    buyUrl: "https://www.flipkart.com/nexushut-rechargeable-juicer-220-w-mixer-grinder/p/itm5505e1b280e79",
    buyStore: "Flipkart",
  },
  {
    id: "jackklein-220",
    brand: "Jack Klein",
    model: "USB Portable Juicer 220W (generic import)",
    price: 813,
    motor: "220 W claimed",
    battery: "Not officially published",
    capacity: "Not officially published",
    charging: "USB",
    icecrush: "Not officially published",
    highlight: "Rebadged generic Flipkart import — listed for completeness; specs are marketing claims",
    pros: ["Cheap (₹813)", "Widely available on Flipkart"],
    cons: ["220 W claimed claim is a peak/marketing figure — unverified", "Not stated", "Rebadged generic import — same hardware sold under many names", "No published battery, jar or safety specs"],
    scores: {
      reliability: 3,
      power: 3.5,
      battery: 3.5,
      value: 4,
      support: 2.5,
      capacity: 4,
    },
    fullSpec: {
      motorWatts: "220 W claimed (peak marketing figure)",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Not officially published",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "Not officially published",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "Not stated",
      rating: "3.4★ (Flipkart, 9 ratings)",
      madeIn: "China (rebadged generic import)",
    },
    buyUrl: "https://www.flipkart.com/jack-klein-usb-portable-juicer-220-w-mixer-grinder/p/itm7f68bbb9750e4",
    buyStore: "Flipkart",
  },
  {
    id: "aftivo-350",
    brand: "AFTIVO",
    model: "350W Juicer (generic import)",
    price: 998,
    motor: "350 W claimed",
    battery: "Not officially published",
    capacity: "Not officially published",
    charging: "USB",
    icecrush: "Not officially published",
    highlight: "Rebadged generic Flipkart import — listed for completeness; specs are marketing claims",
    pros: ["Cheap (₹998)", "Widely available on Flipkart"],
    cons: ["350 W claimed claim is a peak/marketing figure — unverified", "Not stated", "Rebadged generic import — same hardware sold under many names", "No published battery, jar or safety specs"],
    scores: {
      reliability: 3.5,
      power: 4,
      battery: 3.5,
      value: 4,
      support: 2.5,
      capacity: 4,
    },
    fullSpec: {
      motorWatts: "350 W claimed (peak marketing figure)",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Not officially published",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "Not officially published",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "Not stated",
      rating: "4.3★ (Flipkart, 7 ratings)",
      madeIn: "China (rebadged generic import)",
    },
    buyUrl: "https://www.flipkart.com/aftivo-0-350-w-juicer/p/itm3514495bf683d",
    buyStore: "Flipkart",
  },
  {
    id: "tenring-250",
    brand: "Tenring",
    model: "6-Blade 250W (generic import)",
    price: 591,
    motor: "250 W claimed",
    battery: "Not officially published",
    capacity: "Not officially published",
    charging: "USB",
    icecrush: "Not officially published",
    highlight: "Rebadged generic Flipkart import — listed for completeness; specs are marketing claims",
    pros: ["Cheap (₹591)", "Widely available on Flipkart"],
    cons: ["250 W claimed claim is a peak/marketing figure — unverified", "Manufacturing-defect replacement only (email-based)", "Rebadged generic import — same hardware sold under many names", "No published battery, jar or safety specs"],
    scores: {
      reliability: 2.5,
      power: 3.5,
      battery: 3.5,
      value: 5,
      support: 2.5,
      capacity: 4,
    },
    fullSpec: {
      motorWatts: "250 W claimed (peak marketing figure)",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Not officially published",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "Not officially published",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "Manufacturing-defect replacement only (email-based)",
      rating: "2.7★ (Flipkart, 23 ratings)",
      madeIn: "China (rebadged generic import)",
    },
    buyUrl: "https://www.flipkart.com/tenring-6-blade-smoothie-maker-usb-juicer-bottle-blender-250-w/p/itm8146440704448",
    buyStore: "Flipkart",
  },
  {
    id: "tenring-150",
    brand: "Tenring",
    model: "Wireless 150W (generic import)",
    price: 591,
    motor: "150 W claimed",
    battery: "Not officially published",
    capacity: "Not officially published",
    charging: "USB",
    icecrush: "Not officially published",
    highlight: "Rebadged generic Flipkart import — listed for completeness; specs are marketing claims",
    pros: ["Cheap (₹591)", "Widely available on Flipkart"],
    cons: ["150 W claimed claim is a peak/marketing figure — unverified", "Manufacturing-defect replacement only (email-based)", "Rebadged generic import — same hardware sold under many names", "No published battery, jar or safety specs"],
    scores: {
      reliability: 3,
      power: 3,
      battery: 3.5,
      value: 5,
      support: 2.5,
      capacity: 4,
    },
    fullSpec: {
      motorWatts: "150 W claimed (peak marketing figure)",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Not officially published",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "Not officially published",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "Manufacturing-defect replacement only (email-based)",
      rating: "3.5★ (Flipkart, 21 ratings)",
      madeIn: "China (rebadged generic import)",
    },
    buyUrl: "https://www.flipkart.com/tenring-wireless-rechargeable-blender-usb-portable-juicer-smoothies-milkshakes-150-w-mixer/p/itm6c5dc2e70c954",
    buyStore: "Flipkart",
  },
  {
    id: "grebe-100",
    brand: "Grebe",
    model: "Electric Juicer 100W (generic import)",
    price: 819,
    motor: "100 W claimed",
    battery: "Not officially published",
    capacity: "Not officially published",
    charging: "USB",
    icecrush: "Not officially published",
    highlight: "Rebadged generic Flipkart import — listed for completeness; specs are marketing claims",
    pros: ["Cheap (₹819)", "Widely available on Flipkart"],
    cons: ["100 W claimed claim is a peak/marketing figure — unverified", "No warranty", "Rebadged generic import — same hardware sold under many names", "No published battery, jar or safety specs"],
    scores: {
      reliability: 3,
      power: 3,
      battery: 3.5,
      value: 4,
      support: 1.5,
      capacity: 4,
    },
    fullSpec: {
      motorWatts: "100 W claimed (peak marketing figure)",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Not officially published",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "Not officially published",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "No warranty",
      rating: "Not enough ratings yet",
      madeIn: "China (rebadged generic import)",
    },
    buyUrl: "https://www.flipkart.com/grebe-blender-electric-juicers-100-w-juicer-mixer-grinder/p/itm0dcb6493af408",
    buyStore: "Flipkart",
  },
  {
    id: "ajfuture-220",
    brand: "AJFuture",
    model: "USB Portable Juicer 220W (generic import)",
    price: 847,
    motor: "220 W claimed",
    battery: "Not officially published",
    capacity: "Not officially published",
    charging: "USB",
    icecrush: "Not officially published",
    highlight: "Rebadged generic Flipkart import — listed for completeness; specs are marketing claims",
    pros: ["Cheap (₹847)", "Widely available on Flipkart"],
    cons: ["220 W claimed claim is a peak/marketing figure — unverified", "Not stated", "Rebadged generic import — same hardware sold under many names", "No published battery, jar or safety specs"],
    scores: {
      reliability: 3,
      power: 3.5,
      battery: 3.5,
      value: 4,
      support: 2.5,
      capacity: 4,
    },
    fullSpec: {
      motorWatts: "220 W claimed (peak marketing figure)",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Not officially published",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "Not officially published",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "Not stated",
      rating: "Not enough ratings yet",
      madeIn: "China (rebadged generic import)",
    },
    buyUrl: "https://www.flipkart.com/ajfuture-usb-portable-juicer-220-w-mixer-grinder/p/itm71f9c72233639",
    buyStore: "Flipkart",
  },
  {
    id: "mishvard-180",
    brand: "MISHVARD",
    model: "Wireless Rechargeable 180W (generic import)",
    price: 998,
    motor: "180 W claimed",
    battery: "Not officially published",
    capacity: "Not officially published",
    charging: "USB",
    icecrush: "Not officially published",
    highlight: "Rebadged generic Flipkart import — listed for completeness; specs are marketing claims",
    pros: ["Cheap (₹998)", "Widely available on Flipkart"],
    cons: ["180 W claimed claim is a peak/marketing figure — unverified", "Not stated", "Rebadged generic import — same hardware sold under many names", "No published battery, jar or safety specs"],
    scores: {
      reliability: 2,
      power: 3,
      battery: 3.5,
      value: 3,
      support: 2.5,
      capacity: 4,
    },
    fullSpec: {
      motorWatts: "180 W claimed (peak marketing figure)",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Not officially published",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "Not officially published",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "Not stated",
      rating: "1.0★ (Flipkart, 3 ratings)",
      madeIn: "China (rebadged generic import)",
    },
    buyUrl: "https://www.flipkart.com/mishvard-wireless-rechargeable-blender-portable-juicer-smoothies-milkshakes-180-w/p/itm19012bcda4e1b",
    buyStore: "Flipkart",
  },
  {
    id: "skynest-105",
    brand: "SKYNEST",
    model: "Mini Smoothie Bottle 105W (generic import)",
    price: 500,
    motor: "105 W claimed",
    battery: "Not officially published",
    capacity: "Not officially published",
    charging: "USB",
    icecrush: "Not officially published",
    highlight: "Rebadged generic Flipkart import — listed for completeness; specs are marketing claims",
    pros: ["Cheap (₹500)", "Widely available on Flipkart"],
    cons: ["105 W claimed claim is a peak/marketing figure — unverified", "Not stated", "Rebadged generic import — same hardware sold under many names", "No published battery, jar or safety specs"],
    scores: {
      reliability: 3,
      power: 3,
      battery: 3.5,
      value: 5.5,
      support: 2.5,
      capacity: 4,
    },
    fullSpec: {
      motorWatts: "105 W claimed (peak marketing figure)",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Not officially published",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "Not officially published",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "Not stated",
      rating: "Not enough ratings yet",
      madeIn: "China (rebadged generic import)",
    },
    buyUrl: "https://www.flipkart.com/skynest-portable-usb-rechargeable-juicer-blender-mini-smoothie-maker-bottle-105-w-mixer-grinder/p/itm765ed33bac345",
    buyStore: "Flipkart",
  },
  {
    id: "grantox-105",
    brand: "Grantox",
    model: "Mini Smoothie Bottle 105W (generic import)",
    price: 615,
    motor: "105 W claimed",
    battery: "Not officially published",
    capacity: "Not officially published",
    charging: "USB",
    icecrush: "Not officially published",
    highlight: "Rebadged generic Flipkart import — listed for completeness; specs are marketing claims",
    pros: ["Cheap (₹615)", "Widely available on Flipkart"],
    cons: ["105 W claimed claim is a peak/marketing figure — unverified", "Not stated", "Rebadged generic import — same hardware sold under many names", "No published battery, jar or safety specs"],
    scores: {
      reliability: 3,
      power: 3,
      battery: 3.5,
      value: 5,
      support: 2.5,
      capacity: 4,
    },
    fullSpec: {
      motorWatts: "105 W claimed (peak marketing figure)",
      motorVoltage: "Not officially published",
      rpm: "Not officially published",
      blades: "Not officially published",
      iceCrushing: "Not officially published",
      blendTime: "Not officially published",
      batteryMah: "Not officially published",
      blendsPerCharge: "Not officially published",
      chargePort: "USB",
      chargeTime: "Not officially published",
      batteryIndicator: "Not officially published",
      jarCapacity: "Not officially published",
      jarMaterial: "Not officially published",
      lid: "Not officially published",
      leakProof: "Not officially published",
      selfCleaning: "Not officially published",
      safetyLock: "Not officially published",
      weight: "Not officially published",
      dimensions: "Not officially published",
      colours: "Not officially published",
      bisCertified: "Not officially published",
      warranty: "Not stated",
      rating: "Not enough ratings yet",
      madeIn: "China (rebadged generic import)",
    },
    buyUrl: "https://www.flipkart.com/grantox-portable-usb-rechargeable-juicer-blender-mini-smoothie-maker-bottle-105-w-mixer-grinder/p/itm3211db17f2eca",
    buyStore: "Flipkart",
  },
];
